### ISSUE TITLE
How do I set the root directory where camlistore should be initialized?

### ISSUE THREAD

**Issue by gdeverlant** [camlistore/camlistore#1003]
Greetings to all!

When I run camlistored.exe by default the daemon initialize the instance in this folder:

**C:\Users\{username}\AppData\Roaming\Camlistore**

I want to know if there is a way to put a custom path where the initialization should be done?

E.g: camlistored --initPath G:\\Camlistore

Thanx.

**Comment by mpl** [comment]
@gdeverlant I'm sorry, but I'm not familiar with Windows, so I don't really understand the question. Why does it matter where you're running the binary from? As far as I know the working directory has no influence at all on what camlistored does, so it should not matter.
In any case, can't you first cd into whatever directory you want, and run camlistored from there? Wouldn't that achieve what you want?

Maybe @tajtiattila can help you better than me though.

Oh, or are you talking about the location of the configuration files, such as server-config.json?

**Comment by bradfitz** [comment]
@gdeverlant, I assume you want your blobs and index on G: ? You can just modify the `server-config.json` file to point to your G: drive. See https://perkeep.org/doc/server-config. You'll want `blobPath` and `levelDB` set to something on G: probably.

**Comment by gdeverlant** [comment]
@bradfitz I'm aware if the server-config.json file but it doesn't fit to the use I have in mind. I'm integrating Peerkeep to my software and I'm doing all the initialization for **camlistored** within my Software. I can launch **camlistored** via a NativeProcesse but I want to be able to define the initialization path of **camlistored** so that It reflects the settings panel of my app. Would it be possible to define directly via **camlistored** a custom path instead of **C:\Users{username}\AppData\Roaming\Camlistore**?

**Comment by bradfitz** [comment]
I see.

Oh, looks like there's already a way. camlistored uses the osutil package's:

```go
func CamliVarDir() string {
        if d := os.Getenv("CAMLI_VAR_DIR"); d != "" {
                return d
        }
        failInTests()
        switch runtime.GOOS {
        case "windows":
                return filepath.Join(os.Getenv("APPDATA"), "Camlistore")
...
```

Note that CAMLI_VAR_DIR check that's first. You can set that. Or you could set APPDATA too, but CAMLI_VAR_DIR looks better.

**Comment by gdeverlant** [comment]
But this is an environment variable. I think that it will be also good to have a cli param for that in case that we cannot deal with ENV variable due to permissions.

**Comment by tajtiattila** [comment]
You don't need to set environment variables in the system, just set them when you start camlistored. The Windows API CreateProcess* let you do that.

**Comment by gdeverlant** [comment]
I'm not using Windows API but rather this [https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/desktop/NativeProcess.html](https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/desktop/NativeProcess.html).

**Comment by tajtiattila** [comment]
I'm not familiar with ActionScript, sorry. If it cannot set environment variables for executables, you can have a batch file with

```
setenv CAMLI_VAR_DIR=...
path\to\camlistored
```

and run the batch file instead of camlistored directly. Or have a small app to launch it with the environment variables you need.

**Comment by gdeverlant** [comment]
Ok thanx for the info... I didn't think about that but it is one way. I was just trying to do less external dependencies possible with this cli option for camlistored.

**Comment by bradfitz** [comment]
@gdeverlant, we're curious what you're building. Care to share details?

If a environment variable will work, we'd prefer not to add more command-line flags. Any flags we include will add to user confusion and generally just overwhelming users running with `--help`. We try to keep them to a minimum.

**Comment by gdeverlant** [comment]
Yes I'm building a real-time non-linear video editing called Multiverses. This is supposed to be the next generation of browser for the Web 3.0. I hope that nobody will ever code web sites. This is purely based on video browsing. There is a knowledge economy based around the editor. It is like IPFS but Wikipedia of knowledge based on video as the root. I implemented my own OSGi framework that allows infinite amount of micro-apps being able to instantiated on the timeline. It will be used as a learning tool and a consciousness improvement technology. There will be also a patented algorithm which will tell which videos are true and which ones are garbage. There will be no place for content that has no real value on the network. It will be all P2P with no cloud infrastructure.

**Comment by bradfitz** [comment]
Sounds ambitious! Good luck!

I'll close this, since it sounds like the environment variable will work. Let us know if you find other issues.

**Comment by gdeverlant** [comment]
Thanx for the inputs.
