### ISSUE TITLE
Binaries size from 205MB to 72.9MB

### ISSUE THREAD

**Issue by gdeverlant** [camlistore/camlistore#1006]
I just wanted to share the results from my researches on how to reduce Go binary file size.

You can see on the left side VS on the right side:

![image](https://user-images.githubusercontent.com/26530975/34506298-d909c34a-f02b-11e7-8de7-e8e72af2eb6d.png)

A ratio of 65% smaller size for the binaries.

**Comment by bradfitz** [comment]
Are you also going to share details on how?

**Comment by gdeverlant** [comment]
You can go and download this amazing utility called UPX.

[https://blog.lwjgl.org/upx-compression/](https://blog.lwjgl.org/upx-compression/)

You just have to Drag&Drop your files into the executable and voila!

**Comment by gdeverlant** [comment]
This will reduce all Docker container size by 1000x times.

**Comment by bradfitz** [comment]
Oh, yes, I'm aware of UPX. I thought you'd done something to the code instead.

Generally we don't care about binary size ourselves. The other thing we'll probably do going forward as part of the rename (#981) is rename all of our client tools into one tool named `pk`, which will lower the total size, but that's just a happy side effect.

UPX hasn't always been safe for use on Go binaries, at least historically. We (in the Go project) only started testing that they were safe recently in https://github.com/golang/go/issues/16706

Thanks for the info!
