### ISSUE TITLE
website: no godoc for non-pkg packages

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#1010]
We serve godoc for e.g.

But not for other packages, like internal:

https://perkeep.org/internal/lru

Which also means people can't `go get` it.

Now, internal doesn't matter much, because people can't `go get` it anyway, but web-based docs would be nice.

And if we continue to move everything out of perkeep.org/pkg/* up a level, we'll need to resolve this more generally.

/cc @willnorris @mpl

**Comment by bradfitz** [comment]
Note that https://godoc.org/perkeep.org/internal/lru works at least.

**Comment by willnorris** [comment]
That's easy enough to fix, as long as we're reasonably sure we won't have other website content that would conflict.  I've only seen pkg/* packages move into internal so far.  So to clarify, the plan for the others is to just move it up to the top-level?  There's little enough actual website top-level content that avoiding conflicts shouldn't be *too* hard.

**Comment by bradfitz** [comment]
> So to clarify, the plan for the others is to just move it up to the top-level?

I think so. I don't think there will be too many once pkg is cleaned up. We'll have perkeep.org/blob and perkeep.org/importer/* and perkeep.org/blobserver/* etc.

We'll just have to make sure docs on the website are under /doc/ instead of putting docs at the top-level that might conflict with package names.
