### ISSUE TITLE
"Share" via webui fails auth when running behind a proxy

### ISSUE THREAD

**Issue by DanielHeath** [camlistore/camlistore#1013]
After upgrading camlistored (any version after 493cc283d2201dd6fd17b9d6f7bf2a79702a225d seems affected, didn't test earlier), attempting to share a file via the WebUI fails with the following message:

`could not get signer: got status "401 Unauthorized" from blobserver URL "/" during configuration discovery`

I've run 'copy as curl' from the network tab
```
curl 'https://camlistore.heath.cc/' \
  -H 'Host: camlistore.heath.cc' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0' \
  -H 'Accept: text/x-camli-configuration' \
  -H 'Accept-Language: en-US,en;q=0.5' --compressed \
  -H 'Referer: https://camlistore.heath.cc/ui/' \
  -H 'Authorization: Token <snip>' \
  -H 'DNT: 1' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache'
```

The response is:
```
HTTP/2 401
content-type: text/plain; charset=utf-8
server: Caddy
www-authenticate: Basic realm="Restricted"
x-content-type-options: nosniff
content-length: 17
date: Fri, 05 Jan 2018 11:28:39 GMT

401 Unauthorized
```

I'm using Caddy as a transparent reverse proxy and basic auth for camlistore.

**Comment by mpl** [comment]
thanks, I'll check it out shortly.

**Comment by mpl** [comment]
hmm, works for me at 7ed0b7ec5c4b81aea2930ccbb91271072efa768f
Do you have any way to test without Caddy, just so we can know whether the proxying is what we should be looking into?

**Comment by mpl** [comment]
I'm wondering, could it be that you're hitting the same issue as https://github.com/camlistore/camlistore/issues/816 ?

**Comment by DanielHeath** [comment]
I hit #816 when I set it up originally (because I put the auth on the proxy) but that was caused by the browser not sending basic auth credentials for requests that had token auth (this is different).

**Comment by DanielHeath** [comment]
I used SSH forwarding to get around the proxy and it works fine.

**Comment by DanielHeath** [comment]
Aha - I figured it out. I futzed with my configuration management stuff and it added basic auth to the Caddyfile as well as the camlistore instance, which introduced the same problem as #816 again.

**Comment by mpl** [comment]
cool
