### ISSUE TITLE
web: use File API's lastModifiedDate

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#317]
<pre>We don't use lastModifiedDate from the File API: <a href="http://www.w3.org/TR/FileAPI/#file">http://www.w3.org/TR/FileAPI/#file</a>

We should.</pre>

**Comment by dotMR** [comment]
I (quickly) looked into this one. It seems straight forward to submit the lastModifiedDate of the file as part of the form data to the upload helper, but I'm not yet familiar enough with the handler/upload code to understand what it will take to persist.

I'll try to spend some more time looking into it this weekend.

**Comment by dotMR** [comment]
https://camlistore-review.googlesource.com/#/c/4496/

**Comment by mpl** [comment]
a6fe834326210b04cf70fda1b6b3feb086f46c56

thanks Mario
