### ISSUE TITLE
arbitrary attribute editor

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#32]
<pre>The permanode editor page should have a way (mostly for debugging and/or advanced users)
to let you make any arbitrary claim.

a little more specifically, it should also be easy to easily modify the attributes,
making it easy to do add-attribute, set-attribute and del-attribute on any attribute
name (but with perhaps with a drop-down for the common known types?).  and perhaps with
a delete button to do del-attribute on existing ones.</pre>

**Comment by aboodman** [comment]
It's not very good, but there's a start there yeah. Improvements can be separate bugs.
