### ISSUE TITLE
kv: after putting 1100 files the camput cache gets corrupted

### ISSUE THREAD

**Issue by slspeek** [camlistore/camlistore#382]
<pre>After putting and modifying a large number of files with the camput tool, camput exits
immediately with code 1 and message:
2014/02/14 22:02:36 Could not create/open new have cache at
/home/steven/.cache/camlistore/camput.havecache.43d580bdfb0dc7ce880259137313aa73e5c807f5.kv,
unexpected EOF

It suffices to empty the cache in $HOME/.cache/camlistore</pre>

**Comment by mpl** [comment]
We do not really have any repro for this issues, or any hard evidence (for now) that github.com/syndtr/goleveldb is more (or less) reliable than cznic/kv. However, we do have benchmarks that show that the latter is way more efficient than the former for us, so I figure it can't hurt to change that in the statcache and havecache too.

Therefore:
https://camlistore-review.googlesource.com/5506
