### ISSUE TITLE
set up the buildbot to test our s3 client library against amazon

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#424]
<pre>Let's get this in a Docker container:

<a href="https://github.com/jubos/fake-s3">https://github.com/jubos/fake-s3</a>

And use it in our s3 tests.

Currently:

$ go test -v ./pkg/misc/amazon/s3/
=== RUN TestStringToSign
--- PASS: TestStringToSign (0.00 seconds)
=== RUN TestBucketFromHostname
--- PASS: TestBucketFromHostname (0.00 seconds)
=== RUN TestSignRequest
--- PASS: TestSignRequest (0.00 seconds)
=== RUN TestHasDotSuffix
--- PASS: TestHasDotSuffix (0.00 seconds)
=== RUN TestBuckets
--- PASS: TestBuckets (0.00 seconds)
        client_test.go:33: Skipping test; no AWS_ACCESS_KEY_ID or AWS_ACCESS_KEY_SECRET set in environment
=== RUN TestParseBuckets
--- PASS: TestParseBuckets (0.00 seconds)
PASS
ok      camlistore.org/pkg/misc/amazon/s3       0.005s

$ go test -v ./pkg/blobserver/s3/
=== RUN TestS3
--- SKIP: TestS3 (0.00 seconds)
        s3_test.go:31: Skipping manual test. To enable, set the environment variable CAMLI_S3_TEST_CONFIG_JSON to the path of a JSON configuration for the s3 storage type.
=== RUN TestNextStr
--- PASS: TestNextStr (0.00 seconds)
PASS
ok      camlistore.org/pkg/blobserver/s3        0.003s</pre>

**Comment by mpl** [comment]
update: a couple of month ago, upstream finally looked at my PR and fixed the max-keys issue.
So maybe I can revisit that issue.
Although we don't run a buildbot anymore.
But maybe we can launch a fake-s3 instance locally as part of our tests anyway. Or run it somewhere else.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8787

**Comment by mpl** [comment]
the docker image tarball is now up in GCS
