### ISSUE TITLE
mysql: change width of key/value

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#429]
<pre>Apparently VARCHAR(255) isn't enough.  This is 255 bytes and truncates the blobref:

Error parsing config: Caught panic: error instantiating handler for prefix
&quot;/my-search/&quot;, type &quot;search&quot;: error slurping index to memory: bogus
claim row:
&quot;claim|sha1-09dd79f2531185652c6ec1fd28e6c0c67b13c74f|94DE83C46401800C|2014-04-23T02:14:20.629653304Z|sha1-974a8cf7ce8982d7ee90c67a026e1ae5ff8dfbd9&quot;
-&gt;
&quot;set-attribute|title|Checkin+at+%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9+%D0%B0%D1%8D%D1%80%D0%BE%D0%BF%D0%BE%D1%80%D1%82+%D0%92%D0%BD%D1%83%D0%BA%D0%BE%D0%B2%D0%BE+%2F+Vnukovo+International+Airport+%28VKO%29|sha1-f72d&quot;

We should also document &amp; limit the size of permanode attribute names &amp; values.</pre>

**Comment by mpl** [comment]
I believe @aboodman stumbled upon this too while reindexing.
Can't we just go ahead and use varchar(65535) since mysql 5.0.3 (which is the required minimum version for this feature) has been out since 2005?

**Comment by bradfitz** [comment]
SGTM. Changed this to 0.9 milestone.

**Comment by aboodman** [comment]
Why not just make that column have type TEXT? Even with 65k it is still technically possible to have the same problem since Camlistore attribute values are not limited to any particular length.

**Comment by aboodman** [comment]
Also, it seems like there's another bug somewhere in the mysql bindings that a string can get silently truncated this way during insert.

**Comment by bradfitz** [comment]
We would have to verify that MyISAM and InnoDB don't store TEXT columns out of line. That would kill scan performance. And (if the same thing happens for key, ever), that they can be indexed.

**Comment by bradfitz** [comment]
@aboodman, perhaps, although IIRC SQL silently truncates stuff like that without error, at least historically or in some mode (the default?). We can probably force it to be caught, though.

**Comment by aboodman** [comment]
At least according to random article, InnoDB in modern MySQLs seems to store TEXT value in-page until it is huge: http://www.percona.com/blog/2010/02/09/blob-storage-in-innodb/.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4367 for discussion

**Comment by mpl** [comment]
ae38f657b8fe66b9925729bb64764a4355abf92d
