### ISSUE TITLE
ui: unexpected behaviour with middle-click on aspects links

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#434]
<pre>From the &quot;default&quot; (==image for now I suppose) aspect of an image permanode,
if I middle-click on the permanode, or blob aspect, a new tab is opened with the image
aspect, while the desired aspect (permanode, or blob) is opened in the current tab
(instead of in the new tab).

Chrome Version 34.0.1847.116 on linux

camli at 384b627b5ef652c4ee31ba4a6340468237442ae6</pre>

**Comment by aboodman** [comment]
This is long since fixed ... there are unique URLs for each aspect now.
