### ISSUE TITLE
Switch to new oauth2 library

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#489]
<pre>Apparently the community is moving from the goauth2 package to:

<a href="https://github.com/golang/oauth2">https://github.com/golang/oauth2</a>

We should switch, assuming all users of our current goauth2 continue to work with the
new code.

The current code has bugs:

<a href="https://code.google.com/p/goauth2/issues/detail?id=31">https://code.google.com/p/goauth2/issues/detail?id=31</a>
<a href="https://code.google.com/p/goauth2/issues/detail?id=32">https://code.google.com/p/goauth2/issues/detail?id=32</a>
<a href="https://code.google.com/p/goauth2/issues/detail?id=33">https://code.google.com/p/goauth2/issues/detail?id=33</a>
... and no mutex protecting the token state in RefreshToken called by RoundTrip (which
must be threadsafe)</pre>

**Comment by mpl** [comment]
foursquare: https://camlistore-review.googlesource.com/6050

**Comment by mpl** [comment]
picasa: https://camlistore-review.googlesource.com/6051

**Comment by mpl** [comment]
@tgulacsi I notice that none of the functions in third_party/github.com/tgulacsi/picago/auth.go seem to be used by picago. Also, much of the functionalities are implemented in go4.org/oauthutil if we need them. So my question is can I remove auth.go, so I can then remove third_party/code.google.com/p/goauth2/oauth out of Camlistore, or do you still need these functions in picago?

**Comment by tgulacsi** [comment]
Sure, remove as much as you can - I'm not using the command-line picago. If needed, I'll refactoring it.

**Comment by mpl** [comment]
Cool, done.
https://camlistore-review.googlesource.com/6052

**Comment by mpl** [comment]
07a633ecdb61235434ec93f0d08c4546c4025df3

**Comment by mpl** [comment]
@tgulacsi Do you have a suggestion (document it how/where?) about the re-login problem you experienced?

**Comment by tgulacsi** [comment]
Just some vague concept: document it at the importers section (webpage).

mpl <notifications@github.com> ezt írta (időpont: 2016. márc. 9., Sze
17:12):

**Comment by mpl** [comment]
oh, I've just realized that in any case, we can at least document it in the 0.10 release notes.
