### ISSUE TITLE
Rename "search roots" "favorites"

### ISSUE THREAD

**Issue by aboodman** [camlistore/camlistore#506]
<pre>See: <a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!topic/camlistore/YdKj4C_HJLQ</pre>

**Comment by dotMR** [comment]
(The link in the first comment didn't build correctly. Including again here)
https://groups.google.com/forum/#!topic/camlistore/YdKj4C_HJLQ

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6126

**Comment by mpl** [comment]
merged as 48695d85a033c5adff211e3a86d9e03322b9ef4e

Let's reopen a new issue when we actually want to discuss what this "favorites" nav should do.
