### ISSUE TITLE
Make left/right in detail views work again

### ISSUE THREAD

**Issue by aboodman** [camlistore/camlistore#508]
<pre>When I rewrote the UI recently, we lost the ability to page through images by pressing
the left right keys. It would be nice to get that back.

There are a lot of interesting bits to this:

- We need to pass an additional querystring param that is the query you're navigating
through. I'm not sure if we should have a separate querystring param for the case of
navigating through the children of a permanode, or whether we should express that as a
query. In general I like to avoid special cases, so if there is no downside to
expressing that as query, I'd prefer it.

- We need to load additional data periodically (and in the case of an external
navigation, immediately)

- We used to make the piggy march backwards when you navigate left ... would be nice to
bring this back</pre>

**Comment by mpl** [comment]
@aboodman If @bradfitz does not have time to give you the server-side before fosdem, do you think you could have the hacky way ready so I could apply it to my local copy before demo-ing please?
We're planning to show snapshots rather than an actual live demo, but just in case...

**Comment by aboodman** [comment]
Yeah, I'll make sure the patch still applies.

**Comment by aboodman** [comment]
I forgot about the fosdem thing until just now. I just checked and the patch only was failing to merge because of git being conservative. I rebased manually and it works fine (or as fine as it did before).

**Comment by aboodman** [comment]
And I uploaded a new rebased patch that applies cleanly to current head.

**Comment by bradfitz** [comment]
FOSDEM begins right now, but we don't have a release coming out today... just some demos. So no rush. But we do want to get a release out in the next few days.

**Comment by mpl** [comment]
@aboodman yeah, I had prepared snapshots of the UI, not planned on actually demoing it directly, so no worries.

**Comment by mpl** [comment]
@aboodman I think I have something server-side. I'll ping you again to see if we can insert a trivial test somewhere in the UI to send an "around" query (for a member of a container). No need to post a CL if I can't even get that working.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4636

I consider it a WIP because I haven't checked if that does not break the Continuation mechanism, I want to think about it some more.

Still, @bradfitz before I go on with that idea, could you have a look and let me know if I'm working at the right layer here? I don't think it can be done as a new constraint, because as soon as a constraint does not match, the candidate we try to match against is discarded. Which means we would discard all the "before" permanodes that we list (and should actually be results) until we hit the Around value.
So that's why I'm doing this processing "post constraint matching".

@aboodman , does it look like what you wanted?

**Comment by aboodman** [comment]
Thanks Mathieu, I'll patch it in and have a play soon.

**Comment by bradfitz** [comment]
Aaron, were you ever able to patch this in and see how it works?

Mathieu and I are hacking together for several days in Munich and would love to get a release out soon, especially if this works for you.

**Comment by aboodman** [comment]
Ugh, totally slipped my mind. Sorry guys.

Adding to TODO list for tomorrow.

- a

On Tue, Mar 31, 2015 at 12:23 PM, Brad Fitzpatrick <notifications@github.com

**Comment by aboodman** [comment]
Seems to work:
https://camlistore-review.googlesource.com/#/c/4166/

I want to test it a bit more before I land though.

**Comment by mpl** [comment]
server-side: 491bbf525e31ea405d0a5492b71195b4760e2656
client-side: b19e836c7bf5d8f5489f507e6a0502931593818b

@aboodman thanks, feel free to reopen if you notice a problem.
