### ISSUE TITLE
Saving configuration generates invalid config file

### ISSUE THREAD

**Issue by raff** [camlistore/camlistore#522]
<pre>Saving the configuration from <a href="http://localhost:3179/setup/">http://localhost:3179/setup/</a> when no database is
configured will generate a configuration file that cannot be read back (i.e. you can't
start the server until you remove it)

The initial configuration file has this line:
  &quot;dbNames&quot;: null

After the save the line is (I don't have the exact value anymore, but it's a string with
the word &quot;nil&quot; inside&quot;):
  &quot;dbNames&quot;: &quot;..nil..&quot; 

When restarting the server the application terminates with this error:
Error loading config file: Could not unmarshal into a serverconfig.Config: json: cannot
unmarshal string into Go value of type map[string]string

Somewhere when marshalling to JSON the empty map is serialized as a string. I fixed the
problem by changing the declaration of DBNames:

diff --git a/pkg/types/serverconfig/config.go b/pkg/types/serverconfig/config.go
index 75641be..f561768 100644
--- a/pkg/types/serverconfig/config.go
+++ b/pkg/types/serverconfig/config.go
@@ -71,7 +71,7 @@ type Config struct {
        //    &quot;index&quot;               (overrides 'dbname' key above)
        //    &quot;queue-sync-to-index&quot; (the sync queue to index things)
        //    &quot;queue-sync-to-s3&quot;    (the sync queue to replicate to s3)
-       DBNames map[string]string `json:&quot;dbNames&quot;`
+       DBNames map[string]string `json:&quot;dbNames,omitempty&quot;`
 
        ReplicateTo []interface{} `json:&quot;replicateTo,omitempty&quot;` // NOOP for now.
        // Publish maps a URL prefix path used as a root for published paths (a.k.a. a camliRoot path), to the configura</pre>

**Comment by mpl** [comment]
1bd76c138aeecf56e07a265b44d9f4a2d302dd48
