### ISSUE TITLE
camget fetching a share needs integration test

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#527]
<pre>camget fetching a share is broken, needs integration test

Seems like c.via is never being populated in pkg/client/get.go in func (c *Client)
FetchVia(b blob.Ref, v []blob.Ref) (body io.ReadCloser, size uint32, err error) {</pre>

**Comment by mpl** [comment]
While working on this, and noticing that camget with shares didn't work anymore, since the bug was not actually in camget, I figured it was more urgent to fix the bug first:

https://camlistore-review.googlesource.com/6571

integration test in another CL.

**Comment by mpl** [comment]
It turns out I had already written integration tests, but it they weren't enough the detect the breakage fixed by the above CL.

This new one should do:
https://camlistore-review.googlesource.com/6586
