### ISSUE TITLE
s3: sub-directory support

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#529]
<pre>Same as <a href="https://camlistore.org/issue/528">issue #528</a> (camlistore.org/issue/528) but for S3 buckets.

Not blocking the 0.9 release, though.</pre>

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5446

**Comment by mpl** [comment]
92d5c1d04530ca806fd2605bbe967f8735616e2c
