### ISSUE TITLE
Make gce/create.go easier to use

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#530]
<pre>We should make sure that the GCE create.go script is easy to use.

Users are encouraged now to try it out and report difficulties.  It's in
misc/gce/create.go currently.</pre>

**Comment by bradfitz** [comment]
Update this bug with what CLs were involved.

**Comment by bradfitz** [comment]
Convert it all to new oauth2 too?

**Comment by mpl** [comment]
the script was converted to library + camdeploy command in http://camlistore.org/r/4136 , and submitted as 99fe925efc81e805178d57b3a6fa0c59ec13bd14

Converted to new oauth2 in 22f45f14a5a9dc61fcb1425b8d415379483feb3c

Now closing this issue as all the required features have been addressed afaics, and I think the help messages are now good enough. We can open new specific issues if needed.
