### ISSUE TITLE
Make web-based GCE setup wizard

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#531]
<pre>From camlistore mailing list email:

     <a href="https://groups.google.com/forum/#">https://groups.google.com/forum/#</a>!searchin/camlistore/gce/camlistore/WHiR6WPBXVU/A7y4UXYxTh8J

For the 0.9 release, we want an easy web-based wizard for people to create their own
Camlistore installs on Google Cloud (compute engine + cloud storage)

We have most of this in misc/gce/create.go (<a href="https://camlistore.org/issue/530">issue #530</a> to make it easy to use as a CLI
tool), but we need to also web-ify this and put it on <a href="https://camlistore.org/">https://camlistore.org/</a> too.

This bug is about refactoring it into a CLI + library, and then building the web app
OAuth flow using the library.</pre>

**Comment by mpl** [comment]
Not wizard specific, but noting here now so I don't forget:
we should probably install djpeg when deploying on gce so we benefit from the faster rescales?

**Comment by bradfitz** [comment]
I guess so.

**Comment by mpl** [comment]
wizard went in as e3f16b8eada7fff48005d00594e419888a274fb7
Not closing yet as I'm going to add support for detecting already deployed instances soon.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4369

**Comment by mpl** [comment]
closing since issue #568 now mentions https://camlistore-review.googlesource.com/4369
