### ISSUE TITLE
blobpacked: pack blobs in big blobs

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#532]
<pre>This bug is about finishing blobpacked.

As background, I've been working on a new storage type called &quot;blobpacked&quot;,
which is described at:

<a href="https://github.com/bradfitz/camlistore/blob/master/pkg/blobserver/blobpacked/blobpacked.go">https://github.com/bradfitz/camlistore/blob/master/pkg/blobserver/blobpacked/blobpacked.go</a>

/*
Package blobpacked registers the &quot;blobpacked&quot; blobserver storage type,
storing blobs initially as one physical blob per logical blob, but then
rearranging little physical blobs into large contiguous blobs organized by
how they'll likely be accessed. An index tracks the mapping from logical to
physical blobs.

Example low-level config:

     &quot;/storage/&quot;: {
         &quot;handler&quot;: &quot;storage-blobpacked&quot;,
         &quot;handlerArgs&quot;: {
            &quot;smallBlobs&quot;: &quot;/small/&quot;,
            &quot;largeBlobs&quot;: &quot;/large/&quot;,
            &quot;metaIndex&quot;: {
               &quot;type&quot;: &quot;mysql&quot;,
                .....
            }
          }
     }

The resulting large blobs are valid zip files. Those blobs may up be up to
16 MB and contain the original contiguous file (or fractions of it), as well
as metadata about how the file is cut up. The zip file will have the
following structure:

    foo.jpg       (or whatever)
    camlistore/sha1-beb1df0b75952c7d277905ad14de71ef7ef90c44.json (some file ref)
    camlistore/sha1-a0ceb10b04403c9cc1d032e07a9071db5e711c9a.json (some bytes ref)
    camlistore/sha1-7b4d9c8529c27d592255c6dfb17188493db96ccc.json (another bytes ref)
    camlistore/camlistore-pack-manifest.json

The camlistore-pack-manifest.json is documented on the exported
Manifest type. It looks like this:

    {
      &quot;wholeRef&quot;: &quot;sha1-0e64816d731a56915e8bb4ae4d0ac7485c0b84da&quot;,
      &quot;wholeSize&quot;: 2962227200, // 2.8GB; so will require ~176-180 16MB chunks
      &quot;wholePartIndex&quot;: 17,    // 0-based
      &quot;dataBlobsOrigin&quot;: &quot;sha1-355705cf62a56669303d2561f29e0620a676c36e&quot;,
      &quot;dataBlobs&quot;: [
          {&quot;blob&quot;: &quot;sha1-f1d2d2f924e986ac86fdf7b36c94bcdf32beec15&quot;, &quot;offset&quot;: 0, &quot;size&quot;: 273048},
          {&quot;blob&quot;: &quot;sha1-e242ed3bffccdf271b7fbaf34ed72d089537b42f&quot;, &quot;offset&quot;: 273048, &quot;size&quot;: 112783},
          {&quot;blob&quot;: &quot;sha1-6eadeac2dade6347e87c0d24fd455feffa7069f0&quot;, &quot;offset&quot;: 385831, ...},
          {&quot;blob&quot;: &quot;sha1-beb1df0b75952c7d277905ad14de71ef7ef90c44&quot;, &quot;offset&quot;: ...},
          {&quot;blob&quot;: &quot;sha1-a0ceb10b04403c9cc1d032e07a9071db5e711c9a&quot;, &quot;offset&quot;: ...},
          {&quot;blob&quot;: &quot;sha1-7b4d9c8529c27d592255c6dfb17188493db96ccc&quot;, &quot;offset&quot;: ...}
      ],
    }

The manifest.json ensures that if the metadata index is lost, all the
data can be reconstructed from the raw zip files.

The 'wholeRef' property specifies which large file that this zip is building
up.  If the file is less than 15.5 MB or so (leaving room for the zip
overhead and manifest size), it will probably all be in one zip and the
first file in the zip will be the whole thing. Otherwise it'll be cut across
multiple zip files, each no larger than 16MB. In that case, each part of the
file will have a different 'wholePartIndex' number, starting at index
0. Each will have the same 'wholeSize'.
*/

The sub-tasks for finishing this bug are all listed in TODOs in the code &amp; tests,
but the real final task is for me to start using this for my production server, once I
totally trust it.</pre>

**Comment by nf** [comment]
So, are you using it in production yet?

**Comment by bradfitz** [comment]
Yes, at home. It will also be the default in the GCE configuration we recommend for new users (via the new launcher web app) in the 0.9 release.

**Comment by mpl** [comment]
Make blobpacked the default:
https://camlistore-review.googlesource.com/5248
