### ISSUE TITLE
Temporary GCE SPDY proxy

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#534]
<pre>The Camlistore web UI assumes the user has a low-latency connection or has a browser
with SPDY or HTTP/2 enabled. (we have lots of tiny js and css files, not merged
together, by choice)

Eventually we should have HTTP/2 support on the Go server (<a href="https://camlistore.org/issue/533">issue #533</a>) but in the
meantime we could run a SPDY proxy on the GCE instances to provide SPDY to clients
today.  Perhaps we just throw nginx in there.</pre>

**Comment by bradfitz** [comment]
Per email, we decided not to do SPDY at this point since HTTP/2 is deployed enough in clients, and the Go HTTP/2 support is working well.

Assigning to @mpl to delete SPDY stuff.

Thanks and sorry, @saljam!

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4356
