### ISSUE TITLE
GCE: hostname & cert support

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#535]
<pre>We need to make it easy to configure the https server's hostname &amp; SSL cert with the
GCE setup flow.

Right now the default experience is scary and insecure, going to
https://&lt;ip-address&gt; and having the user click through &quot;I know this isn't
secure&quot;.

We should also support making it easy for the user to add the self-signed cert's CA to
their trust list, so at least their browser supports it.  And then tell them in the web
UI (at /status/, perhaps), what config they need to add for the client.</pre>

**Comment by mpl** [comment]
I think all of the server-side is done, but nothing on the client-side apart from the GCE wizard instructing the user that they should check the certificate their browser uses matches the fingerprint we display.

**Comment by bradfitz** [comment]
The web wizard will not let them give camlistore.org their private key.

But I want them to be able to go to the Cloud Storage web UI browser at upload their *.crt and *.pem and have it detect that on start-up.

So it should probably scan their GCS config bucket (well, directory in their one bucket) and notice if they've added the crt+key PEM files.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4506

**Comment by mpl** [comment]
10a0689c1135628a79fd7b70fa9099a35b1d6598 makes sure we reuse existing cert&key
