### ISSUE TITLE
Server /status/ should show client-config

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#536]
<pre>From the server's /status/ or similar, the web UI should tell the user what
client-config.json to use on their local machine to hit that server.

This should include any self-signed SSL cert trust config.</pre>

**Comment by dotMR** [comment]
If I'm understanding correctly, wouldn't this need to live outside the web UI for it to be helpful (where you'd already have needed the cert information to access the web UI and find the Help menu)?

Or is this information only useful for CLI clients?

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4696

**Comment by mpl** [comment]
7b1903d5b1862e4bd2db0763123cac6c7c4367f4 adds help handler, client config generator.

Client tools downloads not yet done.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5230

**Comment by mpl** [comment]
077a74c78bcaa372a383dca3f85b4bf855b4b1a4
