### ISSUE TITLE
binary downloads for 0.9

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#538]
<pre>The 0.9 release should have binary downloads for all supported platforms for the CLI
tools &amp; camlistored.</pre>

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4716

Let me know if this is the kind of setup you were thinking of?
If yes, I'll do the other platforms too.
Probably add some make targets to push to gcs too?

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5006

**Comment by mpl** [comment]
988fc8a43cb6a279c491defff926758198de5d51

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5229

**Comment by mpl** [comment]
32228e451e859276a90d8b9a7fcff6a66d863972
