### ISSUE TITLE
ui: after creating a set, you can't see it

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#553]
<pre>If you create a set in the UI with &quot;Create set from items&quot;, there's no
feedback once it worked.

I would expect to redirect to that set, or see a link to it.

If you're lucky and you're looking at the default search and you're scrolled to the top,
then you see it appear. But if you're scrolled down or searching for something specific
from which you created the set, then nothing appears.</pre>

**Comment by mpl** [comment]
So, isn't this issue now fixed by the above CL?

**Comment by edrex** [comment]
Taking about the "after a big import" use case, it seems like redirect on set creation from selection is fine since the back button works. I guess the only question is whether the selection should be reset after set creation.

**Comment by dotMR** [comment]
> So, isn't this issue now fixed by the above CL?

Yes, unless there are other suggestions I'm considering it fixed.
