### ISSUE TITLE
Add generated resource files to the repository

### ISSUE THREAD

**Issue by saljam** [camlistore/camlistore#561]
Currently make.go generates the zembed_*.go resource files (templates/css/js/&c) in its temp build directory to embed them in the final binaries.

We can check them in the main repository to make "go get" work out of the box with all the resources built in, at the expense of a fatter repository.

We can even use go generate. I guess this is a low-priory issue.

**Comment by saljam** [comment]
Fair do's. Should I close this?

**Comment by mpl** [comment]
I think it's especially moot since afair one of the 0.9 release issues is about providing binaries to users. And I suppose devs weren't the ones you were concerned about for them having to cope with this generation.
