### ISSUE TITLE
mysql index fixed size 'value' column sometimes truncated

### ISSUE THREAD

**Issue by aboodman** [camlistore/camlistore#567]
The value can be any size:
https://github.com/camlistore/camlistore/blob/master/pkg/index/receive.go#L704

This can cause the server to panic at startup if the value is truncated such that there are less than the expected number of fields.

Not sure what happens if the final field (the camli signer) gets truncated ... perhaps that causes those mutations to not show up in search results.

**Comment by aboodman** [comment]
@mpl

**Comment by mpl** [comment]
related to issue #429

**Comment by aboodman** [comment]
No, it's the same bug as #429.
