### ISSUE TITLE
mysql is starting too slowly for camlistored on GCE

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#569]
I've regularly seen that on GCE:

-- Logs begin at Thu 2015-01-22 14:58:08 UTC, end at Thu 2015-01-22 15:06:18 UTC. --
Jan 22 14:59:39 camlistore-server.c.camli-mpl.internal systemd[1]: Starting Camlistore...
Jan 22 14:59:40 camlistore-server.c.camli-mpl.internal bash[772]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Jan 22 14:59:40 camlistore-server.c.camli-mpl.internal bash[772]: Dload  Upload   Total   Spent    Left  Speed
Jan 22 14:59:43 camlistore-server.c.camli-mpl.internal bash[772]: [392B blob data]
Jan 22 14:59:45 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:45 Moving pid 837 to /sys/fs/cgroup/blkio/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:45 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:45 Moving pid 837 to /sys/fs/cgroup/memory/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:45 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:45 Moving pid 837 to /sys/fs/cgroup/freezer/cgroup.procs
Jan 22 14:59:45 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:45 Moving pid 837 to /sys/fs/cgroup/devices/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:45 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:45 Moving pid 837 to /sys/fs/cgroup/cpu,cpuacct/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:45 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:45 Moving pid 837 to /sys/fs/cgroup/systemd/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:45 camlistore-server.c.camli-mpl.internal systemd[1]: camlistored.service: Supervising process 837 which is not our child. We'll most likely not notice when it exits.
Jan 22 14:59:45 camlistore-server.c.camli-mpl.internal systemd[1]: Started Camlistore.
Jan 22 14:59:46 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:46 Starting camlistored version 0.6; Go devel +1757b5c Thu Dec 11 07:31:32 2014 +0000 (linux/amd64)
Jan 22 14:59:47 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:47 Re-using identity with keyID "AC271F0F" found in file /gcs/camli-mpl-camlistore/config/identity-secring.gpg
Jan 22 14:59:48 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:48 TLS enabled, with SHA-256 certificate fingerprint: 65b9d04325e8917e9a6c
Jan 22 14:59:48 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:48 Starting to listen on https://localhost:443
Jan 22 14:59:50 camlistore-server.c.camli-mpl.internal systemd-docker[799]: 2015/01/22 14:59:50 Caught panic installer handlers: error instantiating storage for prefix "/index/", type "index": error from "mysql" KeyValue: error creating database 
camlistore_index: dial tcp 172.17.0.3:3306: connection refused
Jan 22 14:59:50 camlistore-server.c.camli-mpl.internal systemd-docker[799]: Error parsing config: Caught panic: error instantiating storage for prefix "/index/", type "index": error from "mysql" KeyValue: error creating database camlistore_index:
 dial tcp 172.17.0.3:3306: connection refused
Jan 22 14:59:51 camlistore-server.c.camli-mpl.internal systemd[1]: camlistored.service holdoff time over, scheduling restart.
Jan 22 14:59:51 camlistore-server.c.camli-mpl.internal systemd[1]: Stopping Camlistore...
Jan 22 14:59:51 camlistore-server.c.camli-mpl.internal systemd[1]: Starting Camlistore...
Jan 22 14:59:52 camlistore-server.c.camli-mpl.internal bash[1041]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Jan 22 14:59:52 camlistore-server.c.camli-mpl.internal bash[1041]: Dload  Upload   Total   Spent    Left  Speed
Jan 22 14:59:54 camlistore-server.c.camli-mpl.internal bash[1041]: [313B blob data]
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:55 Moving pid 1090 to /sys/fs/cgroup/devices/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:55 Moving pid 1090 to /sys/fs/cgroup/memory/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:55 Moving pid 1090 to /sys/fs/cgroup/cpu,cpuacct/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:55 Moving pid 1090 to /sys/fs/cgroup/systemd/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd[1]: camlistored.service: Supervising process 1090 which is not our child. We'll most likely not notice when it exits.
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd[1]: Started Camlistore.
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:55 Moving pid 1090 to /sys/fs/cgroup/blkio/system.slice/camlistored.service/cgroup.procs
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:55 Moving pid 1090 to /sys/fs/cgroup/freezer/cgroup.procs
Jan 22 14:59:55 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:55 Starting camlistored version 0.6; Go devel +1757b5c Thu Dec 11 07:31:32 2014 +0000 (linux/amd64)
Jan 22 14:59:56 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:56 Re-using identity with keyID "AC271F0F" found in file /gcs/camli-mpl-camlistore/config/identity-secring.gpg
Jan 22 14:59:58 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:58 TLS enabled, with SHA-256 certificate fingerprint: 65b9d04325e8917e9a6c
Jan 22 14:59:58 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:58 Starting to listen on https://localhost:443
Jan 22 14:59:59 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:59 [SyncHandler /bs/ -> /index/] Added 0 pending blobs from sync queue to pending list
Jan 22 14:59:59 camlistore-server.c.camli-mpl.internal systemd-docker[1053]: 2015/01/22 14:59:59 Slurping corpus to memory from index...

which seems to indicate that camlistored first tries to start while mysql is apparently not yet ready. It's no big deal since camlistored dies by itself and systemd restarts it automatically, hence the eventual success. But maybe we could add some sort of delay or test so that camlistored only starts when mysql is actually ready and we succeed at first try?

In this example we'd gain 12s on the boot process, which does not seem negligible imho.

thoughts?

**Comment by bradfitz** [comment]
Yes, we should address this. Two options, in order of preference:

1) systemd config. Tell it that MySQL is required before camlistored, and have it verify it's up first. Keep using TCP.
2) Use systemd socket activation: instead of connecting from Camlistore to MySQL via TCP to localhost:3306 or whatever, have systemd create a socket which when connected to, started up MySQL.  Then Camlistore just blocks until it's up.
3) (probably easiest, if you want to do this, even though ugly) Add configuration option to MySQL's sorted.KeyValue implementation to poll once a second on start-up, waiting for the TCP ip:port to reply.  Maybe wait 20 seconds.

**Comment by mpl** [comment]
I haven't seen the issue in a while anyway, but maybe that's all we actually needed:

https://camlistore-review.googlesource.com/4596

I'm trying to verify something in the log related that bothers me before closing that issue though.

**Comment by mpl** [comment]
376e53ccd55cdfe6798f75805d8a7a00709e369d

We'll see if that's good enough.
