### ISSUE TITLE
Error creating camlistore instance on Google Cloud

### ISSUE THREAD

**Issue by aboodman** [camlistore/camlistore#571]
An error occurred while creating your instance: "could not scan project for existing instances: could not get a list of zones: googleapi: Error 400: Invalid value 'Camlistore Instance'. Values must match the following regular expression: '(?:(?:[-a-z0-9]{1,63}\\.)*(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?):)?(?:[0-9]{1,19}|(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?))', invalidParameter". Please file an issue with your instance key (sha1-2287a135b76b9d4bb83405bdabe052bf2da58d77) at https://camlistore.org/issue

**Comment by mpl** [comment]
wow, thx.

**Comment by saljam** [comment]
I got this when I used the Project Name instead of Project ID. (The wizard
form says Project Name, but I think it actually means Project ID)

**Comment by mpl** [comment]
Did you fill yourself 'Camlistore Instance' in somewhere?

**Comment by mpl** [comment]
aha, thx @saljam

**Comment by aboodman** [comment]
Yeah that was the problem.

**Comment by mpl** [comment]
yeah, I'll fix the doc/label, and probably also start the creation process by testing that the project (id) exists somehow.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4429

**Comment by mpl** [comment]
0e31e41767666f17ab4bad33fec25c20837db3fd
