### ISSUE TITLE
investigate and go around the GCE firewall bug

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#572]
It seems like sometimes (with a brand new project?) the firewall (http(s)) rules we ask for when launching an instance on GCE with the deployer aren't created.

Enabling/Disabling them in the GCP UI once the project is created seems to fix the problem. Maybe we can do the same programmatically.

Or add the firewall rules post-creation with an API call instead of just relying on the &compute.Tags we pass in the instance at creation time.

**Comment by saljam** [comment]
I'll have a bash at this.

**Comment by mpl** [comment]
brilliant, thanks.

**Comment by dotMR** [comment]
+1
I experienced this issue as well when creating a new project. I had to remove/add the HTTP and HTTPS Traffic options before I could access.

**Comment by bradfitz** [comment]
What does cloud-config have to do with this at all?  That's a CoreOS thing inside of Linux.  The firewall is outside and unrelated.

Aside from that, I can't understand the different things said in this bug: is the problem that the default network is missing rules for handling the "http-server" and "https-server" tag?  Or that toggling the "http-server" / "https-server" tags in the web UI fixes the problem.  Or both?

Maybe the web UI recognizes this problem (of old/new projects having a different default network) and has its own workaround to create the firewall rules.

I suppose we could just query the default network's rules and create them if they're missing.

**Comment by mpl** [comment]
yeah I tend to say "cloud-config" when I just mean "all the parameters we have in instance := &compute.Instance{...}", my bad. I know it's actually the CoreOS thing. I edited it out of my first comment.

**Comment by saljam** [comment]
https://camlistore-review.googlesource.com/#/c/4437/

**Comment by mpl** [comment]
df8209ca7a6305a9ea9fde53868da18253a52b72
