### ISSUE TITLE
Add instruction to change user/pass on GCE

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#573]
Or make it easier in some other way?

@saljam suggests as fields to the creation form maybe?

**Comment by saljam** [comment]
Adding them as fields would enlarge the form a bit, but on the other hand the users don't need to go into the GCE control panel at all afterwards unless they are adding ssl certs.

**Comment by mpl** [comment]
I'm just a bit annoyed that it will be one more bit of critical info (we already have their IP, default SSL key and cert) that transits through us. But I agree it seems like a win overall. I'll have a CL for it soon.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4436

**Comment by adg** [comment]
What's the point of having usernames? Why not just make the username hard-coded to blank or some sane value?

**Comment by mpl** [comment]
We may be using that username as an attribute somewhere else, although I don't see why, since the gpg key id should be what really matters. I need to check to be sure.

**Comment by mpl** [comment]
Ok, afaics this username is only used for http auth, so we should be safe leaving it hard-coded. There's a bit of logic in pkg/serverinit/env.go that depends on the username not being blank, so I can't set it blank. I mean it would be easy to change, but maybe Brad had another intention behind this check that I don't know about.

I've set it to "camlistore", and removed it from the form. I'm not sure yet what's the best place to tell the user about it though.

**Comment by adg** [comment]
At least on the same page that says "Okay, your instance will be ready soon. Click this URL..."

**Comment by mpl** [comment]
yeah it is on the success page, within the paragraph about changing the password. But I'm afraid it's not very obvious. Maybe I should move it to right after the URL to the instance.

**Comment by adg** [comment]
Yeah, just a parenthetical after the URL would work.

**Comment by mpl** [comment]
yep done, I think it looks ok now, thanks.

**Comment by mpl** [comment]
83bb6bce78f5ef663dd1701def91f24dbb7dc5c2

not closing yet since there's a tiny bug left as a TODO.

**Comment by mpl** [comment]
the small password bug I was mentioning above is actually addressed too in https://camlistore-review.googlesource.com/4447

**Comment by mpl** [comment]
password bug fixed in e02ac6b36c05b3f102cda1c4da8fd823676ac930
