### ISSUE TITLE
'View Original' link on contextual nav no longer works

### ISSUE THREAD

**Issue by dotMR** [camlistore/camlistore#576]
Steps to reproduce:
- Select an image (only one) from the main search view
--> The contextual navigation appears

- Click the 'View Original' menu option
--> Attempts to open an illegal URL in another tab
example: http://hostname:port/ui/[object%20Object]

**Comment by dotMR** [comment]
https://camlistore-review.googlesource.com/#/c/4516

**Comment by mpl** [comment]
62e1a1f7f7309918239fa9ee8a29af3aff7b3667
