### ISSUE TITLE
Migrate fileinfo index rows to include wholeref

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#577]
See 8229c198507968 ... it adds a field to the "fileinfo" index key, but we need to fix up all old keys on start-up if people have the whole style.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4676

**Comment by mpl** [comment]
Do you want to do some sort of automatic fixing of an existing "broken" index, or is the above good enough to close that bug?

**Comment by bradfitz** [comment]
Yes, it'd be nice if camlistored had a mechanism to let us register upgrade hooks for upgrading from schema version N to N+1 (or hell: even just hard-coded, which is more practical), and then we could do this.

I think we should make users upgrading from 0.8 to 0.9 easy.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4736

**Comment by mpl** [comment]
0f9a56241a07f379d5b050ed54a41c2d4415fa09
