### ISSUE TITLE
search: some (UI) queries are broken because post-search sorts are not finished

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#579]
post-search sorts was started e0624177cd877c5290e42d0fc6874a8276358075 but not finished.

As a result, queries from the UI such as a {blobRefPrefix: targetBlobref} are broken because they always default to a "-created" sort (they probably shouldn't though) and they use an unsorted source (EnumerateCamliBlobsLocked). So they hit the "TODO: unsupported sort+query combination." error.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4626

**Comment by dotMR** [comment]
I just encountered this issue as well. On the 'Blob' aspect I was trying to click on a camliContent ref of a set-attribute claim. The current camliContent blobref link worked, but clicking on the previous version resulted in nothing on the screen, but errors in the browser javascript console.

- - - - -
(For example)
Mutation claims

{
  "claims": [
    {
      "blobref": "sha1-41f02c7bb1e866dc0e8527abc85ce8a9488fe492",
      "signer": "sha1-e692c7dc397e9afcaf79edee0d614ba6f786195f",
      "permanode": "sha1-dc1a26c26390ecc2b7cbe3f897aabd5dfbce68cf",
      "date": "2015-01-19T10:35:50Z",
      "type": "set-attribute",
      "attr": "camliContent",
      **"value": "sha1-cfcd4f9ee6721138eabe90911b6cc1da434a43d4" // BROKEN LINK**
    },
    {
      "blobref": "sha1-a9d977c14dd81e030f6cdee2f4b98e51398e37cc",
      "signer": "sha1-e692c7dc397e9afcaf79edee0d614ba6f786195f",
      "permanode": "sha1-dc1a26c26390ecc2b7cbe3f897aabd5dfbce68cf",
      "date": "2015-01-19T10:35:50Z",
      "type": "set-attribute",
      "attr": "camliContent",
      **"value": "sha1-06583da8a9ec65f7318d935a1e364b4bc5d379b8" // THIS LINK WORKED**
    }
  ]
}

**Comment by mpl** [comment]
3e79e732728cde3dbff3f36c36965151125221f6
