### ISSUE TITLE
Is it possible to share a file which has been split into parts by Camlistore as one single file?

### ISSUE THREAD

**Issue by erikano** [camlistore/camlistore#582]
Hello, I uploaded a PNG image to my install of Camlistore and it was split into multiple parts.

When sharing it, can it be retrieved in one part? If so, how?

Sorry if this question is out of place here in the issue tracker but I attempted asking about it on #camlistore on freenode first but nobody said anything for the hour I was there.

**Comment by parkr** [comment]
I havent used camlistore recently, but v0.6 allowed you to click a link and it rebuilt the file on-the-fly to download. So in v0.6, it was possible, yes!

**Comment by erikano** [comment]
Glad to hear that. Do you remember where the link was and what it was called?

**Comment by aboodman** [comment]
Add assemble=true to the share link.

**Comment by saljam** [comment]
That said, I think the [mailing list](https://groups.google.com/group/camlistore) is the best place for questions like this. The IRC channel can get rather quiet sometimes.

**Comment by erikano** [comment]
Thanks guys and yes, the mailing list would probably have been a better place for me to ask about it. I'll keep that in mind next time.
