### ISSUE TITLE
Enable (optionally?) google cloud logging when on GCE

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#587]
http://googlecloudplatform.blogspot.com/2015/02/gain-business-and-operational-insight-into-your-applications-using-Google-Cloud-Logging.html

**Comment by mpl** [comment]
related to #592

**Comment by mpl** [comment]
Iiuc, this is what we would need if we wanted to write application specific (camlistored) entries to GC Logging:
https://cloud.google.com/logging/docs/install/compute_install

And apparently CoreOS is not supported for now, so I think it's a no go for now.

Just for kicks I tried it on an instance though:

mathieu_lonjaret_gmail_com@camlistore-server ~ $ sudo bash google-fluentd-install.sh
==============================================================================
Starting installation of google-fluentd
==============================================================================
Unidentifiable or unsupported platform.

**Comment by bradfitz** [comment]
No, we wouldn't use the agent daemon.  No Python/Ruby server running in our Docker container.

We'd just use the Cloud Logging HTTP API and log directly from camlistored.

**Comment by mpl** [comment]
hmm ok. the docs lead me to believe the agent was somehow still needed since it was in "Getting started".

**Comment by mpl** [comment]
ok, it was as tedious as usual with the google apis, but I've managed to write a log entry and it shows up in the logs I can see from the devolopers console, so it's probably good enough for us.
More news when I get the whole thing working for https://camlistore-review.googlesource.com/#/c/4887/

**Comment by mpl** [comment]
Done, but it's not optional. We'll reopen if it needs to be.
