### ISSUE TITLE
pre-commit shouldn't take 18 seconds and run find a bunch

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#591]
The third_party import checker should only check the files in the git index.  (that is, only if the file is about to be committed, or even sitting on disk unknown to git).  But files known to git and unmodified should not be open and slurped and grepped for github/code.google.com imports.

Related & a dependency: #590

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5297

**Comment by mpl** [comment]
6fa15a228e50935fb91521d0ea967a6a919b580c
9a24acca6cea06a56be595d903c89a2d683a0380
