### ISSUE TITLE
link to GCE logs (stderr logs) from /status/

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#592]
If running under GCE, link to the logs (at /logs/ ?) from /status/.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/4886

**Comment by mpl** [comment]
I got it all working here

https://github.com/mpl/camlistore/commit/0f1770d13f1030465e76b1beca64a424a6b5d38c

Could not push it to gerrit yet as I merged my other commits to help me with the work. So I need to recut it all.

**Comment by mpl** [comment]
@bradfitz PTAL @ https://camlistore-review.googlesource.com/4887

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5524 merged as 8a10bb52e0e7a7aa9ccc19406f98046aa11fb467
