### ISSUE TITLE
sorted: make a very strict mem implementation for testing

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#600]
so we don't get bitten by sqlite weird locks and gotchas

**Comment by tgulacsi** [comment]
What's the matter with pkg/sorted/mem.go ?

**Comment by tgulacsi** [comment]
I've issued https://camlistore-review.googlesource.com/5597 for removing the last remnants of code.google.com/p/leveldb-go - from pkg/sorted/mem.go.

**Comment by mpl** [comment]
I don't remember for sure what that issue was about exactly. I'll need to think about it.

**Comment by mpl** [comment]
a2c19c1f425c9266dc0ba23dd2c5c672d577e8da makes pkg/sorted/mem.go use syndtr/goleveldb.

I don't remember what the specific emphasis on strict and testing should have been about, so closing it for now.
