### ISSUE TITLE
ui: how to download a non-image?

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#603]
Upload a PDF or some non-image file with a permanode. (e.g. drag-and-drop it onto the UI)

Now, how do I download it?  The UI doesn't seem to let me.

/cc @aboodman @mpl

**Comment by mpl** [comment]
@bradfitz select the item (with the "v" checkmark), click on "view original" in context bar (on right).

**Comment by dotMR** [comment]
@mpl 's suggestion should work. If you find a case where it doesn't work let me know and I'll take a look.
