### ISSUE TITLE
ui: currently selected items are no longer being retained across browser navigation

### ISSUE THREAD

**Issue by dotMR** [camlistore/camlistore#609]
@aboodman introduced a feature to retain the current selected items that doesn't seem to be working right now.

Use case:
- Select 3 items
- Click on a fourth item to make sure it's the one you want
- Click the back button
- Note the previously selected items are no longer selected

Maybe it was lost with the addition of the 'around' query?

**Comment by dotMR** [comment]
Note for future debugging:
functionality introduced here: 3683a15e05a0b4f658fb9b7ac349ed6353b256a7

**Comment by dotMR** [comment]
Looks like it was broken here:
https://github.com/camlistore/camlistore/commit/b19e836c7bf5d8f5489f507e6a0502931593818b#diff-895405ce6e0f79e2b7b0b0884cb0b913R368

    this.setSelection_({});

**Comment by dotMR** [comment]
https://camlistore-review.googlesource.com/#/c/5076/

**Comment by mpl** [comment]
ACK. I'll check it all out later if @aboodman does not get to it. He did warn us that he wanted to test the left/right navigation change more, but we were in a hurry to merge it at the time.

**Comment by mpl** [comment]
38f16f6e316e63adac9383b208feb319ad2560e1
