### ISSUE TITLE
Off-by-one error in Bits in rollsum.go

### ISSUE THREAD

**Issue by aidanhs** [camlistore/camlistore#611]
Currently:

```
func (rs *RollSum) Bits() int {
    bits := blobBits
    rsum := rs.Digest()
    rsum >>= blobBits
    for ; (rsum>>1)&1 != 0; bits++ {
        rsum >>= 1
    }
    return bits
}
```

All values > 13 are 1 less than they should be.
Noticed when working on https://github.com/aidanhs/rollsum-tests.git

**Comment by aidanhs** [comment]
Actually, I may have raised this over-eagerly. Can't quite see how this would return different results.
Will look at my tests.

**Comment by aidanhs** [comment]
Looks like the digest diverges after about 4 bytes.

**Comment by bradfitz** [comment]
Feel free to re-open when there's a concrete bug report. This was a port of https://github.com/bup/bup 's code.

**Comment by aidanhs** [comment]
@bradfitz found the problem
```
func (rs *RollSum) add(drop, add uint8) {
	rs.s1 += uint32(add) - uint32(drop)
	rs.s2 += rs.s1 - uint32(windowSize)*uint32(drop+charOffset)
}
```

`drop` is a uint8, `charOffset` is 31.
Consider the case where `drop` is 252 - `drop+charOffset` will overflow. I guess the fix is to convert drop before adding (or reorder the addition? You would know better than me).

**Comment by aidanhs** [comment]
I think there are other problems with `rs.s1 += uint32(add) - uint32(drop)` (wrapps around instead of going negative).

I found that the following diff made camlistore rollsum pass my tests:
```
$ diff -u src/github.com/camlistore/camlistore/pkg/rollsum/rollsum.go rollsum.go
--- src/github.com/camlistore/camlistore/pkg/rollsum/rollsum.go 2015-05-06 20:16:26.220885271 +0100
+++ rollsum.go  2015-05-06 20:20:12.114248770 +0100
@@ -43,8 +43,10 @@
 }
 
 func (rs *RollSum) add(drop, add uint8) {
-       rs.s1 += uint32(add) - uint32(drop)
-       rs.s2 += rs.s1 - uint32(windowSize)*uint32(drop+charOffset)
+       rs.s1 += uint32(add)
+       rs.s1 -= uint32(drop)
+       rs.s2 += rs.s1
+       rs.s2 -= uint32(windowSize)*uint32(uint32(drop)+charOffset)
 }
 
 func (rs *RollSum) Roll(ch byte) {
```

**Comment by bradfitz** [comment]
You also need to address Camlistore's tests. Any change needs test changes too.

**Comment by kothar** [comment]
I seem to have applied the same patch in #628 - A test for rollsum divergence is included.

**Comment by mpl** [comment]
@kothar If you want to propose a patch for inclusion, we use gerrit, not github PRs.
See http://camlistore.org/code#contributing

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5176

@kothar I'll review it soon
@aidanhs Please feel free to review that CL too

**Comment by mpl** [comment]
@aidanhs I agree about the drop + charOffset bug, and hence with @kothar's CL, but I don't understand your concern about the add - drop part, e.g.:

http://play.golang.org/p/Po1JTitZID

gives you 998, the same as

  r->s1 += add - drop;

would give you (from rollsum_add in https://github.com/bup/bup/blob/master/lib/bup/bupsplit.c).

Can you please give me an example of the problem you're thinking of?

**Comment by mpl** [comment]
@kothar pinging you here in case you're not monitoring the CL.

**Comment by mpl** [comment]
As per chat with Brad, we'll postpone that change to after 0.9. In the unlikely event that this bug does not actually pose any problem (as @saljam said, so far the splitting worked for us), and that we don't have to fix it. Which will require some comparison, benchmarking, etc...

**Comment by aidanhs** [comment]
@mpl I've run the proposed patch against the tests that prompted me to raise this issue and it looks good to me. I don't know what I was thinking with the `add - drop` part.
