### ISSUE TITLE
panic: slice bounds out of range when decoding exif

### ISSUE THREAD

**Issue by hullerob** [camlistore/camlistore#612]
camputting file leads to camlistored crash

file causing crash:
https://github.com/odeke-em/drive/blob/7dbd8bf4629805fc257be30bc932be0aaa9efea1/icons/application-vnd.google-apps.spreadsheet.xcf 

panic is here:
https://github.com/camlistore/camlistore/blob/master/third_party/github.com/rwcarlsen/goexif/exif/exif.go#L576

app.data has length 1, but is sliced with [2:]

this is still present in 89488a3cf4a326b56015885973467cae17982b7e

**Comment by mpl** [comment]
I can reproduce, thanks. I'll look into it.

**Comment by mpl** [comment]
Fix proposed upstream, thanks.

https://github.com/rwcarlsen/goexif/pull/35

**Comment by mpl** [comment]
upstream fix merged. But I'm waiting a bit to see if another of our patches (https://github.com/rwcarlsen/goexif/pull/33) lands soon before updating our third_party.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5046
3a2ea94c13ac7cbfc3c365b85f9f77ae6fe790a3
