### ISSUE TITLE
UI: /ui/blobRef style URL does not load

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#614]
Let sha1-foobar be a valid blobRef for a permanode.

Try opening http://host:port/ui/sha1-foobar in a new tab.

Note that entering ref:sha1-foobar in the search bar of an already loaded UI will work.

I believe this is because we end up with a broken search session, because we gave it an empty query.

I'm not even sure making /ui/blobRef load the correct page used to work for all kinds of blobs, as it seems like a complicated issue (since you first have to determine what kind of blob you're dealing with), but I think at one point it worked at least for permanodes, did it not?

**Comment by mpl** [comment]
So far I've tried:

in getSearchSession_:

adding 

		if (!opt_query && opt_targetBlobref) {
			opt_query = this.buildQuery_(' ', opt_targetBlobref);
			queryString = JSON.stringify(opt_query);
		}

right before:

		console.log('Creating new search session for query %s', queryString);

but it didn't help.

or this hack in updateTargetSearchSession_:

			var query = this.buildQuery_(newURL.getParameterValue('q') || ' ', newURL.getParameterValue('p'));

which seemed to fix the described symptom but which broke search session loading for other cases.

**Comment by mpl** [comment]
I don't really know what I'm doing, but this seems to fix the issues, and I haven't noticed any breaking side-effect.

https://camlistore-review.googlesource.com/5016

**Comment by dotMR** [comment]
Agreed that something is broken. I can take a look at your CL in the morning.

Interesting note, the existing code works as expected if you provide some value for a query '?q=%20'  *http://host:port/ui/sha1-foobar?q=%20*

**Comment by mpl** [comment]
yes, because part of the breakage is the server always expecting a query, while I think we used to be more lenient about it. Hence the hacks I was mentioning in:

https://github.com/camlistore/camlistore/issues/614#issuecomment-102532829

**Comment by aboodman** [comment]
It worked for all blob types. That was why I changed the URL format to just /ui/<ref> not ?p=<ref>. I'm looking at this now, but on first glance this seems to be working. At least with data from -makethings.

**Comment by aboodman** [comment]
scratch that last comment, it's busted. looking...

**Comment by dotMR** [comment]
Neat! I didn't know about the 'makethings' flag.

@aboodman Out of curiosity, what was busted?

**Comment by mpl** [comment]
93727cbff0e8a1d0ec75440f0b7845e66a53194f
