### ISSUE TITLE
camput/camget: default to port 443 when the server url scheme is https://

### ISSUE THREAD

**Issue by saljam** [camlistore/camlistore#616]
When the port is missing from the server URL but the prefix is https, camput correctly tries to establish a TLS connection, but over port 80. It should be 443.

To reproduce, run a server with TLS enabled over port 443:

    $ echo test | camput --server https://example.com:443 blob -   # works
    sha1-4e1243bd22c66e76c2ba9eddc1f91394e57f9f83
    $ echo test | camput --server https://example.com blob -       # fails
    2015/05/18 09:06:38 WARNING: not using local server inventory cache; failed to retrieve server's storage generation: Get http://example.com: dial tcp <nil>-> 203.0.113.2:80: getsockopt: connection refused
    Error putting blob: Get http://example.com: dial tcp <nil>->203.0.113.2:80: getsockopt: connection refused

Substitute example.com & 203.0.113.2 for the server's hostname & IP address.

This is easy enough to work around in the config file. However, the Android client strips off default ports making it impossible to use with an https server on port 443. Or at least I couldn't figure out how to do it.

(I'll look into this issue. I couldn't figure out how to assign it to myself.)

**Comment by mpl** [comment]
I have not (yet) looked into the root of the problem you're reporting, but my Camlistore server is on https (granted, not on 443 though, but neither on 80) and I have no problem using the android client with it.

**Comment by mpl** [comment]
ah ok, you're saying the android client strips off _default_ ports, so 80 and 443, but probably not the (different) one I use?

**Comment by saljam** [comment]
Yep, that's correct. The android client only strips port 80 when the url starts with http and 443 when with https.

**Comment by mpl** [comment]
@saljam Are you interested in looking into it?

**Comment by saljam** [comment]
Yes, I'll look into it. :-) Just thought I'd file it in case I got distracted before I submit anything.

    (I'll look into this issue. I couldn't figure out how to assign it to myself.)

**Comment by saljam** [comment]
OK I found the culprit and here's a quick hack to get around it: https://camlistore-review.googlesource.com/5026

**Comment by mpl** [comment]
hmm it appears I can't assign you either. the list of possible assignees is pretty limited, looks like it corresponds to ppl with submit rights.

**Comment by mpl** [comment]
426496ab8d321d90794f4d854110b4e347b47b95
