### ISSUE TITLE
ui: drag & drop file upload is not working

### ISSUE THREAD

**Issue by dotMR** [camlistore/camlistore#619]
Currently on the tip file upload is not working. It looks like the duplicate check is failing. I can add another check in the JavaScript, but we should understand what caused the change in behavior.

For example:
[http://localhost:3179/my-search/camli/search/files?wholedigest=sha1-xxx](http://localhost:3179/my-search/camli/search/files?wholedigest=sha1-327d3758caf3d571e4fa74c5a5dd425d282f3454)

The search handler used to respond with:

    {
        "files": []
    }

but now only responds with:

    {}

**Comment by dotMR** [comment]
FYI: @mpl

**Comment by dotMR** [comment]
So it looks like it happened here: d94796d4ef768a99e87960bff47e8fc2feb0d7af

I'm assuming the 'files' object is no longer being returned if empty.

**Comment by mpl** [comment]
yeah, I was about to tell you that I knew where to look for the problem. Feel free to fix or I'll do it later today.

**Comment by mpl** [comment]
and thanks for the report!
There might be other cases like that with the map->struct changes that I missed.

**Comment by dotMR** [comment]
Ok, I can make the change today.

In general, should we no longer rely on empty objects being returned from the server? I'd have to look closer, but it may affect other cases as well

**Comment by mpl** [comment]
No, the server should keep answering the same thing regardless of what internal changes  we make, so the client (web UI) can keep on expecting whatever it was receiving before. I caught one or two cases during review where such breaking changes were made but I may have missed some other. I need to re-review that particular aspect probably.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5067

**Comment by mpl** [comment]
01cddcc8d557d14fb3cba5de28871d4dbfefc26b
