### ISSUE TITLE
ui: duplicate permanodes created when uploading same item multiple times

### ISSUE THREAD

**Issue by dotMR** [camlistore/camlistore#622]
Steps to reproduce

    devcam server --wipe

- Upload an item to camlistore via drag/drop on UI
- Repeat 'n' times

Note the same item appears 'n+1' times

Potential duplicate: #112

**Comment by mpl** [comment]
I can't believe we still had that bug.

Fix at: https://camlistore-review.googlesource.com/5226

On a related note, I didn't think I could hate javascript more than I already did. I had never been so wrong.

**Comment by mpl** [comment]
@dotMR could you have a look at the above CL please ?

**Comment by mpl** [comment]
82c6feb61a101b8f6bdaf17523ecf1d30d94cadd

**Comment by dotMR** [comment]
@mpl after the above patch there is one case I've found which feels like a bug from the user perspective:

Steps to reproduce

    devcam server --wipe

- Upload an item
- Create a set (you are automatically redirected to the new set)
- Attempt to upload the same item

Note: nothing appears in the set

In this case it should probably still make the permanode association for the existing item rather than just drop the rest of the promise chain :)

**Comment by mpl** [comment]
@dotMR good point. I'm on it.

**Comment by mpl** [comment]
@dotMR https://camlistore-review.googlesource.com/5345 seems to be working, but I'm not sure it scales with "large" sets. See TODO for discussion please.
