### ISSUE TITLE
ui: FiletreePage links are broken

### ISSUE THREAD

**Issue by dotMR** [camlistore/camlistore#629]
Steps to Reproduce

    devcam server
    camput file -permanode <somedir>

Load the UI and click on the permanode for the directory provided. Note that clicking on any of the links throws an error:

    Uncaught TypeError: this.dispatchImpl_ is not a function

**Comment by dotMR** [comment]
Future debugging notes:

Maybe 'this' isn't being set correctly when calling cam.Navigator.navigate()
@see cache_buster_iframe.js ~Line86

**Comment by mpl** [comment]
Shall I leave you that one to investigate?

**Comment by dotMR** [comment]
Sure, I can take a look

**Comment by dotMR** [comment]
https://camlistore-review.googlesource.com/#/c/5186

**Comment by mpl** [comment]
5ad8e3a3cbd568c0c05c4484a952801b813cfe59
