### ISSUE TITLE
changing feed importer attributes hangs camlistored

### ISSUE THREAD

**Issue by ajft** [camlistore/camlistore#630]
Changing an attribute of the importer feed "Account metadata permanode" blob (eg importAuto from 30m to 180m) and saving, results in camlistored printing:

2015/07/02 18:01:15 Received blob [sha1-ef7173ffac916f50387de5d120d45f5cfcb74690; 689 bytes]

and no longer responding to web requests. (killed it after five minutes of no web response, no obvious activity).   Investigation shows that the claim blob sha1-ef...90.dat was successfully created.

On restart importer appears to be functioning correctly with updated values.

**Comment by edrex** [comment]
I can't reproduce. @ajft if this is working for you can you close?

**Comment by mpl** [comment]
actually, now that I think about it, that might have been the same as issue #709 
in which case it would indeed now be fixed.

**Comment by ajft** [comment]
Nope, I can't reproduce it with current (2016-05-06) versions.
