### ISSUE TITLE
camlistored crash in png decoder

### ISSUE THREAD

**Issue by ajft** [camlistore/camlistore#631]
Crash dump is at https://gist.github.com/ajft/cf152222d776d0f406a4

panic: runtime error: index out of range
 
goroutine 20980 [running]:
image/png.(*decoder).readImagePass(0xc251093180, 0x7fdc21188758, 0xc2514a0410, 0x1, 0xc2514a0400, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/image/png/reader.go:447 +0x1d9e
image/png.(*decoder).decode(0xc251093180, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/image/png/reader.go:328 +0x5de

The png file (or files) that caused it came in from the picasa importer, from my "Automatic Uploads" folder created from phone photos uploaded to google photos -- I'm not sure how the PNGs got included, they seem to be graphics and buttons for apps.

I've isolated at least one specific PNG image that causes this.

**Comment by ajft** [comment]
Example problem file

![radio-title_bottom_bg](https://cloud.githubusercontent.com/assets/597768/8498231/b8dd6142-21c7-11e5-91e1-f07b4bc5f474.png)
sha1 3063284a2cdaa71a5b91a6ce493dc0dd93644c51  radio-title_bottom_bg.png

**Comment by bradfitz** [comment]
What version of Go?

**Comment by ajft** [comment]
It's a ubuntu 15.04 system (which seems to have 1.3.3 in /usr/bin/go, but
I've got 1.4.2 in /usr/local/go/bin.  I'm fairly certain that I've been
building with 1.4.2.

$ /usr/local/go/bin/go version
go version go1.4.2 linux/amd64

Confirmed -- I've still got the entire log from the instance that the gist
was pasted from, initial line is "Starting camlistored version unknown; Go
go1.4.2 (linux/amd64)"

Just rebuilt the binary with 1.4.2 while writing this, (make clean, rm -rf
tmp; make) and I get the same panic in the png.

  Adrian


On Mon, Jul 6, 2015 at 10:48 AM, Brad Fitzpatrick <notifications@github.com>
wrote:

> What version of Go?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camlistore/camlistore/issues/631#issuecomment-118683222>
> .
>



-- 
Adrian Tritschler
Melbourne, Australia

**Comment by bradfitz** [comment]
Filed upstream https://github.com/golang/go/issues/11604 

Hopefully we'll get it fixed in Go 1.5, which Camlistore will then require in about a month.

**Comment by ajft** [comment]
Thanks, I'll treat it like the medusa until then... step carefully around
2015-04-08 and not look at the png's

On Mon, Jul 6, 2015 at 11:24 AM, Brad Fitzpatrick <notifications@github.com>
wrote:

> Filed upstream golang/go#11604 <https://github.com/golang/go/issues/11604>
>
> Hopefully we'll get it fixed in Go 1.5, which Camlistore will then require
> in about a month.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/camlistore/camlistore/issues/631#issuecomment-118686327>
> .
>



-- 
Adrian Tritschler
Melbourne, Australia

**Comment by ajft** [comment]
I've rebuilt camlistored with the newly released go1.5 (linux x64) and no longer experience this crash on my problem image.

(there are still visual uglinesses with camlistore PNG layout, scaling, overlapping images, transparent images etc, but that's probably a lower priority and separate issue).

**Comment by bradfitz** [comment]
Good to hear, thanks!
Will close this, then.

**Comment by bradfitz** [comment]
(since we now depend on Go 1.5 anyway)
