### ISSUE TITLE
index: switch default to syndtr/goleveldb

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#632]
The current default for camlistored is to use cznic/kv as the index storage. Some problems with kv have been observed.
I'm considering changing the default to syndtr/goleveldb. It is already the case for devcam server.

The code changes are trivial. The reason for this issue is to discuss the pros and cons of such changes, especially since syndtr/goleveldb does not seem to have been used much with Camlistore.

**Comment by cliveb** [comment]
Leveldb implementation over cznic/kv allows for easier scaling with Riak or another system supporting Leveldb for scaling. (Recent camli forum posts are folks struggling to load or index bulk data or large files).

**Comment by benschumacher** [comment]
What about BoltDB? Naive go k/v-style database.

**Comment by tgulacsi** [comment]
@cliveb I don't know, but do the different implementations of LevelDB (C, Go) has the same on-disk format, are they compatible?

@benschumacher BoltDB: see https://camlistore-review.googlesource.com/#/q/I7f7c342b6a82b0f1290d5cdcac99dbc6b249405e
Also it has a 2Gb total size limit on i386 systems (https://github.com/boltdb/bolt/issues/277).
And LevelDB is better on spinning disks.

**Comment by cliveb** [comment]
I'd assumed LevelDB (C, Go) ports have the same .sst format. Actually I don't know that the different implementations are on-disk compatible. 

Riak forked Google's leveldb (doesn't sound like compatible): "Those wishing to truly savor the benefits of Basho's modifications need to initialize a new leveldb".  
 
http://docs.basho.com/riak/1.3.2/tutorials/choosing-a-backend/
http://docs.basho.com/riak/latest/ops/advanced/backends/leveldb/
https://github.com/basho/leveldb

On leveldb usage in addition to Chromes IndexedDB and one of Riak's options. Bitcoin Core stores the blockchain metadata using a LevelDB database. Minecraft: Pocket Edition uses a modified version for chunk and entity data storage. Autodesk AutoCAD 2016 also uses LevelDB.
https://en.wikipedia.org/wiki/LevelDB#Usage

**Comment by mpl** [comment]
Related: https://camlistore-review.googlesource.com/5316

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5486 allowed me to get some interesting results.
with:

  % du -sch pkg/index/stress/testdata/
  2.0G	pkg/index/stress/testdata/
  2.0G	total
  % ll pkg/index/stress/testdata/* | wc -l
  434

I'm getting numbers such as:

--- BENCH: BenchmarkPopulateLevelDB-4
ok  	camlistore.org/pkg/index/stress	137.477s

--- BENCH: BenchmarkPopulateCznic-4
ok  	camlistore.org/pkg/index/stress	143.122s

--- BENCH: BenchmarkPopulateSQLite-4
ok  	camlistore.org/pkg/index/stress	302.163s

--- BENCH: BenchmarkReindexLevelDB-4
ok  	camlistore.org/pkg/index/stress	20.824s

--- BENCH: BenchmarkReindexCznic-4
ok  	camlistore.org/pkg/index/stress	87.140s

--- BENCH: BenchmarkReindexSQLite-4
ok  	camlistore.org/pkg/index/stress	225.478s !!

--- BENCH: BenchmarkEnumerateBlobMetaLevelDB-4
2000000000	         0.05 ns/op
	index_test.go:174: Enumerated 33845 meta blobs
ok  	camlistore.org/pkg/index/stress	1.000s

--- BENCH: BenchmarkEnumerateBlobMetaCznic-4
2000000000	         0.12 ns/op
ok  	camlistore.org/pkg/index/stress	2.981s

--- BENCH: BenchmarkEnumerateBlobMetaSQLite-4
2000000000	         0.10 ns/op
ok  	camlistore.org/pkg/index/stress	2.374s

--- BENCH: BenchmarkAllLevelDB-4
ok  	camlistore.org/pkg/index/stress	156.183s

--- BENCH: BenchmarkAllCznic-4
ok  	camlistore.org/pkg/index/stress	232.468s

--- BENCH: BenchmarkAllSQLite-4
ok  	camlistore.org/pkg/index/stress	548.367s

**Comment by mpl** [comment]
Hence, https://camlistore-review.googlesource.com/5496

**Comment by mpl** [comment]
And also, https://camlistore-review.googlesource.com/5497

**Comment by mpl** [comment]
69fdcbb7971937f9e8372add75ed4fe95d50d34d
