### ISSUE TITLE
dependency on google.golang.org/cloud/compute/metadata not quite right?

### ISSUE THREAD

**Issue by epaulson** [camlistore/camlistore#636]
On a reasonably fresh Mac OS X install (never built camlistore on this machine before) and using a fresh checkout of camlistore:

```
epaulson:~/development/camlistore/src/camlistore.org $ git log -1
commit b118fc23fb0d0c53868f7dcfe42be5f8c323f878
Author: mpl <mathieu.lonjaret@gmail.com>
Date:   Fri Aug 21 19:52:10 2015 +0200
```

with go version 1.5
```
epaulson:~/development/camlistore/src/camlistore.org $ go version
go version go1.5 darwin/amd64
```
and camlistore checked out in my GOPATH:

```
epaulson:~/development/camlistore/src/camlistore.org $ echo $GOPATH
/Users/epaulson/development/camlistore
```
building devcam fails:

```
epaulson:~/development/camlistore/src/camlistore.org $ go install ./dev/devcam
pkg/env/env.go:24:2: cannot find package "google.golang.org/cloud/compute/metadata" in any of:
	/usr/local/go/src/google.golang.org/cloud/compute/metadata (from $GOROOT)
	/Users/epaulson/development/camlistore/src/google.golang.org/cloud/compute/metadata (from $GOPATH)
```

This wasn't a hard fix:

```
epaulson:~/development/camlistore $ go get google.golang.org/cloud/compute/metadata
epaulson:~/development/camlistore/src/camlistore.org $ ls $GOPATH/bin
devcam		godef		golint
gocode		goimports	oracle
```

I'm not enough of a golang person to know if something just got missed to set the dependency for the GCE metadata stuff, or if going the ```go install devcam``` route rather than ```go run make.go``` means that sometimes I have add some packages by hand and the HACKING file is just missing a step with the new updates.

**Comment by bradfitz** [comment]
We require GO15VENDOREXPERIMENT=1

**Comment by pmezard** [comment]
https://camlistore-review.googlesource.com/#/c/5341/ to clarify this and the Go 1.5 requirement.

**Comment by mpl** [comment]
b118fc23fb0d0c53868f7dcfe42be5f8c323f878
