### ISSUE TITLE
Camlistore launcher failed...

### ISSUE THREAD

**Issue by benschumacher** [camlistore/camlistore#640]
It seems like the source image is invalid. Here's what I got as an error:

> An error occurred while creating your instance: "could not create compute instance: failed to create instance: googleapi: Error 400: Invalid value for field 'resource.disk.initializeParams.sourceImage': 'https://www.googleapis.com/compute/v1/projects/coreos-cloud/global/images/coreos-stable-444-5-0-v20141016'. Referenced resource was not found., invalid. Please file an issue with your instance key (sha1-fe87910d0efd04f8c64c9f92a6064d480ac989ae) at https://camlistore.org/issue".

Thanks.

**Comment by mpl** [comment]
yes, the code has already been updated (https://camlistore-review.googlesource.com/#/c/5342/), but the launcher "in production" is still running the old code, sorry about that.

**Comment by mpl** [comment]
@benschumacher the launcher has been updated, and it should be easy to keep it updated from now on. Please retry.
