### ISSUE TITLE
deploy/gce: systemd-docker broken

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#646]
we're getting this error for the mysql service:

Oct 16 22:08:41 camlistore-server.c.camli-mpl.internal docker[670]: Status: Downloaded newer image for ibuildthecloud/systemd-docker:latest
Oct 16 22:08:41 camlistore-server.c.camli-mpl.internal docker[670]: Installing systemd-docker to /opt/bin
Oct 16 22:08:41 camlistore-server.c.camli-mpl.internal systemd-docker[871]: 2015/10/16 22:08:41 API error (400): client is too old, minimum supported API version is 1.12, please upgrade 
Oct 16 22:08:41 camlistore-server.c.camli-mpl.internal systemd[1]: mysql.service: Main process exited, code=exited, status=1/FAILURE
Oct 16 22:08:41 camlistore-server.c.camli-mpl.internal systemd[1]: Failed to start MySQL.

I believe it's this issue:
https://github.com/ibuildthecloud/systemd-docker/issues/33

**Comment by mpl** [comment]
@bradfitz I'll look into a fix, but pinging you in case you've hit that issue already elsewhere and you've got a work-around ready.

**Comment by cliveb** [comment]
@mpl Looking forward to dropping docker now that with Go 1.5 has native
cross-compile support for Android Camlistore app (I plan to finally start
hacking on 1.5)

**Comment by saljam** [comment]
@cliveb this is for running camlistored on Google Cloud Engine, not the mobile app. I think Docker is quite useful for this still.

@mpl I ran into this (for a different project) recently when I rebooted CoreOS and its Docker got upgraded, it's definitely that issue. I just used the normal docker command rather than the systemd-docker, but that's not really perfect.

How about vendoring the systemd-docker Dockerfile and fixing it to have the right version?

**Comment by mpl** [comment]
@cliveb this issue isn't the place to discuss this, but:

1) what @saljam said

2) as I already explained, you don't need docker to build the android app (look at the install target in the Makefile) today. I usually don't. We only use docker to get isolation and clean/reproducible builds.

3) I wouldn't get my hopes high about gomobile helping us. it's mainly a big win when you're writing games and/or using openGL. In our case, we're still going to need a lot, if not mostly, of java code. I already would have started ported the app in Go otherwise (https://groups.google.com/d/msg/golang-nuts/j-GpFcTK7Ao/4NkqFtnZBrsJ). You're welcome to try and report about it though :-)

**Comment by mpl** [comment]
@saljam And so we would host our own somewhere, and instead of:

  /usr/bin/docker run --rm -v /opt/bin:/opt/bin ibuildthecloud/systemd-docker

we would:

  /usr/bin/docker run --rm -v /opt/bin:/opt/bin ourcamlistorehuborwherever/systemd-docker

for all our ExecStartPre statements ?

**Comment by saljam** [comment]
@mpl yeah, that's what I was suggesting. Or save the image to a tarball on Cloud Storage like we do with camlistored. I can send a CL for this this weekend.

**Comment by mpl** [comment]
@saljam ah yes, a tarball of the docker image works too. For practical reasons it is actually better (because I do have access to the public camli storage, while I don't think I have it for our "official" imagehub).
As it is a one time thing, I think you should probably make it a separate program from dock.go.
thanks.

**Comment by mpl** [comment]
@saljam Are you already working on a CL for that ? I'm going to work around it by curling a binary for now, but as this issue is blocking for any GCE deploying stuff, I'd like to fix it asap. So let me know if I should work on it myself please.

**Comment by saljam** [comment]
yep, working on it right now :)

**Comment by mpl** [comment]
funny thing happened here. the docker saved systemd-docker.tar.gz is 233MB on my localhost (which makes it pretty inconvenient to upgload to GCloud). and I've just rebuilt it from within google cloud shell, where it is only ~3MB.
Maybe I need to do some cleanup in my docker images...

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5458
c90ae0219ccbf772a8f8f85c203d6e541fad2f8f

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5459
c9e6ca58ef1de7bfb27b1db952def2dbb7e3de86
