### ISSUE TITLE
vendor https://github.com/mpl/taglib-go if needed

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#647]
I've fixed a panic (https://github.com/hjfreyer/taglib-go/pull/8) in taglib-go that I ran into while running Camlistore but haven't had a reply so far.

This issue is just a reminder for myself to switch to my fork (hopefully temporarily) so we get the fix if @hjfreyer is too busy to merge it.

**Comment by hjfreyer** [comment]
LGTM! Thanks so much for the fix. Apologies for the delay, I was on vacation.

**Comment by mpl** [comment]
No worries. I didn't mean to pressure you, it was really meant as a reminder for myself. I'll update taglib-go in Camlistore later today.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5477

**Comment by mpl** [comment]
a7ccb62bf65435e4ffe1f52c836fcc6d27e07535
