### ISSUE TITLE
Remove pkg/context

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#648]
We are now vendoring golang.org/x/net/context in.
We should check if we still need anything (camlistore.org)/pkg/context that is not already in golang.org/x/net/context , and if yes try to use functions in golang.org/x/net/context instead, or alternative solutions.

Then we can simply remove ./pkg/context.

**Comment by tgulacsi** [comment]
Hi,

As a second round of my TODO hunt, here is a CL for removing pkg/context: https://camlistore-review.googlesource.com/5596

Passes devcam test, had to use some code duplication for replacing WithHTTPClient, but hope this will be find useful.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5596

9f7e1df32b6df16e2d9f5dd85b911d105e269b0c

**Comment by mpl** [comment]
@tgulacsi ah I hadn't seen your comment. Where is the code duplication for WithHTTPClient that you're speaking of please ?

**Comment by tgulacsi** [comment]
Not much, just

cl := http.DefaultClient
if x := ctx.Value("HTTPClient"); x != nil {
  cl = x.(*http.Client)
}

at a few places, and a function of it in pkg/importer (importers use this the most).

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5601
718c9d8b63c48ec55a1143df2df365cd6c173bdd

**Comment by tgulacsi** [comment]
Nice, thanks for finishing it up!

mpl <notifications@github.com> ezt írta (időpont: 2015. dec. 16., Sze,
16:24):
