### ISSUE TITLE
replace pkg/googlestorage with google.golang.org/cloud/storage(.Client)

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#652]
Now that google.golang.org/cloud/storage has a Client, we can probably use it everywhere instead of pkg/googlestorage.

https://camlistore-review.googlesource.com/5567 already does it for pkg/wkfs/gcs but there are a couple of users left after that:

./website/camweb.go
./cmd/camtool/googinit.go
./pkg/blobserver/google/cloudstorage/storage.go

Once all users are fixed, we can remove pkg/googlestorage.

**Comment by cliveb** [comment]
"Everywhere". Even on Android client?

**Comment by bradfitz** [comment]
The Android client only speaks the camlistore protocol, not GCS directly.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5577 for website

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5588 for camtool googinit

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5589 for blobserver/cloudstorage

**Comment by mpl** [comment]
9e9d5e0bf24ed87fc44fcf60d64e3de8534bbf83
