### ISSUE TITLE
camweb: fix builder proxying

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#658]
So we can have build.camlistore.org redirect to travis CI

**Comment by bradfitz** [comment]
Not a blocker. We can update the website whenever.

**Comment by mpl** [comment]
yeah, I had set it to 0.9 so build.camlistore.org looks good for the release, especially in the light of https://camlistore-review.googlesource.com/5645

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6010
Not sure why we couldn't just keep on proxying though.
