### ISSUE TITLE
launcher: extra escaping

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#659]
<img width="842" alt="screen shot 2015-12-28 at 9 29 41 pm" src="https://cloud.githubusercontent.com/assets/2621/12029892/2a1c884c-adaa-11e5-80d0-1561697cd876.png">

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6037

**Comment by mpl** [comment]
831d6a9ea13dc1dd4565b4a238f4acd11c66de0e
