### ISSUE TITLE
ui: "upload permanode fail, expected blobRef not in response"

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#660]
Got this when trying out a new Camlistore install on GCE using the launcher...

First blob uploaded:

<img width="1064" alt="screen shot 2015-12-28 at 9 33 29 pm" src="https://cloud.githubusercontent.com/assets/2621/12029928/ddc4a816-adaa-11e5-854b-408a551ccb36.png">

It did seem to work on later uploads, though?

**Comment by mpl** [comment]
I've just tried with the launcher currently deployed and could not reproduce. Not sure what else to check.

**Comment by bradfitz** [comment]
I just got it again on a newly-deployed instance.

The server logs say:

```
Dec 30 17:36:48 camlistore-server.c.camlistore-gce-dev.internal systemd-docker[1475]: 2015/12/30 17:36:48 Got websocket message `{"tag":"q0","query":{"sort":"-created","expression":
" ","describe":{"depth":1,"rules":[{"attrs":["camliContent","camliContentImage"]},{"ifCamliNodeType":"foursquare.com:checkin","attrs":["foursquareVenuePermanode"]},{"ifCamliNodeType
":"foursquare.com:venue","attrs":["camliPath:photos"],"rules":[{"attrs":["camliPath:*"]}]}]},"limit":50}}`
Dec 30 17:36:48 camlistore-server.c.camlistore-gce-dev.internal systemd-docker[1475]: 2015/12/30 17:36:48 Added/updated search subscription for tag "q0"
Dec 30 17:36:55 camlistore-server.c.camlistore-gce-dev.internal systemd-docker[1475]: 2015/12/30 17:36:55 Client error: Error receiving blob sha1-6e4c2a3e81edbd9f5b8e6598c855c73d664
444b0: unexpected EOF
```

**Comment by bradfitz** [comment]
And on the second drag-and-drop, it worked (just like before):

Server says:
```
Dec 30 17:38:27 camlistore-server.c.camlistore-gce-dev.internal systemd-docker[1475]: 2015/12/30 17:38:27 Received blob [sha1-25b3887df787459017789df0cfec874605901e01; 548 bytes]
Dec 30 17:38:28 camlistore-server.c.camlistore-gce-dev.internal systemd-docker[1475]: 2015/12/30 17:38:28 Received blob [sha1-f9926c18c2c26e54bf33201f95a402f9b5f7b29a; 732 bytes]
```

**Comment by mpl** [comment]
I've been able to reproduce.

First thing I see is that the file blob is there, but no permanode:

```
% camtool list -describe
sha1-08112e627ef2ad29205c3f61ace3e1a9022efb27 74626
sha1-0b07e1a8f6705afb468842e9d03d8e753e6ad598 262144
sha1-15e0faf1b684841b3ca663acf91322ca1a035feb 81499
sha1-249501c5211d471819c4a125d512b34c65fb53f2 1319	file (automata.jpg size=1566105)
sha1-25ff99838f19ed9e0b8dd727a42690807c7b29ff 69145
sha1-295dcb3004a18c830e40d779410c5c40cb162561 65686
sha1-2dd44b0a30fddd8554f6f24c96f6261723c2d837 75506
sha1-302fedcd1c7fb98262e3a40d09c8f727e5bbbd7d 84282
sha1-33f0d4690e10eff03cbb19c930f9a1c520ba0ffe 659	bytes
sha1-3789b097b8c09a49dfa1114739a3c67c802ad474 <not described>
sha1-46c170af4a293861eaadabd201011d6b09ef6ef4 76531
sha1-47bb05fd0e276d3bb1de193bb70ea87cfb7c782d 71704
sha1-4830de63e4ff7880edcadee74b0a7e6adb6eb8ab 67275
sha1-497247ba04329c232b749a7bbec55d6831b5084e 6084
sha1-5bd54bd8cb308f0a60f18d1f45eeb24e26d36dde <not described>
sha1-7051f32bc8064f0be3e5f912c25c0cc2b1f84482 259	bytes
sha1-7926eb29374b34a2a8e3625d2e2ab1205a86d28a <not described>
sha1-7d5e0af6335995b83fad0c6a0c8eda669a194039 70852
sha1-8adc0c760b968c757c60b4a383b19ddc6eddb792 76102
sha1-8f7b142cbe0b570611bcfc7784f72ab25bb6a3ce <not described>
sha1-92a88dd2b2d5b66603f46ddebd20e7111061098f <not described>
sha1-98449826fed3ee77d34d28c7401ec75ab2c033f8 74779
sha1-a771cc4a0c4d5d73655015ef0dd7fa6dbecb3583 95752
sha1-ace5a37d7db21c682accc446fa53ae4e8b053c49 <not described>
sha1-ad0bea6a49fa364d6212b040b16257ec758711ac 76957
sha1-bea2d063353dc463ed263d1f4d65b0d7ee9545e0 <not described>
sha1-c5864c7a390d1845c1089bb28707e8f6f7bc2d1c 81873
sha1-c6ff837d67bba901368fd9325f48e0f620890f01 259	bytes
sha1-d8a02f324c28e42fb29e0c76c4b4c2d34ce435fc <not described>
sha1-da39818eb9d46516c296269166e993cb14cb5a1b <not described>
sha1-ea6d6d4b553afa09b5368f3d932019aadff0054f 84268
sha1-edee82cc2ebaf8d7ecb857c0f66244c07865f9bb <not described>
sha1-f3c0c80b643789879caf7ef24356ec21a8d24c94 71040
sha1-f4ec1d378d97d509f79dce1ed49936f942be1c2c <not described>

% camget sha1-249501c5211d471819c4a125d512b34c65fb53f2
{"camliVersion": 1,
  "camliType": "file",
  "fileName": "automata.jpg",
  "parts": [
    {
      "blobRef": "sha1-0b07e1a8f6705afb468842e9d03d8e753e6ad598",
      "size": 262144
    },
    {
      "blobRef": "sha1-302fedcd1c7fb98262e3a40d09c8f727e5bbbd7d",
      "size": 84282
    },
    {
      "bytesRef": "sha1-33f0d4690e10eff03cbb19c930f9a1c520ba0ffe",
      "size": 616790
    },
    {
      "blobRef": "sha1-f3c0c80b643789879caf7ef24356ec21a8d24c94",
      "size": 71040
    },
    {
      "blobRef": "sha1-2dd44b0a30fddd8554f6f24c96f6261723c2d837",
      "size": 75506
    },
    {
      "blobRef": "sha1-46c170af4a293861eaadabd201011d6b09ef6ef4",
      "size": 76531
    },
    {
      "blobRef": "sha1-c5864c7a390d1845c1089bb28707e8f6f7bc2d1c",
      "size": 81873
    },
    {
      "blobRef": "sha1-08112e627ef2ad29205c3f61ace3e1a9022efb27",
      "size": 74626
    },
    {
      "blobRef": "sha1-295dcb3004a18c830e40d779410c5c40cb162561",
      "size": 65686
    },
    {
      "blobRef": "sha1-4830de63e4ff7880edcadee74b0a7e6adb6eb8ab",
      "size": 67275
    },
    {
      "blobRef": "sha1-ea6d6d4b553afa09b5368f3d932019aadff0054f",
      "size": 84268
    },
    {
      "blobRef": "sha1-497247ba04329c232b749a7bbec55d6831b5084e",
      "size": 6084
    }
  ],
  "unixMtime": "2013-01-30T13:46:35Z"
```

**Comment by mpl** [comment]
and after a (successful) retry, the only difference I see are the new claim and permanode. So it would seem, at least in that case, that the permanode creation is where the problem lies.

**Comment by mpl** [comment]
For the record, the error comes from:

client-side: server/camlistored/ui/server_connection.js : uploadString_
server-side: pkg/blobserver/handlers/upload.go (handleMultiPartUpload)

**Comment by mpl** [comment]
Doing some experiments since the "debugging with prints" strategy doesn't play well with the rebuild/upload new image/deploy on GCE/ cycle...

Interestingly, on a fresh deploy, if I first camput -filenodes a file, not only does it succeed, but then the subsequent first upload through the UI succeeds as well at first try.

I wonder what's getting "unwedged" by a first upload...

**Comment by mpl** [comment]
The only lead I can think of, is that the server first needs to have the public key blob uploaded to it. But the sign handler does that automatically if needed nowadays.
I guess I could try and confirm the hypothesis by restarting an instance which already has the public key blob (and only that blob) in its bucket.

**Comment by mpl** [comment]
So I deleted my existing instance, I left the config/ bucket intact, and I erased all blobs in the blobs/ bucket EXCEPT for the blob containing the gpg key.
I then created a new instance through the launcher, and I didn't see the bug when I dropped my first image in the UI. Of course it could be some sort of coincidence, but I'm going to take that as an indication that it is not for now, and keep on following that hypothesis as a lead.

**Comment by mpl** [comment]
Again, it could be red herring, but with https://camlistore-review.googlesource.com/5690 (the current WIP docker image for the launcher has this change), I'm not seeing the bug.

**Comment by mpl** [comment]
ok, the good news is I can reproduce the problem with camlistored running on my server, so debugging will now be much easier.

**Comment by mpl** [comment]
systematic repro for that problem:

-on a remote server: start fresh camlistored (wipe blobs, run with -reindex)
-open new incognito window in chrome (otherwise there's apparently some caching preventing the problem)
-navigate to UI
-drop first image on UI

**Comment by mpl** [comment]
@bradfitz Just in case, I've just retried with an updated http2, and I can still reproduce that bug.

**Comment by mpl** [comment]
@bradfitz I have isolated the problem, but I have no better solution than this hack for now, PTAL:

https://camlistore-review.googlesource.com/5706

the WORKINPROGRESS docker image has this fix, in case you want to test a deploy with it.
Maybe you know someone who knows more about Chrome and could shed a light on this? I'm saying Chrome, because I haven't seen the problem on firefox so far.

CC @dotMR

**Comment by mpl** [comment]
additional: @bradfitz and I found more about the cause: for each "new" URL it seems the browser first tries an unauthenticated (no Authorization header) request, and if it gets a 401 it immediately retries with the (previously entered by user) Basic Auth for Authorization.
That usually works fine, except that in the uploadString_ case, we append a Blob to the form data, and Chrome apparently messes up that append in the retry, so we end up sending garbage instead (zeroes I think).

It is basically the same problem as described http://inedo.com/support/kb/1019/workaround-for-chrome-file-uploading-bug

**Comment by mpl** [comment]
@bradfitz I made https://gist.github.com/mpl/521b24fd5a802075c8c1 , which seems to show that the bug is indeed fixed when using the native implementation of XMLHttpRequest.
So I'm starting to suspect our (now dating) vendored closure implementation of goog.net.XhrIo.

I've started updating closure at https://camlistore-review.googlesource.com/5736 but I haven't tested yet either if that fixes the problem or if it doesn't break anything else on the UI.

Also I'd like to do a version of the gist mentioned above that uses our old closure to see if I can get a repro with it.

**Comment by bradfitz** [comment]
Oh! I didn't even know we weren't using the native XHR. Good to know. Promising updates.

**Comment by mpl** [comment]
Sad to report that updating closure does not seem to fix the problem. Now on to modifying my repro so that is uses closure instead of native, just to be sure.

**Comment by mpl** [comment]
ugh. I can't get my repro code to "misbehave" so far. My POST requests have an authorization header right from the start, so of course the actual problem can't occur. I don't know what it is with our UI requests which make them try a first time without authorization.

**Comment by mpl** [comment]
As an additional note: on firefox, the UI also sends its first requests - for each new URL or method - without any authorization (which I still can't reproduce in a simpler example, as all requests except the very first one have an authorization), but it doesn't mess up the resend of the Blob in the FormData.
(which is why the bug does not show up on firefox).

**Comment by mpl** [comment]
also, I've tried forcing the credentials so we'd get authenticated requests right from the start with something like (in uploadString_):

	this.sendXhr_(
		this.config_.blobRoot + "camli/upload",
		goog.bind(this.handleUploadString_, this,
			blobref,
			{success: success, fail: opt_fail}
		),
		"POST",
		fd,
		null, // opt_headers
		0, // opt_timeout. 0 means no timeout, which is the default anyway.
		true // opt_withCredentials
	);

which did not seem to work.

**Comment by mpl** [comment]
@bradfitz finally got a minimal repro that we can show at https://gist.github.com/mpl/dc5d285da61e78739e30
Any people in particular you want me to show it to, or shall I simply report it as a bug against chrome ?
I'll explain in chat/hangout why it took so long (partly because I'm an idiot), and why it doesn't really help us (yet) for Camlistore.

**Comment by bradfitz** [comment]
I think we can do two things in parallel:

1) report it & see if Chrome people care. It doesn't matter whether they do, because:

2) we can also just work around it: we can make GET /ui/ serve an auth token for XHR calls. We'll make sure "GET /ui" never serves CORS headers, and then for all XHRs, send HTTP request header "Authorization: Whatever XXXXXXXXXXToken". Because we set the Authorization header, XHR won't re-try requests.

Thoughts?

**Comment by bradfitz** [comment]
(I also like removing the ambiguity over whether the browser will be retrying things)

**Comment by mpl** [comment]
sgtm for 1). btw, the same behaviour can be observed when the server replies with a 307 to our POST: the client will follow the redirect and repost with a similar mangled body. Whereas firefox again does not have this problem.

I think 2) might be the answer to "what is the difference between our UI and my repro" that I could never find and that forced me to cheat to get that repro.
I'll try it and get back to you.

**Comment by mpl** [comment]
repro demo integrated to camweb: https://camlistore-review.googlesource.com/5747

**Comment by mpl** [comment]
And chromium bug filed: https://code.google.com/p/chromium/issues/detail?id=578914

**Comment by mpl** [comment]
people, we'll be making the plan described in 2) of  https://github.com/camlistore/camlistore/issues/660#issuecomment-172158005 anyway

but it looks like the underlying chromium bug has been fixed recently:
https://code.google.com/p/chromium/issues/detail?id=567692
so, just update your chrome!

**Comment by mpl** [comment]
e03d0af04f9e0e229d836786042d0744ff36a605
