### ISSUE TITLE
camput, camget: verify http2 is being used

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#661]
I verified that http2 is being used for browsers in new launcher instances on GCE.

But is camput/camget using http2 for those instances?

Verify before 0.9.

**Comment by mpl** [comment]
Don't we need at least something like that https://camlistore-review.googlesource.com/5648 and in a few other places to have http2 on clients?

If not, that tells you how little I understand of it right now...

Still struggling to find a good place/way to test for that.

**Comment by mpl** [comment]
and with https://camlistore-review.googlesource.com/5649 I indeed hit that log.Fatal with camput and camget. Is it proof enough that they're not using http2 ?

**Comment by bradfitz** [comment]
Okay, I'll wire up http2.
