### ISSUE TITLE
another fd leak 

### ISSUE THREAD

**Issue by awsong** [camlistore/camlistore#667]
similar to #655 
one line 244 https://github.com/camlistore/camlistore/blob/master/pkg/blobserver/diskpacked/diskpacked.go#L244

if this f.Seek() call returns error, fd should be closed. Otherwise, the error populate up and no Storage object is created then the fd becomes an orphan.

**Comment by awsong** [comment]
When openAllPacks() fails on nextPack() or openForWrite(), those read fds should also be closed.

**Comment by tgulacsi** [comment]
The first one I see, but openAllPacks calls storage.Close on error which closes all in s.fds. Ain't that enough?

**Comment by tgulacsi** [comment]
PTAL https://camlistore-review.googlesource.com/6326

**Comment by awsong** [comment]
Try to remember what I meant back then. 

To answer your question, When openAllPacks fails on nextPack() or openForWrite(), it won't call storage.Close() which is only called when openAllPacks fails on openForRead(). In another word, if line 310 return s.nextPack() returns an err, those read fds should be closed but not.

Hope I made myself clear.

**Comment by tgulacsi** [comment]
I've moved the s.Close() from openAllPacks to its (only) caller. This way all open fds will be closed on any error.
