### ISSUE TITLE
TestTransportSetup failure

### ISSUE THREAD

**Issue by tajtiattila** [camlistore/camlistore#672]
pkg/client.TestTransportSetup fails on my system, apparently because useHTTP2() returns true when called from transportForConfig.

$ cd /c/src/camlistore.org
$ go version
go version go1.5.2 windows/amd64
$ devcam test ./pkg/client
--- FAIL: TestTransportSetup (0.00s)
panic: interface conversion: http.RoundTripper is *http2.Transport, not *http.Transport [recovered]
        panic: interface conversion: http.RoundTripper is *http2.Transport, not *http.Transport

goroutine 12 [running]:
testing.tRunner.func1(0xc08205c870)
        c:/go/src/testing/testing.go:450 +0x178
camlistore.org/pkg/client.TestTransportSetup(0xc08205c870)
        c:/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/transport_test.go:166 +0x8c0
testing.tRunner(0xc08205c870, 0x11da9d8)
        c:/go/src/testing/testing.go:456 +0x9f
created by testing.RunTests
        c:/go/src/testing/testing.go:561 +0x874

goroutine 1 [chan receive]:
testing.RunTests(0xee4de8, 0x11da960, 0x7, 0x7, 0x1)
        c:/go/src/testing/testing.go:562 +0x8b4
testing.(*M).Run(0xc082067ed8, 0x0)
        c:/go/src/testing/testing.go:494 +0x77
main.main()
        camlistore.org/pkg/client/_test/_testmain.go:66 +0x11d
FAIL    camlistore.org/pkg/client       0.152s
Error: exit status 1

**Comment by mpl** [comment]
@tajtiattila thanks. what about with:

  go test ./pkg/client

?

**Comment by mpl** [comment]
@tajtiattila nvm that last comment, I've just remembered about the fake_android build tag

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/5691

**Comment by mpl** [comment]
630ed571ee27c7e478afbb4864a07eca49a0b2c5

@tajtiattila thanks!
