### ISSUE TITLE
panic with cammount

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#686]
It happened in response to an ls a newly created root. Since I'm investigating another bug, other things I did before might have been responsible for the actual cause. I'll write more later if I have a repro.
For now here's the trace:

panic: close of closed channel

goroutine 18692 [running]:
panic(0x97d2e0, 0xc82000be70)
	/home/mpl/go1/src/runtime/panic.go:464 +0x3e6
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).streamByID(0xc820098b00, 0x1000018f1, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:941 +0x101
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).forgetStreamID(0xc820098b00, 0xc8000018f1)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:932 +0x2e
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).RoundTrip(0xc820098b00, 0xc820cd2000, 0xc82098b2c0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:631 +0x600
camlistore.org/vendor/golang.org/x/net/http2.(*Transport).RoundTripOpt(0xc82008c960, 0xc820cd2000, 0x0, 0xc8200ea010, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:282 +0x357
camlistore.org/vendor/golang.org/x/net/http2.(*Transport).RoundTrip(0xc82008c960, 0xc820cd2000, 0xc8222db8e0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:257 +0x41
camlistore.org/pkg/httputil.(*StatsTransport).RoundTrip(0xc820070f00, 0xc820cd2000, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/httputil/transport.go:70 +0x319
net/http.send(0xc820cd2000, 0x7f61aa4344c0, 0xc820070f00, 0x0, 0x0, 0x0, 0xc8225a3b80, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82016c8d0, 0xc820cd2000, 0x0, 0x0, 0x0, 0xc82098b2a0, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82016c8d0, 0xc820cd2000, 0xcaa910, 0x0, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc82016c8d0, 0xc820cd2000, 0xc820088110, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:191 +0x1e4
camlistore.org/pkg/client.(*Client).doReqGated(0xc8200eae00, 0xc820cd2000, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/client.go:921 +0xaa
camlistore.org/pkg/client.(*Client).expect2XX(0xc8200eae00, 0xc820cd2000, 0x4, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/client.go:908 +0x52
camlistore.org/pkg/client.(*Client).Describe(0xc8200eae00, 0xc824aa2900, 0xc82107dd08, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/client.go:556 +0x329
camlistore.org/pkg/fs.(*mutDir).populate(0xc82107dd00, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/fs/mut.go:130 +0x2c5
camlistore.org/pkg/fs.(*mutDir).ReadDir(0xc82107dd00, 0xc820014660, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/fs/mut.go:246 +0x92
camlistore.org/third_party/bazil.org/fuse/fs.(*serveConn).serve(0xc82018e000, 0x7f61aa46e0f0, 0xc820cce050)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/third_party/bazil.org/fuse/fs/serve.go:1046 +0x1014
created by camlistore.org/third_party/bazil.org/fuse/fs.(*Server).Serve
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/third_party/bazil.org/fuse/fs/serve.go:335 +0x528
panic: close of closed channel

goroutine 18544 [running]:
panic(0x97d2e0, 0xc82024c220)
	/home/mpl/go1/src/runtime/panic.go:464 +0x3e6
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).streamByID(0xc820098b00, 0x1000018c5, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:941 +0x101
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).forgetStreamID(0xc820098b00, 0xc8000018c5)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:932 +0x2e
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).RoundTrip(0xc820098b00, 0xc82135a2a0, 0xc825bc2f00, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:631 +0x600
camlistore.org/vendor/golang.org/x/net/http2.(*Transport).RoundTripOpt(0xc82008c960, 0xc82135a2a0, 0x0, 0xac81a0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:282 +0x357
camlistore.org/vendor/golang.org/x/net/http2.(*Transport).RoundTrip(0xc82008c960, 0xc82135a2a0, 0xc8211bac00, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:257 +0x41
camlistore.org/pkg/httputil.(*StatsTransport).RoundTrip(0xc820070f00, 0xc82135a2a0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/httputil/transport.go:70 +0x319
net/http.send(0xc82135a2a0, 0x7f61aa4344c0, 0xc820070f00, 0x0, 0x0, 0x0, 0xc825712480, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82016c8d0, 0xc82135a2a0, 0x0, 0x0, 0x0, 0xc8259b77d0, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82016c8d0, 0xc82135a2a0, 0xcaa910, 0x0, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc82016c8d0, 0xc82135a2a0, 0xc820088110, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:191 +0x1e4
camlistore.org/pkg/client.(*Client).doReqGated(0xc8200eae00, 0xc82135a2a0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/client.go:921 +0xaa
camlistore.org/pkg/client.(*Client).Upload(0xc8200eae00, 0xc824aa9cc8, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/upload.go:459 +0x195d
camlistore.org/pkg/client.(*Client).ReceiveBlob(0xc8200eae00, 0x7f61aa438098, 0xc825bc2c40, 0x7f61aa437f60, 0xc825bc2dc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/get.go:182 +0x214
camlistore.org/pkg/blobserver.receive(0x7f61aa4389d0, 0xc8200eae00, 0x7f61aa438098, 0xc825bc2c40, 0x7f61aa437f60, 0xc825bc2dc0, 0xc820074100, 0x0, 0x0, 0x0, ...)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/receive.go:50 +0x24e
camlistore.org/pkg/blobserver.ReceiveNoHash(0x7f61aa4389d0, 0xc8200eae00, 0x7f61aa438098, 0xc825bc2c40, 0x7f61aa4337a8, 0xc825bc2da0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/receive.go:42 +0x90
camlistore.org/pkg/schema.uploadString(0x7f61aa47c5a8, 0xc8200eae00, 0x7f61aa438098, 0xc825bc2c40, 0xc8210a9600, 0x837, 0x0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/schema/filewriter.go:211 +0x2b4
camlistore.org/pkg/schema.uploadBytes.func1(0x7f61aa47c5a8, 0xc8200eae00, 0x7f61aa438098, 0xc825bc2c40, 0xc8210a9600, 0x837, 0xc8259b6e70)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/schema/filewriter.go:250 +0x66
created by camlistore.org/pkg/schema.uploadBytes
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/schema/filewriter.go:252 +0x546

**Comment by mpl** [comment]
I've just seen it again, this time during a cp:

panic: close of closed channel

goroutine 14900 [running]:
panic(0x97d2e0, 0xc823fd4000)
	/home/mpl/go1/src/runtime/panic.go:464 +0x3e6
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).streamByID(0xc8241de160, 0x10000173d, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:941 +0x101
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).forgetStreamID(0xc8241de160, 0xc80000173d)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:932 +0x2e
camlistore.org/vendor/golang.org/x/net/http2.(*ClientConn).RoundTrip(0xc8241de160, 0xc8268d1dc0, 0xc82695d060, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:631 +0x600
camlistore.org/vendor/golang.org/x/net/http2.(*Transport).RoundTripOpt(0xc82008c960, 0xc8268d1dc0, 0x0, 0xac81a0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:282 +0x357
camlistore.org/vendor/golang.org/x/net/http2.(*Transport).RoundTrip(0xc82008c960, 0xc8268d1dc0, 0xc8211a8000, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/vendor/golang.org/x/net/http2/transport.go:257 +0x41
camlistore.org/pkg/httputil.(*StatsTransport).RoundTrip(0xc820070f40, 0xc8268d1dc0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/httputil/transport.go:70 +0x319
net/http.send(0xc8268d1dc0, 0x7f3b1c6c7328, 0xc820070f40, 0x0, 0x0, 0x0, 0xc820071f40, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82016c8d0, 0xc8268d1dc0, 0x0, 0x0, 0x0, 0xc82695f170, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82016c8d0, 0xc8268d1dc0, 0xcaa910, 0x0, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc82016c8d0, 0xc8268d1dc0, 0xc820088118, 0x0, 0x0)
	/home/mpl/go1/src/net/http/client.go:191 +0x1e4
camlistore.org/pkg/client.(*Client).doReqGated(0xc8200eae00, 0xc8268d1dc0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/client.go:921 +0xaa
camlistore.org/pkg/client.(*Client).Upload(0xc8200eae00, 0xc8211efcc8, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/upload.go:459 +0x195d
camlistore.org/pkg/client.(*Client).ReceiveBlob(0xc8200eae00, 0x7f3b1c704580, 0xc821212220, 0x7f3b1c704418, 0xc82695cf20, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/client/get.go:182 +0x214
camlistore.org/pkg/blobserver.receive(0x7f3b1c704b10, 0xc8200eae00, 0x7f3b1c704580, 0xc821212220, 0x7f3b1c704418, 0xc82695cf20, 0xc820074100, 0x0, 0x0, 0x0, ...)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/receive.go:50 +0x24e
camlistore.org/pkg/blobserver.ReceiveNoHash(0x7f3b1c704b10, 0xc8200eae00, 0x7f3b1c704580, 0xc821212220, 0x7f3b1c6c66d8, 0xc82695cf00, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/blobserver/receive.go:42 +0x90
camlistore.org/pkg/schema.uploadString(0x7f3b1c704a38, 0xc8200eae00, 0x7f3b1c704580, 0xc821212220, 0xc8241b0000, 0x7cc, 0x0, 0x0, 0x0, 0x0)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/schema/filewriter.go:211 +0x2b4
camlistore.org/pkg/schema.uploadBytes.func1(0x7f3b1c704a38, 0xc8200eae00, 0x7f3b1c704580, 0xc821212220, 0xc8241b0000, 0x7cc, 0xc825beca50)
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/schema/filewriter.go:250 +0x66
created by camlistore.org/pkg/schema.uploadBytes
	/home/mpl/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/schema/filewriter.go:252 +0x546

**Comment by mpl** [comment]
@bradfitz I've just noticed this might actually be an http2 client bug, so pinging just in case you've seen and fixed it already.

go version go1.6 linux/amd64

**Comment by bradfitz** [comment]
Is our vendored http2 code the latest version?

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6046

I haven't been able to make sure all tests pass yet, because I'm battling some docker/postgres bullshit that's blocking them.

**Comment by mpl** [comment]
with http2 updated, I was able to cp a ~50MB file to a GCE instance, which I had never been able to do in one go so far.
Then it went (almost) fine with a ~100MB file too. It eventually succeeded but after some weird prodding on my part (but that is another story).
Anyway, no panic anymore so far, so closing it for now.
