### ISSUE TITLE
UI fails to display symlinks

### ISSUE THREAD

**Issue by stevearm** [camlistore/camlistore#687]
1. `camput file mydir` for a directory that contains a symlink
2. Attach that hash to a permanode, so it shows up in the UI
3. Browse to that permanode in the UI to list the files
4. Get a javascript alert ["not a file or dir"](https://github.com/camlistore/camlistore/blob/master/server/camlistored/ui/filetree.js#L143)
5. That entry in the UI just shows the permanode `P`, with no title

The switch statement above it should probably handle this and display the symlink's filename as the title, but make it text instead of a link.

**Comment by stevearm** [comment]
Submitted possible fix: https://camlistore-review.googlesource.com/#/c/6067/

**Comment by mpl** [comment]
93dba45f8d2656b0a77b956ebed258a50d9421a1
