### ISSUE TITLE
declare custom import paths

### ISSUE THREAD

**Issue by willnorris** [camlistore/camlistore#689]
Camlistore uses "camlistore.org/..." to import its packages, but none of the packages actually declare a [custom import path](https://golang.org/s/go14customimport).

This normally wouldn't matter except that when browsing packages in godoc.org, all packages are repeated three times, prefixed with `camlistore.org`, `github.com/camlistore/camlistore`, and `camlistore.googlesource.com/​camlistore.git/​`.  For example: https://godoc.org/go4.org/wkfs?importers

Any reason not to go ahead and add the custom import path comments so that godoc.org only shows the canonical package name? (I've confirmed it will redirect from the non-canonical names)

**Comment by mpl** [comment]
I don't see any reason. We've probably just been lazy about it.
Do you want to take care of it?

**Comment by willnorris** [comment]
yep, I'll put together a CL

**Comment by mpl** [comment]
Thanks. I'm now wondering if we couldn't add a check to the git commit hook, which would at least detect that, and maybe output the command to run to automatically add that stanza.
Thoughts?

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6106
https://review.gerrithub.io/266138

**Comment by willnorris** [comment]
most striaght forward approach might be to parse the output of:

    go list -json $(go list camlistore.org/... | grep -v vendor | grep -v third_party)

looking for packages that don't have an `ImportComment` field.  Might be a simpler way, but that's similar to what I did to add the import comments (see https://github.com/willnorris/tools/tree/master/canon)
