### ISSUE TITLE
Twitter importer: link tweets to their twitter account

### ISSUE THREAD

**Issue by DanielHeath** [camlistore/camlistore#696]
I've imported multiple twitter accounts and it's very hard to search for tweets from one or the other. The twitter user handle is embedded in the URL but the docs don't say anything about substring matches when searching via the UI.

Patch welcome? It's a pretty tiny change.

**Comment by mpl** [comment]
I'm not sure I'm following.

I think you should end up with one permanode per twitter account (and one "container/set" permanode per account for all this account tweets), so for each account you should have a permanode titled something like "nick's Tweets" (where nick is the twitter username). If you then click on that permanode, it should only contain/show you the tweets for this account. Isn't that working?

To answer your other implied question: yes, we do not support yet full-text search. But we've been thinking on doing it with something like https://github.com/blevesearch/bleve someday.
The supported search predicates for now are https://camlistore.googlesource.com/camlistore/+/master/doc/search-ui.txt

In any case, if you still have a problem, what is it that you're proposing to do? set a camliPath back to the twitter account on each tweet?

**Comment by bradfitz** [comment]
He wants to search for a tweet permanode, filtering the search results by a substring of the permanode's URL attribute.

@DanielHeath, I think it might already be supported, though... I seem to recall you can add a tilde somewhere to get a substring?

**Comment by DanielHeath** [comment]
Would you prefer I revise the docs for search to mention you can do that?

**Comment by DanielHeath** [comment]
I think this is actually more of a front-end / discoverability feature.

**Comment by edrex** [comment]
If you know the ref of the account node ("edrex's Tweets") you can find the tweets like so:

```
childrenof:sha1-7f84502b0b3aaa686da5876aaf7ab59599aa2be3
```

(same as the Contents aspect for that node)

You can also search directly like so:

```
attr:camliNodeType:"twitter.com:tweet" attr:url:~edrex
```

The docs on search are technically complete, but not very discoverable for users. Maybe the solution is to build search help into the search box. Opened https://github.com/camlistore/camlistore/issues/808.
