### ISSUE TITLE
picasa importer failling since Oauth2 change

### ISSUE THREAD

**Issue by ajft** [camlistore/camlistore#698]
Since March 10 when there was a change to the picasa importer from Oauth1 to Oauth2, the importer has been failing.

Symptoms are that it will never finish running (72 hours or more when first noticed).

I've stopped camlistore and restarted and told the importer to "re-login" and received an error that there was something wrong with my credentials added the correct callback URL for my dydns.org registration, then manually ran the picasa importer and it picked up all my new photos (30 or so) of the last ten days, but once again the importer doesn't seem to want to finish.  Pressing the "Pause Import" button has no effect.  The importer status page reports:
Running: true
Started: 11h29m10.651559107s ago
There's nothing appearing in the logs (other than the feed importer, foursquare importer and twitter importer msgs on their schedules).

Stopped & restarted camlistore and again did the re-login, saw the message about updated tokens and then manually started an import (at 08:45).  It once again imported 2 days of new photos and continued re-importing photos for approx 90 minutes (these have all been in my camlistore for months), the last message on the console was of 

2016/03/22 09:48:27 Importing media from https://lh3.googleusercontent.com/.../I/20151022_142151.jpg

Once again I can't pause the importer.  System CPU use is up around 90%, all used by camlistored.

**Comment by mpl** [comment]
I've just run a full import from scratch (on an empty camlistore, with devcam server), and it was successful. But I don't have a very large set - it took ~40 mins - which might be why I'm less likely to be able to reproduce what you're seeing.

I'll try and figure out some way for you to find us more debugging info.

Btw, we didn't Go from OAuth1 to OAuth2, but from a deprecated OAuth2 library to the recommended one.

**Comment by mpl** [comment]
@ajft you said approx 90 mins, but could you make sure it's not rather starting to fail after ~1 hour? I'm asking because it looks like we're getting tokens that expire after 60 mins, so if token refreshing is what's failing, it would make sense we'd see that after ~1 hour.

Even though my data does not need 1 hour to be all imported, I think I can nevertheless test that theory myself anyway.

**Comment by ajft** [comment]
@mpl indeed one hour seems to be the key.  I just ran up a copy of devcam, put in my google creds. and watched it for an hour as it sucked down photos, then went silent.  After 21:44 same symptoms as before, the importer is still running but nothing appears on the console and I can't pause it.

2016/03/23 20:43:03 Token = &oauth2.Token{AccessToken:"y..Q", TokenType:"Bearer", RefreshToken:"1/s..6", Expiry:time.Time{sec:63594326583, nsec:167231318, loc:(*time.Location)(0x1c93060)}, raw:map[string]interface {}{"access_token":"y..Q", "token_type":"Bearer", "expires_in":3600, "refresh_token":"1/s//6"}}, error <nil>
2016/03/23 20:43:21 Starting picasa importer account, sha1-0..0: userid 1..6 (Adrian Tritschler)
 :
2016/03/23 21:43:21 Importing media from https://lh3.googleusercontent.com/-g..c/r..M/I/2..8.jpg

**Comment by mpl** [comment]
@ajft thanks. I think I've just been able to reproduce this as well. that's good, I know what to debug now.

**Comment by mpl** [comment]
ok, I found the bug. CL should follow later today.

**Comment by mpl** [comment]
@ajft Can you tell me if https://camlistore-review.googlesource.com/6156 fixes things for you please?

**Comment by ajft** [comment]
@mpl -- with that change it seems to have fixed it.  Has been importing
photos for 75 minutes now without stalling at the hour.  Also correctly
responded to the "pause import" button after 75 minutes, then restarted
correctly a few minutes later when I told it to run again.  Not sure how
long I"ll have to watch to see if finish my 3750 photos, I'll leave it
importing overnight and check in the morning.

**Comment by mpl** [comment]
@ajft Excellent, thanks. Please note that this probably won't be the actual fix though.

**Comment by tgulacsi** [comment]
Nice catch! I just wanted to report that it seems to be a token refresh issue: after a while it reproducibly stalls on start, but (after a camlistored restart) after re-login it works.

**Comment by mpl** [comment]
yeah, I know exactly what the problem is. Just waiting for feedback from Brad on my CL.
