### ISSUE TITLE
GCE: pubkey blob missing

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#700]
After creating a `f1-micro` instance via https://camlistore.org/launch/, there are lots of errors in the log about missing pubkey blob dependency when the indexer is trying to index claims. To get it working, we had to manually upload the pubkey blob:

- create ~/.config/camlistore/.client-config.json with content of https://THE_SERVER/help
- download the keyring (linked from post-launch report page) to client machine and save as `~/.config/camlistore/identity-secring.gpg`
- import the keychain: `gpg --import ~/.config/camlistore/identity-secring.gpg`
- export as ascii armor and upload: `gpg --export --armor '(camlistore)' | camput blob -`

The first step, as @mpl points out, is normal and not strictly necessary (could upload the file via web ui).

Maybe it's also be necessary to re-sync bs -> index after uploading the pubkey, not sure.

cc @mathpunk, who hit this issue, and *@jonathanpittman, who* originally reported in [this thread](https://groups.google.com/forum/#!topic/camlistore/Mjs05Hs8dnI) in January.

**Comment by edrex** [comment]
Possibly relevant: the first attempt to submit the form failed because GCE needed to be enabled for the account. Not sure if bits were flipped on the account which may have affected the subsequent run (#568)

**Comment by edrex** [comment]
Maybe camlistored should automatically put the pubkey blob in place from its keychain, if the key is missing at startup.

**Comment by mpl** [comment]
I've just launched one from scratch and could not repro :(

Steps I followed:

1) created the instance through the launcher
2) went to /help
3) copied the client config from /help
4) downloaded the secring, moved it as identity-secring.gpg (as an aside, maybe it should already be named identity-secring.gpg in cloud storage too)
5) camput file -filenodes some images
6) everything looks good in /ui

And to answer your suggestion, I think we already automatically add the gpg key to the blobstore+indexer, but I'm going to recheck.

**Comment by mpl** [comment]
Both command-line clients (using func (c *Client) UploadAndSignBlob from pkg/client/client.go), and clients using the sign handler (using func (h *Handler) handleSign from pkg/jsonsign/signhandler/sig.go), rely on an uploadPublicKey method to make sure the server has the key.

This would make me think all bases are covered, but you obviously found a way to not go through any of these code paths (or to make them fail?), so if we could get a reliable reproduction on how you got there, it would be really interesting and helpful.

**Comment by edrex** [comment]
I didn't know that creating a permanode through a go client causes the public key to be uploaded, if missing. Maybe that's the key difference: Tom didn't try to upload things with the command line tools, but rather went straight to configuring importers. Another possible first action would be to upload a file by dropping it on the web UI. I think new users are likely to stick with actions they can perform through the web UI at first.

It has been my experience that starting camlistored for the first time generates the keypair and server config, but fails to upload the pubkey blob (not just on GCE). I think maybe is a regression.

Overall, it's my impression that missing pubkey issues have been the biggest source of support threads for the project. I think this is a user experience issue, and requires some design thinking.

Ideas:

- Maybe the client-side uploading should it should be removed or made an explicit flag/mode. I think the current magical behavior is confusing and has acted to mask a long-standing bug in server init.
- Big red error in the web UI if the indexer can't find the pubkey. Detailed instructions to resolve in error.
- I think Camlistore would benefit enormously from a community-curated FAQs, something with voting and stuff like SO. Issues that come up again and again would rise to the top. The mailing list would get fewer repeat threads.

Corrected error in the original issue text: @jonathanpittman posted the initial report

**Comment by edrex** [comment]
#344 indicates that the publish app was actually the server-side piece uploading the pubkey.

**Comment by mpl** [comment]
@edrex Ah yes, that's what I needed. By starting with configuring an importer, I can reproduce, thanks.

And yes, it is true that variants of this issue have been recurring now and then.

**Comment by mpl** [comment]
And indeed, if you instead start with creating e.g. a permanode (even from the UI), then you don't see the  problem when configuring an importer.

**Comment by jonathanpittman** [comment]
I do not have anything significant to add, but as a data point I too had started with configuring importers when I ran into this.  My goal at the time was pulling out all of my data from some other sites and having it stored in camlistore.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6206

**Comment by edrex** [comment]
I got curious why importer doesn't upload the public key, and realized it's because it doesn't go through `signhandler.Handler`, but instead instantiates its own `schema.Signer`. Not sure what to do with that.

**Comment by mpl** [comment]
36944ca8180a818a572a81bb7f7ef40f459095e4
