### ISSUE TITLE
create signed certs with let's encrypt (ACME) by default

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#701]
Mentioned elsewhere (#239, [deploy/gce/deploy.go](https://github.com/camlistore/camlistore/blob/b3ba9aa7cd4372977a875de941b6787e7029e7d1/pkg/deploy/gce/deploy.go#L650)), but the Let's Encrypt CA wasn't public yet.

I think the main obstacle is that an ACME client needs to be able to serve things on ports 80 and 443 for verification. Some non-root are options listed [here](https://github.com/xenolf/lego#sudo). setcap on (newish) Linux is a decent option. But for GCE etc this isn't an issue.

The certs expire after 3 months, so the server needs to refresh them periodically.

Inspiration:
- https://github.com/mholt/caddy does it by default (http/2 too, thanks Brad!)
- https://github.com/dkumor/acmewrapper

**Comment by edrex** [comment]
A super simple alternative would be to make sure that camlistored notices and rotates when the cert file changes on disk. Then, an external process could keep the cert updated (for example, Caddy), and camlistored could just use it.

**Comment by bradfitz** [comment]
There's a pending CL to add `acmewrapper` support: https://camlistore-review.googlesource.com/#/c/6137/1

I left some comments there.

**Comment by edrex** [comment]
Awesome, I should have searched the CLs. Maybe I'll keep this open anyway.

**Comment by mpl** [comment]
rsc has written one too:
https://godoc.org/rsc.io/letsencrypt

**Comment by jeffallen** [comment]
I am using rsc's and it works great. I use setcap to let me bind to port 443. My patch is hacky and says "if httpCert == "autoLetsEncrypt" then use rsc's package, otherwise do the normal thing".

I was planning on cleaning up the hackiness and posting a CL.

**Comment by bradfitz** [comment]
Related but different: #805 (for camlistore.org the website)
