### ISSUE TITLE
camweb: keep github in sync with gerrit

### ISSUE THREAD

**Issue by timthelion** [camlistore/camlistore#708]
Master on github is from Febuary, while googlesource is from April.

https://camlistore.googlesource.com/camlistore/+/master

**Comment by mpl** [comment]
Yes, I know. But Brad's the only one in control of that syncing.

**Comment by bradfitz** [comment]
camweb should probably do the regular push to github, since it's already regularly mirroring from gerrit.

@mpl, you want to repurpose this bug for that automation?

Then we give camlibot an ssh key and push access to github.

**Comment by mpl** [comment]
ACK

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6296

**Comment by mpl** [comment]
fe8372e1171a56843e2295fbca8e3680ce3d38a0
