### ISSUE TITLE
dockerfiles for android build corrupted

### ISSUE THREAD

**Issue by cliveb** [camlistore/camlistore#731]
@mpl we spoke in person. please see this issue in @wasabeef docker project for android  https://github.com/wasabeef/dockerfiles/issues/1

**Comment by mpl** [comment]
@cliveb here's the situation: the wasabeef/android Dockerfile (https://github.com/wasabeef/dockerfiles/blob/master/android/Dockerfile) indeed tries to fetch some archives (like the apache ant one) that do not exist anymore.

Which means if you tried to build the image yourself with docker build you wouldn't be able to. Or the day the maintainer removes the image from his disk and wants to rebuild it, he'll be boned too.

However, the image on the docker registry itself is still there, and very much usable. I was able to 'docker pull wasabeef/android' from two different computers without a problem.

I suspect the docker registry had some problems at the moment you tried. Can you retry to 'docker pull wasabeef/android' and confirm that it works for you now?

Building the "camlistore/android" image is another, different, story. It has other problems, which I'm looking at atm.

**Comment by cliveb** [comment]
@mpl success. thanks for working through the camlistore/android.

Restored session: Sat May 14 03:05:14 PDT 2016

clivebs-bigMac:cliveb seebe$ wget
https://github.com/wasabeef/dockerfiles/blob/master/android/Dockerfile

--2016-05-14 15:01:00--
https://github.com/wasabeef/dockerfiles/blob/master/android/Dockerfile

Resolving github.com... 192.30.252.129

Connecting to github.com|192.30.252.129|:443... connected.

HTTP request sent, awaiting response... 200 OK

Length: unspecified [text/html]

Saving to: 'Dockerfile'


Dockerfile                        [ <=>
          ]  47.64K   244KB/s    in 0.2s


2016-05-14 15:01:00 (244 KB/s) - 'Dockerfile' saved [48781]
