### ISSUE TITLE
foursquare importer panics

### ISSUE THREAD

**Issue by ajft** [camlistore/camlistore#755]
Since 2016-May-03, recent builds are crashing for me as soon as the foursquare importer runs.

2016/05/04 20:13:15 foursquare: importing 100 checkins (offset 100)
2016/05/04 20:13:15 couldn't get image: Get : unsupported protocol scheme ""
2016/05/04 20:13:17 picasa importer account, sha1-a56097db9877fc0861d140cf23ae177147a221ae finished.
2016/05/04 20:13:17 picasa importer account, sha1-a56097db9877fc0861d140cf23ae177147a221ae ran recently enough. Sleeping for 6h9m59.999869638s.
2016/05/04 20:13:19 couldn't get image: Get : unsupported protocol scheme ""
2016/05/04 20:13:20 couldn't get image: Get : unsupported protocol scheme ""
2016/05/04 20:13:20 couldn't get image: Get : unsupported protocol scheme ""
2016/05/04 20:13:22 foursquare: importing 100 checkins (offset 200)
2016/05/04 20:13:23 couldn't get image: Get : unsupported protocol scheme ""
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xaae316]

goroutine 58 [running]:
panic(0x10491c0, 0xc82000e180)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
camlistore.org/pkg/importer/foursquare.(*run).importPlace(0xc8ee08a400, 0xc8a3f90440, 0xc8db658930, 0x0, 0x0, 0x0)
        /home/ajft/src/camlistore/tmp/build-gopath/src/camlistore.org/pkg/importer/foursquare/foursquare.go:426 +0x796
camlistore.org/pkg/importer/foursquare.(*run).importCheckins(0xc8ee08a400, 0x0, 0x0)
        /home/ajft/src/camlistore/tmp/build-gopath/src/camlistore.org/pkg/importer/foursquare/foursquare.go:257 +0x74d
camlistore.org/pkg/importer/foursquare.(*imp).Run(0xc8205274e0, 0xc8bfc316c0, 0x0, 0x0)
        /home/ajft/src/camlistore/tmp/build-gopath/src/camlistore.org/pkg/importer/foursquare/foursquare.go:154 +0x136
camlistore.org/pkg/importer.(*importerAcct).start.func1(0xc8edc6a5b0, 0xc8bfc316c0)
        /home/ajft/src/camlistore/tmp/build-gopath/src/camlistore.org/pkg/importer/importer.go:1133 +0x1b4
created by camlistore.org/pkg/importer.(*importerAcct).start
        /home/ajft/src/camlistore/tmp/build-gopath/src/camlistore.org/pkg/importer/importer.go:1146 +0x416

**Comment by mpl** [comment]
The foursquare importer has changed again very recently, so could you please give me an exact revision with the same panic stack trace as above, so I can be sure to look at the correct lines of code?

**Comment by ajft** [comment]
ok, a mostly complete log from start to crash at
https://gist.github.com/ajft/15c8403dd6dd42bc6b85d0aff5b5cfc8 (trimmed out a dozen lines about feed importer running)

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6498
