### ISSUE TITLE
bad index resulting from broken EXIF header

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#758]
I have a JPG with somehow broken EXIF header:

![hi](https://cloud.githubusercontent.com/assets/14615/15058663/5dfe13c8-12d2-11e6-9d91-78e1fe84e9d4.jpg)

Preview sees Latitude but not Longitude:

![image](https://cloud.githubusercontent.com/assets/14615/15058711/ab6a77be-12d2-11e6-88d2-e3f11374f21d.png)

Adding the file to the store

```
eric@ark ~/g/s/camlistore.org (map)> devcam put file ~/hi.jpg
2016/05/05 14:56:52 Blob server reports error: Error receiving blob sha1-61beed85110b38aa9700c11f042c9c6382e35f8a: bogus row "exifgps|sha1-01b44d981e6451fb4203be915183bf1918385161" = "45.54396275|-4.2949671745890217e%2B09"
Error putting file: Server didn't receive blob.
2016/05/05 14:56:52 Client stats: [uploadRequests=[blobs=2 bytes=236270] uploads=[blobs=1 bytes=235890]]
2016/05/05 14:56:52   #HTTP reqs: 3
2016/05/05 14:56:52    responses: 3 (h1), 0 (h2)
```

results in an indexing error:

```
eric@ark ~/g/s/camlistore.org (master)> devcam server -wipe
...
2016/05/05 14:56:47 Available on http://localhost:3179/ui/
2016/05/05 14:56:52 Received blob [sha1-01b44d981e6451fb4203be915183bf1918385161; 235890 bytes]
2016/05/05 14:56:52 replica: receiving blob sha1-61beed85110b38aa9700c11f042c9c6382e35f8a, 1 successes, 1 failures; backend /index-leveldb/ reported: bogus row "exifgps|sha1-01b44d981e6451fb4203be915183bf1918385161" = "45.54396275|-4.2949671745890217e%2B09"
2016/05/05 14:56:52 Client error: Error receiving blob sha1-61beed85110b38aa9700c11f042c9c6382e35f8a: bogus row "exifgps|sha1-01b44d981e6451fb4203be915183bf1918385161" = "45.54396275|-4.2949671745890217e%2B09"
^C2016/05/05 14:59:50 Got SIGINT: shutting down
2016/05/05 14:59:50 Shut down.
```

The malformed index value is fatal on subsequent starts:

```
eric@ark ~/g/s/camlistore.org (master)> devcam server
...
2016/05/05 14:59:59 Slurping corpus to memory from index...
2016/05/05 14:59:59 Slurping corpus to memory from index... (1/9: meta rows)
2016/05/05 14:59:59 Scanned prefix "meta": 6 rows, 77.163µs
2016/05/05 14:59:59 Slurping corpus to memory from index... (2/9: prefix "signerkeyid")
2016/05/05 14:59:59 Slurping corpus to memory from index... (3/9: prefix "claim")
2016/05/05 14:59:59 Slurping corpus to memory from index... (4/9: prefix "fileinfo")
2016/05/05 14:59:59 Slurping corpus to memory from index... (5/9: prefix "filetimes")
2016/05/05 14:59:59 Slurping corpus to memory from index... (6/9: prefix "imagesize")
2016/05/05 14:59:59 Slurping corpus to memory from index... (7/9: prefix "wholetofile")
2016/05/05 14:59:59 Slurping corpus to memory from index... (8/9: prefix "exifgps")
2016/05/05 14:59:59 Slurping corpus to memory from index... (9/9: prefix "mediatag")
2016/05/05 14:59:59 Scanned prefix "mediatag": 0 rows, 77.278µs
2016/05/05 14:59:59 Scanned prefix "signerkeyid": 1 rows, 115.202µs
2016/05/05 14:59:59 Scanned prefix "imagesize": 1 rows, 60.867µs
2016/05/05 14:59:59 Scanned prefix "fileinfo": 1 rows, 103.711µs
2016/05/05 14:59:59 Scanned prefix "wholetofile": 1 rows, 68.33µs
2016/05/05 14:59:59 Scanned prefix "filetimes": 1 rows, 64.478µs
2016/05/05 14:59:59 Scanned prefix "claim": 2 rows, 428.863µs
2016/05/05 14:59:59 Caught panic installer handlers: error instantiating handler for prefix "/my-search/", type "search": error slurping index to memory: bogus row "exifgps|sha1-01b44d981e6451fb4203be915183bf1918385161" = "45.54396275|-4.2949671745890217e%2B09"
Error parsing config: Caught panic: error instantiating handler for prefix "/my-search/", type "search": error slurping index to memory: bogus row "exifgps|sha1-01b44d981e6451fb4203be915183bf1918385161" = "45.54396275|-4.2949671745890217e%2B09"

eric@ark ~/g/s/camlistore.org (master) [1]>
```

**Comment by edrex** [comment]
Also yes, my panorama skills are clearly amazing

**Comment by edrex** [comment]
AFAICT the sequence is:

 - long is a float. It is much larger than a longitude should be, so it prints in scientific notation as `-4.2949671745890217e+09`
 - its component is escaped since it's `typeStr`, so it becomes `-4.2949671745890217e%2B09`
 - when it is read into corpus, it isn't properly unescaped before being coerced back to float.

I think all of this is correct behavior, except it should be urldecoded when it's read in corpus. Submitted https://camlistore-review.googlesource.com/#/c/6506/.

It might also be a good idea to sanity check the lat/long values before indexing them: `abs(lat) > 90.0 || abs(long) > 180.0)`.

@mpl @tajtiattila

**Comment by mpl** [comment]
To answer your question about sanity checking; yes, I don't see why we shouldn't do that. If so, we should do it even before it reaches the corpus code. We should do it in receive.go, right after decoding the latlong, and before setting the mutation to the index.

I'm also wondering why we're not url decoding before setting the index mutation too. Why would we store the url encoded value in the index?

**Comment by tajtiattila** [comment]
I think strings are url encoded so that content is not mistaken for the separator character '|' (pipe).

**Comment by mpl** [comment]
@tajtiattila Ah good point. But couldn't we leave it url encoded only for content that is at risk of containing a pipe? Numbers like lat and long surely should not contain a pipe.
But maybe it's better to keep it all url encoded for the sake of consistency and clarity...

**Comment by edrex** [comment]
Yeah, the escaping is a little weird. The first thing I tried was to change the type in receive.go from `typeStr` to `typeRawStr`, which seems to work (it leaves the `+` alone`) but would require rebuilding indexes.

Seems like to bounds checking should be in the exif package. Opened https://github.com/rwcarlsen/goexif/pull/47. It seems like PRs on goexif aren't getting reviewed lately though. We could add the check in our code, or fork and vendor the fork. Preference?

**Comment by mpl** [comment]
I think I have review+submit rights on rwcarlsen/goexif so I could review and land it eventually, but I'm not sure yet that's the right place for it, let me think about it some more.

In the meantime, I think it couldn't hurt to do it in receive.go, right after decoding.

**Comment by edrex** [comment]
Added check to https://camlistore-review.googlesource.com/#/c/6506/

**Comment by bradfitz** [comment]
I don't think we should even be putting `e+` notation into the index.

the `fmt.Sprint(float64)` is probably the real problem.

**Comment by edrex** [comment]
Works for me. We don't patch the index, so anyone with a bad value like this should rebuild, right?

**Comment by bradfitz** [comment]
I'd be fine with having a registered set of index-fixer steps that run once on start-up if never run before.

One fixer step could be scanning for these and rewriting them.

**Comment by edrex** [comment]
I just explicitly reset the bad key in my instance, and maybe nobody else hit this.

If they had their server wouldn't start, so we'd probably have heard about it or they'd have moved on.

For the future, setting up a mechanism for registering one-time fixer steps (alongside the existing schema upgrade mechanism) seems useful.

**Comment by edrex** [comment]
Attaching my standalone fixup script (kvfile only) in case it's needed later: https://gist.github.com/7595986d535ce6e781ba46f16169c13d
