### ISSUE TITLE
pkg/blobserver/diskpacked does not seem to support double-delete

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#760]
Since we've added a double deletion test (check that deleting a non-existing blob is not an error) to the standard blobserver test suite (pkg/blobserver/storagetest), I notice diskpacked does not seem to pass that test.

--- FAIL: TestDiskpacked (0.28s)
	diskpacked_test.go:55: diskpacked test dir is "/tmp/diskpacked-test918497993"
	storagetest.go:78: Testing blobserver storage *diskpacked.storage
	storagetest.go:80: Testing Enumerate for empty
	storagetest.go:93: Testing receive
	storagetest.go:112: Testing Enumerate for 1 blobs
	storagetest.go:112: Testing Enumerate for 5 blobs
	storagetest.go:112: Testing Enumerate for 100 blobs
	storagetest.go:117: Testing Fetch
	storagetest.go:127: Testing Stat
	storagetest.go:141: Testing Enumerate on all
	storagetest.go:144: Testing Enumerate 'limit' param
	storagetest.go:150: Testing Enumerate 'after' param; after "sha1-0bd12717c0f2687335671451851af26dd0debeac"
	storagetest.go:157: Testing Enumerate 'after' + 'limit' param; after "sha1-0bd12717c0f2687335671451851af26dd0debeac", limit 1
	storagetest.go:164: Testing Enumerate 'after' + 'limit' param; after "a", limit 1
	storagetest.go:176: Testing Remove
	storagetest.go:187: Testing double-delete
	storagetest.go:189: Double RemoveBlobs: file does not exist
	storagetest.go:66: test *diskpacked.storage FAILED, skipping cleanup!
--- FAIL: TestDiskpackedAltIndex (0.27s)
	diskpacked_test.go:55: diskpacked test dir is "/tmp/diskpacked-test931248532"
	storagetest.go:78: Testing blobserver storage *diskpacked.storage
	storagetest.go:80: Testing Enumerate for empty
	storagetest.go:93: Testing receive
	storagetest.go:112: Testing Enumerate for 1 blobs
	storagetest.go:112: Testing Enumerate for 5 blobs
	storagetest.go:112: Testing Enumerate for 100 blobs
	storagetest.go:117: Testing Fetch
	storagetest.go:127: Testing Stat
	storagetest.go:141: Testing Enumerate on all
	storagetest.go:144: Testing Enumerate 'limit' param
	storagetest.go:150: Testing Enumerate 'after' param; after "sha1-0bd12717c0f2687335671451851af26dd0debeac"
	storagetest.go:157: Testing Enumerate 'after' + 'limit' param; after "sha1-0bd12717c0f2687335671451851af26dd0debeac", limit 1
	storagetest.go:164: Testing Enumerate 'after' + 'limit' param; after "a", limit 1
	storagetest.go:176: Testing Remove
	storagetest.go:187: Testing double-delete
	storagetest.go:189: Double RemoveBlobs: file does not exist

**Comment by mpl** [comment]
@tgulacsi Are you interested in looking into that?

If not, I'll get to it later.

**Comment by tgulacsi** [comment]
PTAL https://camlistore-review.googlesource.com/6556

**Comment by mpl** [comment]
thanks
