### ISSUE TITLE
build failure on NetBSD

### ISSUE THREAD

**Issue by erde74** [camlistore/camlistore#763]
Hello, i tried to build on NetBSD and got the following error
 
>tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/cznic/exp/lldb/2pc.go:285: undefined: fileutil.IsEOF
>tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/cznic/exp/lldb/2pc.go:297: undefined: fileutil.IsEOF
>tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/cznic/exp/lldb/btree.go:188: undefined: fileutil.IsEOF
>tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/cznic/exp/lldb/memfiler.go:218: undefined: fileutil.IsEOF
>tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/cznic/exp/lldb/memfiler.go:340: undefined: fileutil.IsEOF
>tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/cznic/exp/lldb/simplefilefiler.go:72: undefined: fileutil.PunchHole
>tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/cznic/exp/lldb/xact.go:156: undefined: fileutil.IsEOF
>tmp/build-gopath-nosqlite/src/camlistore.org/vendor/github.com/cznic/exp/lldb/xact.go:214: undefined: fileutil.IsEOF

after manually adding  **fileutil_netbsd.go** to vendor/github.com/cznic/fileutil/ the errors where gone.

**Comment by mpl** [comment]
thanks. I'll update our vendored cznic/fileutil asap to fix it properly.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6567
