### ISSUE TITLE
Option show file name(s) as permanode title line

### ISSUE THREAD

**Issue by glowingwire** [camlistore/camlistore#769]
I discovered that a text file shows filename, but an mp4 file doesn't.  This is regarded as a feature. Since I put so much effort into filenames, and folder structure, seeing these would be great help. I propose to always show the filename as object title, because I will never not want the filename, but other people may want it off, so option is requested.

It is hard to search for filenames so seeing them is important.

**Comment by mpl** [comment]
dup of #746 now
