### ISSUE TITLE
describe on file lacks exifgps metadata

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#777]
Describe doesn't currently return gps metadata, although it is indexed. Other metadata which is extracted from the file header (image dimensions, media tags, but not exif tags) are described.

It's needed for map views in the web ui (#766, #767).

It's implemented as part of https://camlistore-review.googlesource.com/#/c/6456/. Since the other part of that CL, which adds a synthesized location field when describing a permanode, is uncertain, I'd like to see the file-describing part split out.

**Comment by tajtiattila** [comment]
There is already DescribedFile.MediaTags but there are no DescribedFile.ExifTags. The Exif tags are in the index, this could be returned, too. While this could theoretically work, the Exif data in the index is modeled after the binary Tiff format (IOW data is just dumped there as is), so it is difficult to parse. 

It would be unfortunate to add a new field in DescribedFile for every new file type we encounter. Perhaps these should be merged into eg. DescribedFile.Metadata. Maybe even in the index database.

Exif has its own ways to represent data, eg. times are in two separate fields (DateTime* and SubSecTime*), just like location (unsigned GPS{Latitude|Longitude} and ~Ref for N/S, E/W). Each know tag (those we care about) should be converted to its format in camlistore (RFC3339 for time and with fmt.Sprintf("%f", x) for lat/long).
