### ISSUE TITLE
CSS files don't load via http/2

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#780]
Something about the way the current version of less.js is doing its XHRs (maybe using the deprecated sync option) is causing the CSS files to fall back to http/1.1. Upgrading to the latest version allows them to load via http/2.

**Comment by edrex** [comment]
https://camlistore-review.googlesource.com/6616

**Comment by bradfitz** [comment]
CL 6616 should reference this bug.

Put at the end:

> Fixes #780

**Comment by edrex** [comment]
Oops, meant to. Thanks, done.
