### ISSUE TITLE
foursquare: attempt to get blank URL image

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#781]
Noticed in logs:

```
May 21 16:58:37 ante camlistored.run[19564]: 2016/05/21 16:58:37 foursquare: importing 100 checkins (offset 600)
May 21 16:58:58 ante camlistored.run[19564]: 2016/05/21 16:58:58 couldn't get image: Get : unsupported protocol scheme ""
May 21 16:59:14 ante camlistored.run[19564]: 2016/05/21 16:59:14 foursquare: importing 100 checkins (offset 700)
```

Something is trying to `http.Get()` on an empty URL string.

The new photos-of-friends importing? /cc @radkat, @mpl

**Comment by ajft** [comment]
I've seen those for months on my camlistore; one very minor suggestion I'd
make about the msg would be if it said "foursquare: couldn't get ..." so
people know where the msg comes from.
