### ISSUE TITLE
video player says "Video can't be played because file is corrupt"

### ISSUE THREAD

**Issue by mkorenkov** [camlistore/camlistore#793]
Got a few of these ones today. Not sure how to get a reliable way to reproduce. Log shows nothing.

**Comment by mpl** [comment]
Please give us more to work with. Where do you see that message? In which circumstance, etc.

**Comment by mkorenkov** [comment]
Good news, data seems to be OK. I was actually able to `camget` the video back, it is playable and I didn't find any issues with it.

It seems, video player was just unable to process it. There could be various reason for that: timeout when downloading, missing frames, unsupported codec/compression/whatever, etc. My best guess would be the timeout as I waited for 10+ minutes for `camget` to actually download the file.

**Comment by mkorenkov** [comment]
I tried to reproduce this one more time and all the videos seems to be fine. The very same video player is able to play them and doesn't complain about it.

It seems, the workaround from #800 did fixed the issue. Closing this one as not actionable.
