### ISSUE TITLE
getting started says Go 1.5 is required

### ISSUE THREAD

**Issue by jeffallen** [camlistore/camlistore#794]
https://camlistore.org/download says that Go 1.5 is required. Go 1.6 is required as of today.

I would have submitted a doc fix for this, but I didn't see where it is in the repo to hack on.

**Comment by happyalu** [comment]
https://camlistore-review.googlesource.com/#/c/6656/

**Comment by willnorris** [comment]
"required as of today"?  Was there a specific commit that requires 1.6?

**Comment by mpl** [comment]
Hey,

I can't properly check things right now (mobile, spotty internet), but
afair on the website we were listing the go version required for the latest
stable release. Which is still go 1.5 for 0.9.

Mathieu

(on phone)

**Comment by happyalu** [comment]
The current tip requires 1.6 (enforced by make.go) . 

The instructions on the release page (https://camlistore.org/doc/release/0.9) correctly say that mininum needed is 1.5. However, the download page (https://camlistore.org/download) has build instructions that I just checked fail with 1.5.4.

Maybe we can 
(a) Add a line to checkout tag 0.9 before building, in case someone wants to build the stable release, and
(b) Clarify that 0.9 needs 1.5, but tip needs 1.6.
?

**Comment by mpl** [comment]
@happyalu yes, let's do (b). https://camlistore.org/doc/release/0.9 already says Go 1.5 (or newer, actually, but nevermind). Let's just fix https://camlistore.org/download to say "As of revision 33a8eec553, Camlistore requires Go 1.6 or newer."

**Comment by happyalu** [comment]
Updated https://camlistore-review.googlesource.com/#/c/6656/
