### ISSUE TITLE
blobpacked_index vs runIndex

### ISSUE THREAD

**Issue by happyalu** [camlistore/camlistore#797]
In an attempt to speed up a large data dump, I was trying to disable indexing. Base config file:

{
    "auth": "localhost",
    "listen": ":3179",
    "identity": "XXX7",
    "identitySecretRing": "/loc/identity-secring.gpg",
    "blobPath": "/loc/camlistore/blobs",
    "packRelated": true,
    "levelDB": "/path/camlistore/index.leveldb",
    "dbNames": null
}

Adding runIndex: false to this set triggers this error: 
"With runIndex disabled, you can't specify any of mongo, mysql, postgres, sqlite" (https://github.com/camlistore/camlistore/blob/e9ae7b016c8a7635a2546e77d83456968aeb59da/pkg/serverinit/genconfig.go#L809)

And then removing levelDB line triggers a panic, because no storage can be found for blobpacked_index: https://github.com/camlistore/camlistore/blob/e9ae7b016c8a7635a2546e77d83456968aeb59da/pkg/serverinit/genconfig.go#L339

Not possible to use blobpacked with a disabled indexer?

**Comment by mpl** [comment]
@happyalu afair, In theory you should be able to. But in practice we've been increasingly relying on the indexer, so I wouldn't be surprised if you can't. I'll double-check, thanks.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6666

Even with that change, I think you're going to run into some trouble when running camput against a Camlistore without an indexer. I'm looking into it.

**Comment by happyalu** [comment]
Thanks, this looks good :+1: 

By the way, (you've probably already seen this) I had tried running the indexer in this manner, camput threw some errors about receiving invalid JSON when asking for whole file digests.

**Comment by mpl** [comment]
yeah, this is fixed in https://camlistore-review.googlesource.com/6676 but gotta run for now before testing it out.
