### ISSUE TITLE
website /gw/ redirect only works for some directories

### ISSUE THREAD

**Issue by willnorris** [camlistore/camlistore#803]
https://camlistore.org/gw/ redirects to source code on googlesource.com.  It hard codes support for the "doc" and "clients" directory, otherwise it assumes that the first path segment is a git ref.  We have at least a few links in https://camlistore.org/doc/status that are broken because they assume that other directories are supported (e.g. https://camlistore.org/gw/server/camlistored).

I would love if we could flip the logic and check if it looks like a git ref first and if not then just assume it's a directory, but I'm not sure if that's easily doable.  Otherwise, we should probably just add support for linking to some of the more common top-level directories like "server" and possibly "website".

Another option would be to add support for /src/ URLs similar to golang.org.  Even if we didn't initially host the source code there ourselves and just redirected to googlesource.com, I really like those URLs better than /gw/.

/cc @edrex: what do you think, since you're starting to add some more direct links to googlesource.com, which I think would be better served by a camlistore.org/src (or similar) URL.

**Comment by edrex** [comment]
It looks like there's only one usage of the git ref form (in CONTRIBUTING.md). My first thought is "why not remove it?", but I find there's a reluctance to delete code here.

How about two handlers, `/ref` for refs and `/src` for master, so it's unambiguous?

**Comment by willnorris** [comment]
If we're going to leave /gw/, then there doesn't seem to be much point in adding a /ref, especially if it's not an oft-used thing.  I would think just adding /src which always takes a source path and assumes the master branch would be sufficient.

**Comment by willnorris** [comment]
fixed in ce00f4cac4be3292e4a3fdec790019335ae27b95
