### ISSUE TITLE
"public mode"

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#804]
Add a mode which hides potentially sensitive content.

I mean, not for me, for a friend. 😝

I think a single attr flag `isPrivate: true` would suffice.

UI only initially, not a security feature (although the semantics could be used later to provide a "public stream" share).

**Comment by edrex** [comment]
Nevermind, circles-style "opt-in" sharing as discussed elsewhere makes more sense.

**Comment by mpl** [comment]
also, note that we're supposed to have some sort of mechanism for hiding the permanodes (even though I've never paid much mind to it). See SkipHidden in pkg/search.
