### ISSUE TITLE
camweb: TLS cert expiring Jun 23rd, move to LetsEncrypt

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#805]
The TLS cert for https://camlistore.org expires "Thursday, June 23, 2016 at 4:59:59 PM Pacific Daylight Time".

I return from my honeymoon Wednesday, June 22nd, 2016, 7:40pm, Pacific Daylight Time.

While I might in theory have time to mess with TLS certs immediately after I return, I doubt it.

@mpl, please update camweb to a vendored copy of https://godoc.org/rsc.io/letsencrypt and persisting the JSON cert cache to local disk, even though that's different than how we do it today (with the cert+key on GCS). That does mean if we destroy the VM and recreate it, it'll re-fetch the certs. Oh well.

**Comment by mpl** [comment]
ACK

**Comment by mpl** [comment]
Well, that was easy: https://camlistore-review.googlesource.com/6757

@bradfitz I've tested that it works in the non prod case at least. Let me know how you want to proceed for the prod launch/testing.

Regarding the cache file being destroyed when we destroy the VM, why can't we have camweb regularly back it up to GCS? And then on startup attempt to download it back from GCS if it exists, and use it?
Or we could even attach a second small persistent disk to the instance on startup, which would not have auto-delete=false, and that would be where we write the cache file.
But of course, this is all probably premature optimization.

**Comment by bradfitz** [comment]
Yes, premature. That would work, but not for step 1.

Feel free to just test it in production if you're around with buffered energy to debug if things go badly.

Related: http://www.commitstrip.com/en/2016/06/13/the-end-of-an-expensive-era/

**Comment by mpl** [comment]
ok. today's not the good day for that, but tomorrow should be long and uninterrupted so I'll do it then.
I will:
1) first do a restart with a built on HEAD to make sure we haven't had any breaking change in the meantime
2) land 6757
3) rebuild, and restart.

**Comment by mpl** [comment]
camweb built from HEAD (46cf811f431fc966e15cadbf83ccd59106f0abb2) now running. So far so good.

**Comment by mpl** [comment]
And https://camlistore.org now running with Let'sEncrypt cert , sha256 E0 B6 3D D1 A1 B2 0C 81 85 3F F9 BE E6 2D 2D 8C A7 7D B5 46 F9 A1 6E 9F 43 23 7A A9 42 FB 15 6D :)

Just to be sure, now forcing a hard reboot to check if everything restarts correctly.

**Comment by mpl** [comment]
And everything still looks good after a stop/start of the VM.

**Comment by mpl** [comment]
@bradfitz I don't think a deletion/recreation test of the VM is needed, as it should hit the same code path as it went through when the current VM ran the new code for the first time, but maybe I'm forgetting something. WDYT?

**Comment by mpl** [comment]
@willnorris same question as above. :)

**Comment by mpl** [comment]
fyi, I'm seeing a couple of these errors in the logs:

2016/06/15 14:43:40 transport: http2Client.notifyError got notified that the client transport was broken EOF.
2016/06/15 14:47:58 http: TLS handshake error from 194.187.170.210:39950: remote error: unknown certificate

And none of them seem to appear before today's changes. Probably just some random client not supporting LE yet?

**Comment by willnorris** [comment]
The main question is just under what circumstances does `/var/le/letsencrypt.cache` get blown away?  Only when deleting and recreating the VM?  Or does it live inside of a docker container and therefore get recreated whenever camweb is restarted (I don't recall how that is setup)?  If the latter, then I would just be worried about hitting the LE limit of 5 requests per week.

**Comment by mpl** [comment]
Unless I got confused again, the cache file should always persist unless we voluntarily destroy the VM.
