### ISSUE TITLE
website: /code/#contributing anchor is broken

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#814]
- https://github.com/camlistore/camlistore/blob/master/CONTRIBUTING.md 
- links to https://camlistore.org/doc/contributing
- that redirects to https://camlistore.org/code#contributing
- ... which is broken (the actual id is #contributing-36 or something)

**Comment by willnorris** [comment]
looks like all the headings on most all the pages are including these numbers at the end of their IDs.  Very strange.  Is there a setting in blackfriday we need to tweak by chance?  Stray trailing punctuation or whitespace in the markdown that's getting converted?

**Comment by edrex** [comment]
The ids start out without suffix on server launch, and then increment on each page load, which is why I didn't catch it.

![jackie-chan-wtf](https://cloud.githubusercontent.com/assets/14615/16179787/6c941c72-3625-11e6-9ac6-eaf4642c8278.jpg)

I imagine this is happening because we are reusing an instance across page renders which is meant to be instantiated once per render (see https://github.com/russross/blackfriday/pull/129). Investigating..

**Comment by edrex** [comment]
https://camlistore-review.googlesource.com/6816

**Comment by mpl** [comment]
hmm, the PR you pointed to says "configurable"; so isn't there a way for us to specify that we want the suffix to be the empty string or something like that?
