### ISSUE TITLE
https://camlistore.org/launch/ is blank

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#815]
@mpl hmm. Maybe doc changes?

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6806

**Comment by edrex** [comment]
Does master auto-deploy camweb?

**Comment by mpl** [comment]
@edrex thanks for the warning. fixed in production now too.

**Comment by mpl** [comment]
camweb is never automatically redeployed.

**Comment by mpl** [comment]
@willnorris @edrex PTAL

https://camlistore-review.googlesource.com/6807
