### ISSUE TITLE
cammount on Mac OS X doesn't seem to work (?)

### ISSUE THREAD

**Issue by bdillahu** [camlistore/camlistore#821]
Current git version (as of yesterday or so)... works fine on Linux, but Mac OS X, with FUSE 3.4.0 it runs, spits out "help" and just sits there... no files visible.

./bin/cammount ~/test_mount                                                                                              master
2016/07/11 09:49:54 mount helper error:
2016/07/11 09:49:54 mount helper error: Available mount options:
2016/07/11 09:49:54 mount helper error:     -o allow_other         allow access to others besides the user who mounted
2016/07/11 09:49:54 mount helper error:                            the file system
2016/07/11 09:49:54 mount helper error:     -o allow_recursion     allow a mount point that itself resides on a OSXFUSE
2016/07/11 09:49:54 mount helper error:                            volume (by default, such mounting is disallowed)
2016/07/11 09:49:54 mount helper error:     -o allow_root          allow access to root (can't be used with allow_other)
2016/07/11 09:49:54 mount helper error:     -o auto_xattr          handle extended attributes entirely through ._ files
2016/07/11 09:49:54 mount helper error:     -o blocksize=<size>    specify block size in bytes of "storage"
2016/07/11 09:49:54 mount helper error:     -o daemon_timeout=<s>  timeout in seconds for kernel calls to daemon
2016/07/11 09:49:54 mount helper error:     -o debug               turn on debug information printing
2016/07/11 09:49:54 mount helper error:     -o default_permissions let the kernel handle permission checks locally
2016/07/11 09:49:54 mount helper error:     -o defer_permissions   defer permission checks to file operations themselves
2016/07/11 09:49:54 mount helper error:     -o direct_io           use alternative (direct) path for kernel-user I/O
2016/07/11 09:49:54 mount helper error:     -o extended_security   turn on macOS extended security (ACLs)
2016/07/11 09:49:54 mount helper error:     -o fsid=<fsid>         set the second 32-bit component of the fsid
2016/07/11 09:49:54 mount helper error:     -o fsname=<name>       set the file system's name
2016/07/11 09:49:54 mount helper error:     -o fssubtype=<num>     set the file system's fssubtype identifier
2016/07/11 09:49:54 mount helper error:     -o fstypename=<name>   set the file system's type name
2016/07/11 09:49:54 mount helper error:     -o iosize=<size>       specify maximum I/O size in bytes
2016/07/11 09:49:54 mount helper error:     -o jail_symlinks       contain symbolic links within the mount
2016/07/11 09:49:54 mount helper error:     -o local               mark the volume as "local" (default is "nonlocal")
2016/07/11 09:49:54 mount helper error:     -o negative_vncache    enable vnode name caching of non-existent objects
2016/07/11 09:49:54 mount helper error:     -o sparse              enable support for sparse files
2016/07/11 09:49:54 mount helper error:     -o volname=<name>      set the file system's volume name
2016/07/11 09:49:54 mount helper error:
2016/07/11 09:49:54 mount helper error: Available negative mount options:
2016/07/11 09:49:54 mount helper error:     -o noalerts            disable all graphical alerts (if any) in OSXFUSE Core
2016/07/11 09:49:54 mount helper error:     -o noappledouble       ignore Apple Double (._) and .DS_Store files entirely
2016/07/11 09:49:54 mount helper error:     -o noapplexattr        ignore all "com.apple.*" extended attributes
2016/07/11 09:49:54 mount helper error:     -o nobrowse            mark the volume as non-browsable by the Finder
2016/07/11 09:49:54 mount helper error:     -o nolocalcaches       meta option equivalent to noreadahead,noubc,novncache
2016/07/11 09:49:54 mount helper error:     -o noreadahead         disable I/O read-ahead behavior for this file system
2016/07/11 09:49:54 mount helper error:     -o nosynconclose       disable sync-on-close behavior (enabled by default)
2016/07/11 09:49:54 mount helper error:     -o nosyncwrites        disable synchronous-writes behavior (dangerous)
2016/07/11 09:49:54 mount helper error:     -o noubc               disable the unified buffer cache for this file system
2016/07/11 09:49:54 mount helper error:     -o novncache           disable the vnode name cache for this file system

**Comment by mpl** [comment]
@edrex @saljam @willnorris or anyone else with a mac, could you confirm/reproduce please?

**Comment by cmpis** [comment]
@mpl I got this not using latest (b4af9400a22cbf6bde8424cf952ebad87393f669)

Using OSX FUSE 3.4.0.

cp at Chriss-MacBook-Pro in ~/src/camlistore/bin (master)
$ ./cammount ~/camlistore
2016/07/15 15:10:07 mount helper error:
2016/07/15 15:10:07 mount helper error: Available mount options:
2016/07/15 15:10:07 mount helper error:     -o allow_other         allow access to others besides the user who mounted
2016/07/15 15:10:07 mount helper error:                            the file system
2016/07/15 15:10:07 mount helper error:     -o allow_recursion     allow a mount point that itself resides on a OSXFUSE
2016/07/15 15:10:07 mount helper error:                            volume (by default, such mounting is disallowed)
2016/07/15 15:10:07 mount helper error:     -o allow_root          allow access to root (can't be used with allow_other)
2016/07/15 15:10:07 mount helper error:     -o auto_xattr          handle extended attributes entirely through ._ files
2016/07/15 15:10:07 mount helper error:     -o blocksize=<size>    specify block size in bytes of "storage"
2016/07/15 15:10:07 mount helper error:     -o daemon_timeout=<s>  timeout in seconds for kernel calls to daemon
2016/07/15 15:10:07 mount helper error:     -o debug               turn on debug information printing
2016/07/15 15:10:07 mount helper error:     -o default_permissions let the kernel handle permission checks locally
2016/07/15 15:10:07 mount helper error:     -o defer_permissions   defer permission checks to file operations themselves
2016/07/15 15:10:07 mount helper error:     -o direct_io           use alternative (direct) path for kernel-user I/O
2016/07/15 15:10:07 mount helper error:     -o extended_security   turn on macOS extended security (ACLs)
2016/07/15 15:10:07 mount helper error:     -o fsid=<fsid>         set the second 32-bit component of the fsid
2016/07/15 15:10:07 mount helper error:     -o fsname=<name>       set the file system's name
2016/07/15 15:10:07 mount helper error:     -o fssubtype=<num>     set the file system's fssubtype identifier
2016/07/15 15:10:07 mount helper error:     -o fstypename=<name>   set the file system's type name
2016/07/15 15:10:07 mount helper error:     -o iosize=<size>       specify maximum I/O size in bytes
2016/07/15 15:10:07 mount helper error:     -o jail_symlinks       contain symbolic links within the mount
2016/07/15 15:10:07 mount helper error:     -o local               mark the volume as "local" (default is "nonlocal")
2016/07/15 15:10:07 mount helper error:     -o negative_vncache    enable vnode name caching of non-existent objects
2016/07/15 15:10:07 mount helper error:     -o sparse              enable support for sparse files
2016/07/15 15:10:07 mount helper error:     -o volname=<name>      set the file system's volume name
2016/07/15 15:10:07 mount helper error:
2016/07/15 15:10:07 mount helper error: Available negative mount options:
2016/07/15 15:10:07 mount helper error:     -o noalerts            disable all graphical alerts (if any) in OSXFUSE Core
2016/07/15 15:10:07 mount helper error:     -o noappledouble       ignore Apple Double (._) and .DS_Store files entirely
2016/07/15 15:10:07 mount helper error:     -o noapplexattr        ignore all "com.apple.*" extended attributes
2016/07/15 15:10:07 mount helper error:     -o nobrowse            mark the volume as non-browsable by the Finder
2016/07/15 15:10:07 mount helper error:     -o nolocalcaches       meta option equivalent to noreadahead,noubc,novncache
2016/07/15 15:10:07 mount helper error:     -o noreadahead         disable I/O read-ahead behavior for this file system
2016/07/15 15:10:07 mount helper error:     -o nosynconclose       disable sync-on-close behavior (enabled by default)
2016/07/15 15:10:07 mount helper error:     -o nosyncwrites        disable synchronous-writes behavior (dangerous)
2016/07/15 15:10:07 mount helper error:     -o noubc               disable the unified buffer cache for this file system
2016/07/15 15:10:07 mount helper error:     -o novncache           disable the vnode name cache for this file system

**Comment by mpl** [comment]
Here's a shot in the dark: https://camlistore-review.googlesource.com/6909

Can you guys try that CL out and let me know if it fixes things for you please?

If anything, it looks like upgrading at least to https://github.com/bazil/fuse/commit/19db53613b8c45efbfe49d0fd6205077332915d0 is needed anyway.

**Comment by bdillahu** [comment]
That seems to work for me... I have FUSE 3.4.0 loaded and after this patch and a recompile, it mounts!

Thanks!

**Comment by mpl** [comment]
@bdillahu thanks
