### ISSUE TITLE
iOS client in iOS 9 requires ForwardSecrecy

### ISSUE THREAD

**Issue by cmpis** [camlistore/camlistore#822]
I've been trying to get my iOS client talking to my google cloud instance of Camlistore. I self signed a cert and installed it on my phone.

However, no matter what settings I change in the Info.plist, I can't get the client to talk to my camlistore server. It complains about error codes 9802 and 9813. 

I tried following this issue on StackOverflow with little success: https://stackoverflow.com/questions/31662134/https-request-in-ios-9-nsurlsession-nsurlconnection-http-load-failed-kcfstrea/32870795

Has anyone run in to this already? 

Extra: I'm not an iOS developer. Sorry for this issue, but I am in a rush and wanted to report. Would this be better on the mailing list than here?

**Comment by mpl** [comment]
Emails get forgotten, issues are easier to track, so never hesitate to open an issue when you find a bug.

I don't know anything about IOS though, so it might take awhile until I do, or until we find someone else to look into the issue.

**Comment by bradfitz** [comment]
Maybe we should change Camlistore and set its minimum TLS version higher, or change its default TLS ciphersuite list to only include Ephemeral Diffie-Helman ones.

Looking at https://en.wikipedia.org/wiki/Template:TLS/SSL_support_history_of_web_browsers it seems that TLS 1.2 support is a fine minimum these days.

**Comment by cmpis** [comment]
Yea I think setting the min to TLS 1.2 is the easiest solution here.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6906

**Comment by cmpis** [comment]
Good news, it worked! I have a patch to the client for building with XCode 7 that I'm going to try submitting soon along with a better README since there isn't a way for users to get the iOS client right now except by compiling.
