### ISSUE TITLE
Is there currently a way to upgrade GCE deployment

### ISSUE THREAD

**Issue by cmpis** [camlistore/camlistore#824]
I wanted to take advantage of #822 being fixed, but I'm not sure how else to upgrade my GCE deploy from the launcher.

Also where is the launcher code? I expected a separate repo under the camlistore org or somewhere in the root of this project and didn't find anything.

**Comment by mpl** [comment]
you'd have to wait for me to make a new docker image for the GCE deployer, which i can do imminently. Then you'd only have to restart your instance from the GCE console, or even 'sudo systemctl restart camlistored' from an ssh to your instance should work.

I'll let you know when the new image is up.

all the launcher code is at pkg/deploy/gce/

**Comment by mpl** [comment]
@cmpis Done. The launcher will now deploy dd230b2cbaec560d16bc886a60177cd27ba54cdf. I've tested that it deploys and boots.
Let me know if hit any problem with it please.

**Comment by cmpis** [comment]
Worked! Thanks @mpl
