### ISSUE TITLE
Add --permanode option to camput for blob

### ISSUE THREAD

**Issue by bdillahu** [camlistore/camlistore#827]
I suggest we add a --permanode option to create a permanode for blobs, the same as currently exist for files.

Right now you can store a file and create a permanode for it in one step, while for a blob (non-file based storage), you have to create the blob, then separately create that permanode.

**Comment by bdillahu** [comment]
Just a note - I'm working on a CL for this...

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/6926
