### ISSUE TITLE
build broken at 3b2ec3a

### ISSUE THREAD

**Issue by kortschak** [camlistore/camlistore#836]
Attempting to build camlistore at tip results in the following failure:

```
$ go run make.go 
gopherjs for publisher error: exit status 1, tmp/build-gopath-nosqlite/src/github.com/gopherjs/gopherjs/compiler/natives/runtime/runtime.go:11:14: TheGoos not declared by package sys
../../go/src/runtime/error.go:70:9: invalid operation: e._type (variable of type *struct{_string *string}) has no field or method string
exit status 1
```

This bisects to 3b2ec3af0f6814b51195311d81c0e592c864caf8.

Note, building with go version devel +31ad583, though see the same with go1.7rc6

**Comment by mpl** [comment]
Yeah i know, this is https://github.com/gopherjs/gopherjs/issues/475

(on phone)

**Comment by kortschak** [comment]
It seems that the build is also broken for go1.6. Though this is a different cause:

```
$ go version
go version go1.6.3 linux/amd64
$ go run make.go 
generated /home/user/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/app/publisher/js/zsearch.go
gopherjs for publisher error: exit status 1, tmp/build-gopath-nosqlite/src/camlistore.org/pkg/buildinfo/testinglinked.go:24:2: undeclared name: testingLinked
exit status 1
```

**Comment by kortschak** [comment]
Sorry, that appears to be a remaining dreg. `rm -rf tmp` fixes this.

**Comment by kortschak** [comment]
@bradfitz Is there an issue to track the need to update the vendored gopherjs after go1.7? This deals with that.

**Comment by bradfitz** [comment]
Historically, Camlistore switches to the latest Go release as the minimum requirement within a ~week of it coming out. Go 1.7 isn't out yet. We'll have a bug, though.
