### ISSUE TITLE
make: git version matching too restrictive

### ISSUE THREAD

**Issue by cyphar** [camlistore/camlistore#839]
`make.go` currently only allows `git describe` to return a 7-character commit ID. However, many people (including myself) use larger defaults (as per the Linux kernel guidelines). This can be fixed by just changing the regex to not be so restrictive.

**Comment by cyphar** [comment]
Here's a patch I wrote two weeks ago and submitted but forgot to create an issue for it: https://camlistore-review.googlesource.com/#/c/6986/

**Comment by tgulacsi** [comment]
Esp. https://news.ycombinator.com/item?id=12296974

Aleksa Sarai <notifications@github.com> ezt írta (időpont: 2016. aug. 17.,
Sze 10:17):

**Comment by cyphar** [comment]
The problem isn't nearly as bad as colliding GPG fingerprints, but the reason you'd want to use >7 characters is to futureproof any references in emails (without also pasting the full commit hash). The actual issue inside the build script is that the code is broken when a user has a custom `gitconfig`.

**Comment by mpl** [comment]
@cyphar what do you think of https://github.com/camlistore/camlistore/issues/888#issuecomment-269601680 instead? if you agree with it, do you want to change your CL to use that solution?

In any case, closing that issue as both issues stem from the same bug, and we can keep on discussing on #888 instead.

**Comment by cyphar** [comment]
@mpl I submitted a PR in gerrit for this on August...

**Comment by mpl** [comment]
@cyphar not quite. the comment I pointed to suggests using the --abbrev option instead.

**Comment by messju** [comment]
I like the fix with "--abbrev=7". Works like a charme for me with git versions 2.11.0 (arch) and 2.1.4 (debian).

Another way would be to use the full hash instead of it's abbreviation.
Add "--no-abbrev" as an option to the git command and change the regexp to:

```
-var gitVersionRx = regexp.MustCompile(`\b\d\d\d\d-\d\d-\d\d-[0-9a-f]{7,7}\b`)
+var gitVersionRx = regexp.MustCompile(`\b\d\d\d\d-\d\d-\d\d-[0-9a-f]{40,40}\b`)

```

**Comment by cyphar** [comment]
Do what you like, but I don't get why you want to keep the restrictive length matching.
