### ISSUE TITLE
ui: provide a 'select all' option

### ISSUE THREAD

**Issue by sid-kurias** [camlistore/camlistore#842]
Lets say I have already stored 10 photos of dogs (tagged as dogs), 10 of cats(tagged as cats).

Here is what I want to do....

Publish the photos of the dogs and cats under a root called pets. 

How do I accomplish the following 
1. Search for (tag:dogs  or tag:cats) and create a set called animals from it.On the UI I can execute the search but couldn't find a "select all" option. There might be too many results to select them individually.

The 'select all' option would be really handy.

Thanks
Sid

**Comment by cyphar** [comment]
+1 on a "select all" option. The problem is that you'd have to do the selection client-side (which means that you'd lose the lazy-loading of the items). It might be a bit harder than it sounds.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/10206
