### ISSUE TITLE
Windows 10 / Go 1.7 build issue (missing vendored dependency)

### ISSUE THREAD

**Issue by iafan** [camlistore/camlistore#844]
Trying to build (`go run make.go`) on Windows fails:

```
> go run make.go
Now rebuilding gopherjs at C:\Storage\Work\Personal\camlistore\camlistore\tmp\build-gopath-nosqlite\bin\gopherjs.exe
error building gopherjs: error while building gopherjs: exit status 1, ..\..\spf13\cobra\command_win.go:9:2: cannot find package "github.com/inconshreveable/mousetrap" in any of: A
        C:\Storage\Work\Personal\camlistore\camlistore\tmp\build-gopath-nosqlite\src\camlistore.org\vendor\github.com\inconshreveable\mousetrap (vendor tree)
        C:\Program Files (x86)\Go\src\github.com\inconshreveable\mousetrap (from $GOROOT)
        C:\Storage\Work\Personal\camlistore\camlistore\tmp\build-gopath-nosqlite\src\github.com\inconshreveable\mousetrap (from $GOPATH)
exit status 1
```

Looks like there's a missing vendored dependency: "github.com/inconshreveable/mousetrap". If I put the module manually into the appropriate folder, it successfully goes past this failure point.

**Comment by iafan** [comment]
Looks like this might be related to #838. Feel free to close if it is so.

**Comment by mpl** [comment]
the windows part is probably covered by https://camlistore-review.googlesource.com/6956
and yes, the Go 1.7 part is issue #838 
I hope to take care of all this soon.

**Comment by mpl** [comment]
Considering:

1) What github.com/inconshrevable/mousetrap is meant for: helping users double-clicking on the gopherjs binary, which I think we don't care about.
2) That our vendored copy of gopherjs is already hacked to not need fsnotify as dependency, because we don't care about gopherjs serve

I'm tempted to also just hack our vendored github.com/spf13/cobra so that it doesn't need mousetrap.

@tajtiattila @bradfitz Any objection ?

**Comment by bradfitz** [comment]
Totally agree.

**Comment by tajtiattila** [comment]
No objections. Let me know if you want me to do it.

**Comment by mpl** [comment]
@tajtiattila sure, feel free to give it a go if that tickles your fancy.

**Comment by tajtiattila** [comment]
With the build tags (see https://camlistore-review.googlesource.com/#/c/6956/) changed gopherjs compiles.

The go:generate in app/publisher/js/main.go uses a shell script to generate zsearch.go, this will not work on windows. The workaround is to run the script manully (if one has bash, eg. msys).

After that the errors with go1.7 on Windows are the same as on Linux, see issue #838 

```
$ go run make.go
gopherjs for publisher error: exit status 1, tmp\build-gopath-nosqlite\src\github.com\gopherjs\gopherjs\compiler\natives\runtime\runtime.go:11:14: TheGoos not declared by package sys
..\..\Go\src\runtime\error.go:70:9: invalid operation: e._type (variable of type *struct{_string *string}) has no field or method string
exit status 1
$
```

**Comment by iafan** [comment]
> The go:generate in app/publisher/js/main.go uses a shell script to generate zsearch.go, this will not work on windows. The workaround is to run the script manully (if one has bash, eg. msys).

If you're about `gensearchtypes.sh`, then I'd like to suggest another workaround. Windows users who have Git installed usually have `sh.exe` executable which could run the script, but the script is called as `./gensearchtypes.sh`, and Windows has no idea how to 'execute' it. A simple solution would be to place a file called `gensearchtypes.sh.bat` next to `gensearchtypes.sh`, which would contain this one line: `@sh gensearchtypes.sh`. Now, when the outer program tries to run `./gensearchtypes.sh`, Windows will find the file with .bat extenstion and run it. This will allow Windows folks to run installation from a vanilla console.

**Comment by tajtiattila** [comment]
@iafan Nice trick, thanks for the tip. But I'm not sure sh.exe is always added to the PATH when installing Git for Windows.

Perhaps it would be nicer to rewrite `gensearchtypes.sh` in Go.

**Comment by iafan** [comment]
Yes, sh.exe is located in the same directory as git.exe, and by default Git updates %PATH%. But yes, I agree, this one-liner batch file can only be treated as a temporary hack.

**Comment by tajtiattila** [comment]
I believe it is only $PROGRAMFILES/Git/cmd that is always added to the PATH, not $PROGRAMFILES/Git/bin where sh.exe und bash.exe resides. I have Git for Windows installed, but the only sh.exe `where` finds is the one that came with MSYS on my system.

**Comment by mpl** [comment]
the zsearch.go is another story, right? so let's talk about it in another issue please.

@tajtiattila I was a bit surprised that you didn't have to modify gopherjs itself for the mousetrap dep, but I suppose it makes sense if the only thing it does is catch a mouse double-click. Just to be sure, have you tried your CL with go1.6.x, so we can be sure your CL fixes the issue, and make.go succeeds without the Go1.7 specific issues?

**Comment by tajtiattila** [comment]
AFAICT the sole purpose of mousetrap is to show a message when an app that should only be used from the CLI is double clicked in Windows Explorer. So removing this from the vendored github.com/spf13/cobra alone fixes the issue.

`go run make.go -all` with the updated CL works for me with Go 1.6.3, even when vendor/github.com/inconshreveable/mousetrap is removed.

**Comment by iafan** [comment]
@tajtiattila I just checked — it depends on installation options: by default it's only Git that is in the PATH, and if one chooses "Use Git and optional Unix tools", then `sh` will be added to the PATH as well.

I also just realized that the generated `zsearch.go` file seems to be empty apart from the static header. This is what I get when running `sh gensearchtypes.sh` manually:

```
doc: no such package camlistore.org/pkg/search.SearchResult
exit status 1
doc: no such package camlistore.org/pkg/search.SearchResultBlob
exit status 1
doc: no such package camlistore.org/pkg/search.DescribeResponse
exit status 1
doc: no such package camlistore.org/pkg/search.MetaMap
exit status 1
doc: no such package camlistore.org/pkg/search.DescribedBlob
exit status 1
doc: no such package camlistore.org/pkg/search.DescribedPermanode
exit status 1
```

Does it work for you?

**Comment by tajtiattila** [comment]
@iafan Yes, that is what I was worried about, the availability of sh depends on the installation options. I used it from MSYS bash, `(cd app/publisher/js && ./gensearchtypes.sh)` works with both 1.6.3 and 1.7 for me.

But @mpl have asked to open an issue for the `gensearchtypes.sh` topic earlier.

**Comment by mpl** [comment]
8c30e24b77bd3122f3653633b7d165c00c17d015
