### ISSUE TITLE
pkg/search: data race on (des *DescribedBlob)

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#846]
At rev ee421c8eb2622241ddf8c647dc117ec4fafc43c0 : 

	==================
	WARNING: DATA RACE
	Write by goroutine 15:
	  camlistore.org/pkg/search.(*DescribeRequest).describeReally()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:714 +0x45b
	  camlistore.org/pkg/search.(*DescribeRequest).Describe.func1()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:596 +0xa8
	
	Previous write by goroutine 106:
	  camlistore.org/pkg/search.(*DescribeRequest).describeReally()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:714 +0x45b
	  camlistore.org/pkg/search.(*DescribeRequest).Describe.func1()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:596 +0xa8
	
	Goroutine 15 (running) created at:
	  camlistore.org/pkg/search.(*DescribeRequest).Describe()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:597 +0x330
	  camlistore.org/pkg/search.(*DescribeRequest).describeRefs()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:857 +0x177
	  camlistore.org/pkg/search.(*DescribeRequest).populatePermanodeFields()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:830 +0xba3
	  camlistore.org/pkg/search.(*DescribeRequest).describeReally()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:721 +0x12cc
	  camlistore.org/pkg/search.(*DescribeRequest).Describe.func1()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:596 +0xa8
	
	Goroutine 106 (finished) created at:
	  camlistore.org/pkg/search.(*DescribeRequest).Describe()
	      /home/mpl/src/camlistore.org/pkg/search/describe.go:597 +0x330
	  camlistore.org/pkg/search.(*Handler).GetRecentPermanodes()
	      /home/mpl/src/camlistore.org/pkg/search/handler.go:472 +0x489
	  camlistore.org/pkg/search.(*Handler).serveRecentPermanodes()
	      /home/mpl/src/camlistore.org/pkg/search/handler.go:501 +0xbf
	  camlistore.org/pkg/search.(*Handler).ServeHTTP()
	      /home/mpl/src/camlistore.org/pkg/search/handler.go:203 +0x2e4
	  camlistore.org/pkg/httputil.(*PrefixHandler).ServeHTTP()
	      /home/mpl/src/camlistore.org/pkg/httputil/httputil.go:114 +0x400
	  camlistore.org/pkg/auth.Handler.serveHTTPForOp()
	      /home/mpl/src/camlistore.org/pkg/auth/auth.go:399 +0x82
	  camlistore.org/pkg/auth.Handler.ServeHTTP()
	      /home/mpl/src/camlistore.org/pkg/auth/auth.go:393 +0x5f
	  camlistore.org/pkg/auth.(*Handler).ServeHTTP()
	      <autogenerated>:9 +0xda
	  net/http.(*ServeMux).ServeHTTP()
	      /home/mpl/go1/src/net/http/server.go:1910 +0x212
	  camlistore.org/pkg/webserver.(*Server).ServeHTTP()
	      /home/mpl/src/camlistore.org/pkg/webserver/webserver.go:127 +0x4bc
	  net/http.serverHandler.ServeHTTP()
	      /home/mpl/go1/src/net/http/server.go:2081 +0x206
	  net/http.(*conn).serve()
	      /home/mpl/go1/src/net/http/server.go:1472 +0x1565
	==================

**Comment by mpl** [comment]
Here's what I think is happening:

Since the dr.Describe->dr.describeReally recursion is creating goroutines, we potentially have several goroutines accessing the same (dr *DescribeRequest). That is why we have dr.mu, which is, among other things, guarding dr.m.
However, dr.m is storing pointers. So, as soon as two goroutines operating on the same dr, have gotten a hold of the same dr.m[bs] (in func (dr *DescribeRequest) describedBlob), they're actually working on the same des DescribedBlob through its address. And as far as I can see, we're not guarding that des at all, hence the race.

@bradfitz Before I start working on a fix, do you agree with the analysis?

**Comment by bradfitz** [comment]
I haven't tested this, but here's what I currently think the problem is and the fix: https://camlistore-review.googlesource.com/8106

**Comment by bradfitz** [comment]
(That is, it passes the existing tests in the package, but I haven't added new ones)

**Comment by mpl** [comment]
315fa6f3d9c06a4cb41afa66d84e6a57c0f77ef2
