### ISSUE TITLE
Reimplement gensearchtypes.sh in Go for better portability

### ISSUE THREAD

**Issue by iafan** [camlistore/camlistore#848]
Currently build process uses [gensearchtypes.sh](https://github.com/camlistore/camlistore/blob/master/app/publisher/js/gensearchtypes.sh) file to automatically generate zsearch.go. The invocation of `./gensearchtypes.sh` fails on Windows for obvious reasons. @tajtiattila [suggested](https://github.com/camlistore/camlistore/issues/844#issuecomment-243060134) to reimplement this in Go, and I did just that.

[Here's the gist with the rewritten script](https://gist.github.com/iafan/8d347f4194aa6a668c2baa7de16713e0). The differences from the original one is that it prints the contents to stdout and doesn't run `gofmt -f` after that. I think it should better be done from the context of the make.go.

**Comment by tgulacsi** [comment]
See https://camlistore-review.googlesource.com/8146
