### ISSUE TITLE
If an attribute's value is too large, picasa import fails

### ISSUE THREAD

**Issue by dldx** [camlistore/camlistore#849]
I'm new to Camlistore (which is pretty amazing by the way!) so I'm not exactly sure what's going on but basically, it looks like the picasa import gets hung up if an attribute in an image file is too large. This is the error I get:

> 2016/08/31 03:03:11 [SyncHandler /bs/ -> /index/] error copying sha1-ca17565d902569eaa1217f99184e2566493d49e8: dest write: sorted: key size is over 767: signerattrvalue|D31C4C21EBDEC02B|title|HINTEN+VL%3A+ANNA+STIEBLICH+%28SPIELT+DORIS%29+UND+ADNAN+MARAL+%28SPIELT+METIN%29+VORNE+VL%3A+EMIL+REINKE+%28SPIELT+NILS%29%2C+JOSEFINE+PREUSS+%28SPIELT+LENA%29%2C+ELYAS+M%27BAREK+%28SPIELT+CEM%29+UND+PEGAH+FERYDONI+%28SPIELT+YAGMUR%29+BEI+FOTOTERMIN+ZUR+NEUEN+ARD+VORABENDSERIE+%22T%C3%9CRKISCH+F%C3%9CR+ANF%C3%84NGER%22+IN+BERLIN+%28150605%29+%2F+SCHAUSPIELERIN+%2F+SCHAUSPIELER+%2F+VORSTELLEN+PR%C3%84SENTIEREN+SERIE+NEU+%2F+VORSTELLUNG+%2F+PR%C3%84SENTATION+%2F+TV+%2F+FERNSEHEN+%2F+FERNSEHSERIE+%2F+FERNSEHSENDUNG+%2F+SENDUNG+%2F+SITZEN+AUF+STEHEN+HINTER+SOFA+COUCH+%2F+HALTEN+HAND+%2F+GRUPPENFOTO+%2F+GRUPPENBILD+%2F+L%C3%84CHELN+%2F+2005+%2F+DEUTSCHLAND+%2F+EUROPA|rt7983-91-68T98:56:91.701070067Z|sha1-ca17565d902569eaa1217f99184e2566493d49e8
2016/08/31 03:03:11 [SyncHandler /bs/ -> /index/] error copying sha1-c61b3dafd6aa3cf853bcaa674f6b90e6ea75790b: dest write: sorted: key size is over 767: signerattrvalue|D31C4C21EBDEC02B|title|HINTEN+VL%3A+ANNA+STIEBLICH+%28SPIELT+DORIS%29+UND+ADNAN+MARAL+%28SPIELT+METIN%29+VORNE+VL%3A+EMIL+REINKE+%28SPIELT+NILS%29%2C+JOSEFINE+PREUSS+%28SPIELT+LENA%29%2C+ELYAS+M%27BAREK+%28SPIELT+CEM%29+UND+PEGAH+FERYDONI+%28SPIELT+YAGMUR%29+BEI+FOTOTERMIN+ZUR+NEUEN+ARD+VORABENDSERIE+%22T%C3%9CRKISCH+F%C3%9CR+ANF%C3%84NGER%22+IN+BERLIN+%28150605%29+%2F+SCHAUSPIELERIN+%2F+SCHAUSPIELER+%2F+VORSTELLEN+PR%C3%84SENTIEREN+SERIE+NEU+%2F+VORSTELLUNG+%2F+PR%C3%84SENTATION+%2F+TV+%2F+FERNSEHEN+%2F+FERNSEHSERIE+%2F+FERNSEHSENDUNG+%2F+SENDUNG+%2F+SITZEN+AUF+STEHEN+HINTER+SOFA+COUCH+%2F+HALTEN+HAND+%2F+GRUPPENFOTO+%2F+GRUPPENBILD+%2F+L%C3%84CHELN+%2F+2005+%2F+DEUTSCHLAND+%2F+EUROPA|rt7983-91-68T98:61:69.712779664Z|sha1-c61b3dafd6aa3cf853bcaa674f6b90e6ea75790b
2016/08/31 03:03:16 [SyncHandler /bs/ -> /index/] error copying sha1-c61b3dafd6aa3cf853bcaa674f6b90e6ea75790b: dest write: sorted: key size is over 767: signerattrvalue|D31C4C21EBDEC02B|title|HINTEN+VL%3A+ANNA+STIEBLICH+%28SPIELT+DORIS%29+UND+ADNAN+MARAL+%28SPIELT+METIN%29+VORNE+VL%3A+EMIL+REINKE+%28SPIELT+NILS%29%2C+JOSEFINE+PREUSS+%28SPIELT+LENA%29%2C+ELYAS+M%27BAREK+%28SPIELT+CEM%29+UND+PEGAH+FERYDONI+%28SPIELT+YAGMUR%29+BEI+FOTOTERMIN+ZUR+NEUEN+ARD+VORABENDSERIE+%22T%C3%9CRKISCH+F%C3%9CR+ANF%C3%84NGER%22+IN+BERLIN+%28150605%29+%2F+SCHAUSPIELERIN+%2F+SCHAUSPIELER+%2F+VORSTELLEN+PR%C3%84SENTIEREN+SERIE+NEU+%2F+VORSTELLUNG+%2F+PR%C3%84SENTATION+%2F+TV+%2F+FERNSEHEN+%2F+FERNSEHSERIE+%2F+FERNSEHSENDUNG+%2F+SENDUNG+%2F+SITZEN+AUF+STEHEN+HINTER+SOFA+COUCH+%2F+HALTEN+HAND+%2F+GRUPPENFOTO+%2F+GRUPPENBILD+%2F+L%C3%84CHELN+%2F+2005+%2F+DEUTSCHLAND+%2F+EUROPA|rt7983-91-68T98:61:69.712779664Z|sha1-c61b3dafd6aa3cf853bcaa674f6b90e6ea75790b
2016/08/31 03:03:16 [SyncHandler /bs/ -> /index/] error copying sha1-ca17565d902569eaa1217f99184e2566493d49e8: dest write: sorted: key size is over 767: signerattrvalue|D31C4C21EBDEC02B|title|HINTEN+VL%3A+ANNA+STIEBLICH+%28SPIELT+DORIS%29+UND+ADNAN+MARAL+%28SPIELT+METIN%29+VORNE+VL%3A+EMIL+REINKE+%28SPIELT+NILS%29%2C+JOSEFINE+PREUSS+%28SPIELT+LENA%29%2C+ELYAS+M%27BAREK+%28SPIELT+CEM%29+UND+PEGAH+FERYDONI+%28SPIELT+YAGMUR%29+BEI+FOTOTERMIN+ZUR+NEUEN+ARD+VORABENDSERIE+%22T%C3%9CRKISCH+F%C3%9CR+ANF%C3%84NGER%22+IN+BERLIN+%28150605%29+%2F+SCHAUSPIELERIN+%2F+SCHAUSPIELER+%2F+VORSTELLEN+PR%C3%84SENTIEREN+SERIE+NEU+%2F+VORSTELLUNG+%2F+PR%C3%84SENTATION+%2F+TV+%2F+FERNSEHEN+%2F+FERNSEHSERIE+%2F+FERNSEHSENDUNG+%2F+SENDUNG+%2F+SITZEN+AUF+STEHEN+HINTER+SOFA+COUCH+%2F+HALTEN+HAND+%2F+GRUPPENFOTO+%2F+GRUPPENBILD+%2F+L%C3%84CHELN+%2F+2005+%2F+DEUTSCHLAND+%2F+EUROPA|rt7983-91-68T98:56:91.701070067Z|sha1-ca17565d902569eaa1217f99184e2566493d49e8

It basically gets hung up on that process indefinitely and it hasn't imported anything else since. Apparently, I had a photo in Google Photos that had a super long title. A quick google search suggests that "key size is over 767" may be related to SQL. I thought that deleting the photo from Google Photos might fix the problem but it doesn't really seem to have fixed it. Also, that wouldn't be an ideal solution for people who actually care about these edge cases. Unfortunately, it was from a google image search so I can't find the photo again to link it to you.. 

Anyway, I wonder if the error message is enough to find the bug. If not, let me know how I can help.

Cheers,
Durand

**Comment by bradfitz** [comment]
Short term: we should probably skip indexing attributes larger than sorted.MaxKeySize / sorted.MaxValueSize. @mpl, can you do that soonish to unblock @durand1?

Longer-term we may want to indirect them through a blob (still bound to 16 MB) or a "bytes" schema blob (unlimited). But even if we store them, we still probably don't want to slurp an unbounded attribute into the index's in-memory corpus search system. But we can think about that more later.

**Comment by mpl** [comment]
ACK, will do today.

**Comment by dldx** [comment]
No need to rush it out but thanks for looking into it!

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8187

**Comment by dldx** [comment]
Works fine for me. Thanks!

**Comment by mpl** [comment]
Closing for now. We'll reopen for the longer term solution.
