### ISSUE TITLE
"wip" and "foo" tags

### ISSUE THREAD

**Issue by remram44** [camlistore/camlistore#865]
Were these meant to be pushed to GitHub?

**Comment by mpl** [comment]
maybe? Is it causing any actual problem?

**Comment by remram44** [comment]
Not on my end... It looks like "wip" was some kind of staging area (someone used `tag wip` instead of `stash`), I'm really not sure what the "foo" release is supposed to be (lots of deleted files)

**Comment by bradfitz** [comment]
@mpl, let's delete them.

You can use a fork in your own github account as a personal scratch space.

**Comment by mpl** [comment]
@bradfitz I'm not sure I can do it myself as I didn't create them, and I don't remember if I have push rights directly to the github repo. but I'll see.

**Comment by mpl** [comment]
ok, I was able to remove them through the github interface. hopefully that didn't break anything.
