### ISSUE TITLE
camnetdns: Let's Encrypt DNS (Unbound) not happy

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#867]
As I've reported here: https://community.letsencrypt.org/t/is-lets-encrypt-dns-not-liking-my-domain-name-server/21303 , we're going to have problems with Let's Encrypt because their DNS does not like something about the camnetdns response(s).

As e.g. http://dnsviz.net/d/camlistore.net/dnssec/ shows, there's a number of things to improve anyway. I'm going to work on what I think are the most likely candidates for failure until I know exactly what Unbound is not happy about.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8586

**Comment by cliveb** [comment]
Nice job, did you already push CL to camlistore.org?

Last evening thought I saw more errors in red http://dnsviz.net/d/
camlistore.net/dnssec/

DNS infosec at this level well out of my depth (just curious to learn).

**Comment by mpl** [comment]
Yes, even though the CL isn't merged yet, the changes are already live on camnetdns.camlistore.org, hence why you saw all the errors/warnings disappear from there.

That way I can test as I go whether Let's Encrypt likes us better yet or not.
