### ISSUE TITLE
unit tests are using up too much memory

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#868]
I can't ever run

  go test ./pkg/...

anymore without having to kill chrome first. Otherwise I hit OOM errors, among other problems.

Of course, this is partly an environment issue: with chrome and a few tabs open, I'm at ~5/7.5 GB mem used. And closing chrome usually releases around 2GB mem.

Still, I'd like to investigate if I could improve the tests so they can run under 2GB of mem used.

**Comment by cliveb** [comment]
Chrome's memory efficiency is being improved with version 55 pegged to be
released around December 6.

http://v8project.blogspot.com/2016/10/fall-cleaning-optimizing-v8-memory.html

https://plus.google.com/+FrancoisBeaufort/posts/EL1E7aA1pLv

**Comment by mpl** [comment]
Almost never a problem anymore for me since I stopped using Gnome, so closing for now.
