### ISSUE TITLE
vendor: update cloud.google.com/go/logging to v2

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#873]
v1 is being deprecated, and we need to switch to v2 before march 2017

https://cloud.google.com/logging/docs/api/v2/migration-to-v2

For us, that basically means updating the vendored copy, and fix how we create log entries in a couple of places.

**Comment by bradfitz** [comment]
We better do this soon, then, so it's in the upcoming release.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8907

**Comment by mpl** [comment]
@bradfitz Shall I use your prototype for logging, that uses net/http instead of grpc, so we can bypass the RootCAs not found problem? If yes, where is that at?
