### ISSUE TITLE
Camlistore doesn't build at Go tip

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#875]
Camlistore doesn't build at Go tip:

```
$ make
go run make.go
Now rebuilding gopherjs at /home/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/bin/gopherjs
error building gopherjs: error while building gopherjs: exit status 2, # camlistore.org/vendor/github.com/gopherjs/gopherjs/compiler
compiler/compiler.go:20: undefined: ___GOPHERJS_REQUIRES_GO_VERSION_1_7___
exit status 1
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 1
ante:camlistore.org $ go version
go version devel +f9d406e Sat Nov 5 01:17:21 2016 +0000 linux/amd64
```

Does GopherJS not work at Go tip?

/cc @mpl

**Comment by mpl** [comment]
Nope. As far as I understood, gopherjs only supports 1.7. They enforce it through https://github.com/gopherjs/gopherjs/blob/master/compiler/version_check.go

If we really needed, I suppose we could hack our vendored copy and see if we can make things work on tip.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8868
