### ISSUE TITLE
blobpacked: the --recovery flag should always be respected

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#876]
If the user runs camlistored with --recovery, the blobpacked code will ignore it if it sees that it has non-zero meta rows.

I had non-zero meta rows because I'd lost my blobpacked index and started camlistored without recovery, which caused the twitter importer to run, which imported jpegs, which created blob packs, so then I had a few dozen meta rows.

But I'd also lost millions of meta rows, and --recover silently didn't recover.

/cc @mpl

**Comment by bradfitz** [comment]
Also, now that I'm using recovery, I realize it has no log entry that it's running. I just see mysqld and camlistored CPU usage.

It needs a log entry that it's starting, and ideally progress updates every 10 seconds.

**Comment by bradfitz** [comment]
The only way I know it's working is watching MySQL ...

```
mysql> select count(*) from rows;
+----------+
| count(*) |
+----------+
|   714391 |
+----------+
1 row in set (0.51 sec)

mysql> select count(*) from rows;
+----------+
| count(*) |
+----------+
|   716400 |
+----------+
1 row in set (0.50 sec)
```

**Comment by bradfitz** [comment]
Also, my CPU is 80% idle while this runs. We should be more aggressive.

**Comment by bradfitz** [comment]
Found a way to get progress:

```
$ find packed/ -type f | wc -l
55593

mysql> select count(distinct substr(v from instr(v, " ")+1 for 45)) from rows;
+-------------------------------------------------------+
| count(distinct substr(v from instr(v, " ")+1 for 45)) |
+-------------------------------------------------------+
|                                                 51824 |
+-------------------------------------------------------+
1 row in set (4.37 sec)
```

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/8687
