### ISSUE TITLE
panic at startup

### ISSUE THREAD

**Issue by stephens2424** [camlistore/camlistore#881]
Noticed my camlistore instance was down after my latest update.

```
Nov 19 02:35:13 new camlistored[7205]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 19 02:35:13 new camlistored[7205]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6183b0]
Nov 19 02:35:13 new camlistored[7205]: goroutine 69372 [running]:
Nov 19 02:35:13 new camlistored[7205]: panic(0xd2a740, 0xc42000c070)
Nov 19 02:35:13 new camlistored[7205]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Nov 19 02:35:13 new camlistored[7205]: camlistore.org/pkg/index.claimsIntfAttrValue(0x0, 0x0, 0xe3ceb3, 0x8, 0x0, 0x0, 0x0, 0x15361a0, 0xc42035e8e0, 0x15361a0, ...)
Nov 19 02:35:13 new camlistored[7205]: #011/home/stephen/go/src/camlistore.org/pkg/index/util.go:91 +0xb0
Nov 19 02:35:13 new camlistored[7205]: camlistore.org/pkg/index.permAttr.get(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15361a0, 0xc42035e8e0, 0xe3ceb3, 0x8, ...)
Nov 19 02:35:13 new camlistored[7205]: #011/home/stephen/go/src/camlistore.org/pkg/index/location.go:152 +0x128
Nov 19 02:35:13 new camlistored[7205]: camlistore.org/pkg/index.(*LocationHelper).permanodeLocation(0xc42035e920, 0x7f0cec353018, 0xc42000d048, 0x15361a0, 0xc425d39560, 0x0, 0x0, 0x0, 0x15361a0, 0xc42035e8e0, ...)
Nov 19 02:35:13 new camlistored[7205]: #011/home/stephen/go/src/camlistore.org/pkg/index/location.go:80 +0x14b
Nov 19 02:35:13 new camlistored[7205]: camlistore.org/pkg/index.(*LocationHelper).PermanodeLocation(0xc42035e920, 0x7f0cec353018, 0xc42000d048, 0x15361a0, 0xc425d39560, 0x0, 0x0, 0x0, 0x15361a0, 0xc42035e8e0, ...)
Nov 19 02:35:13 new camlistored[7205]: #011/home/stephen/go/src/camlistore.org/pkg/index/location.go:55 +0xad
Nov 19 02:35:13 new camlistored[7205]: camlistore.org/pkg/search.(*DescribeRequest).doDescribe(0xc429e0c540, 0x1537220, 0xc42000d048, 0x15361a0, 0xc425d39560, 0x1)
Nov 19 02:35:13 new camlistored[7205]: #011/home/stephen/go/src/camlistore.org/pkg/search/describe.go:754 +0x3ad
Nov 19 02:35:13 new camlistored[7205]: camlistore.org/pkg/search.(*DescribeRequest).StartDescribe.func1(0xc429e0c540, 0xc42a2420e0, 0x1537220, 0xc42000d048, 0x15361a0, 0xc425d39560, 0x1)
Nov 19 02:35:13 new camlistored[7205]: #011/home/stephen/go/src/camlistore.org/pkg/search/describe.go:624 +0xc6
Nov 19 02:35:13 new camlistored[7205]: created by camlistore.org/pkg/search.(*DescribeRequest).StartDescribe
Nov 19 02:35:13 new camlistored[7205]: #011/home/stephen/go/src/camlistore.org/pkg/search/describe.go:625 +0x28f
Nov 19 02:35:13 new systemd[1]: camlistore.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

Haven't gotten to dig into it yet, but I wanted to at least upload the stack trace to an issue. Assuming the problem isn't obvious after a just a little digging, here are some thoughts on direction for investigation:

- I have a twitter importer, picasa importer, and recently, I added an active feed importer
- I have an encrypted blobstore

I'm running a bisect now. Hopefully I'll see the issue soon.

**Comment by stephens2424** [comment]
The bisect pointed me to bdb350dc25ef7a09cf756c1b1cadc522b037bf64. I suspect I have some weirdly detached node in my system somewhere and the caching implemented there doesn't expect it.

Digging into the trace, I found that we hit a condition where both of the return values here are nil (location.go:65):

		pa.attrs, claims = lh.corpus.permanodeAttrsOrClaims(pn, at, signer)

Later, in util.go, called from line 155 of location.go, we expect pa.claims to be non-nil.

**Comment by stephens2424** [comment]
sidenote: is it odd that commit bdb350dc25ef7a09cf756c1b1cadc522b037bf64 shows up in [gerrit](https://camlistore-review.googlesource.com/#/c/8649/), but not [github](https://github.com/camlistore/camlistore/commit/bdb350dc25ef7a09cf756c1b1cadc522b037bf64)?

**Comment by stephens2424** [comment]
Just looking at that code, it seems like there's another case where we are okay returning an empty string in a similar "missing-data" kind of case. This change simply avoids the panic by returning another empty string: https://camlistore-review.googlesource.com/c/8806/

I don't yet have an understanding of how we got into the situation.

**Comment by stephens2424** [comment]
I got it to panic with the arguments to `permanodeAttrsOrClaims`

```
panic: bug: pn: sha1-4068479dad902d905f35d1a4de78b632ce515f8e, at: 0001-01-01 00:00:00 +0000 UTC, signer: sha1-910f08f55d619af3a743f1e19efe77f3af21d3b1
```

I looked up the permanode and get

```
camlistore@new:~/src/camlistore$ ./bin/camget sha1-4068479dad902d905f35d1a4de78b632ce515f8e
{"camliVersion": 1,
  "camliSigner": "sha1-910f08f55d619af3a743f1e19efe77f3af21d3b1",
  "camliType": "permanode",
  "random": "vb1HtN2vlDTqZHSQ2rQYLxn2WjY="
,"camliSig":"wsBcBAABCAAQBQKIbgkACRCPZYdBIPuaxwAAb/YIAGPxHYBBEcHk/ftG/f7bP/S7TW3lKBOvtSKojUvBbz9isVeaStOVInkspOTajmej0apRi4wWSEcMEaKXHQQiHWA6dGCBBrE1MIb6CwceO6p/ZVRHXwGjrQCw+IwdF5AS83i6DsGeValzjwwEcVIVFJ3El+hJbtY4bo1ToSM9mwzJmMppyxYPASoIAVvU4VHhj3JWZhcqSkUAjNHXrfR+30S/VHyuHM/g6AtCLhP2sdOOAWeohkjn0FZOkyFJ2JwB2AVi3iAJGZt1zIa7TGpAv/65lG8DIt1TMgtWcQAL/13WiSmOVSPhnZHWrRa/AP+gJnd00AQxx/PhMpATvHNaaeM==v0mB"}

camlistore@new:~/src/camlistore$ ./bin/camtool describe  sha1-4068479dad902d905f35d1a4de78b632ce515f8e
{
  "meta": {
    "sha1-4068479dad902d905f35d1a4de78b632ce515f8e": {
      "blobRef": "sha1-4068479dad902d905f35d1a4de78b632ce515f8e",
      "camliType": "permanode",
      "size": 562,
      "permanode": {
        "attr": {},
        "modtime": "0001-01-01T00:00:00Z"
      }
    }
  }
}
```

Not sure what to make of it at this point.

**Comment by mpl** [comment]
thanks for the report, I'll try to look into it soon.
pinging @tajtiattila in the meantime, since he was also involved in these changes.

**Comment by tajtiattila** [comment]
In index/location.go permAttr.get calls claimsIntfAttrValue with pa.claims at the end.

Earlier pa.claims was a slice, where a nil value was not a problem. But it was changed to an interface, and claimsIntfAttrValue crashes when it is nil.

permAttr.get should not call claimsIntfAttrValue when pa.claims is nil.

**Comment by mpl** [comment]
> sidenote: is it odd that commit bdb350dc25ef7a09cf756c1b1cadc522b037bf64 shows up in gerrit, but not github?

thanks for the report. I kicked the part that needed kicking. things should be back to normal soon.

**Comment by mpl** [comment]
test to repro the issue:

https://camlistore-review.googlesource.com/8826
