### ISSUE TITLE
pkg/test: get rid of FakeIndex

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#883]
We're using FakeIndex in tests as an alternative implementation of index.Interface.

But in practice, we only ever have/use one implementation of index.Interface; namely index.Index, so I don't think it makes the code better anywhere to pass/use an index.Interface instead of an index.Index. 

Also, the index.Index interface has gotten pretty large and gross, so I don't think it's a good thing that we're tied to it.

Finally, it's not really simpler and nicer to use a FakeIndex instead of e.g. index.NewMemoryIndex() in tests, especially in tests out of the index pkg. On the contrary.

So I think it would be a win to completely get rid of FakeIndex. And maybe that would help us then in cleaning up the index.Interface, or get away from it.

**Comment by mpl** [comment]
CC @tajtiattila

**Comment by bradfitz** [comment]
SGTM

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/11866
