### ISSUE TITLE
Vendored files skipped during build because of incorrect matching expression

### ISSUE THREAD

**Issue by raff** [camlistore/camlistore#887]
The regular expression here: https://github.com/camlistore/camlistore/blob/master/make.go#L83 ignores files with multiple "dots" in the name (i.e. a.b.c.go).

I am trying to see if I can change the "s3" implementation to use the official AWS Go SDK and one of the files is https://github.com/aws/aws-sdk-go/blob/master/service/s3/platform_handlers_go1.6.go (but this could potentially happen with any other vendored package).

I have change the pattern from:
-       rxMirrored = regexp.MustCompile(`^([a-zA-Z0-9\-\_]+\.(?:blobs|camli|css|eot|err|gif|go|s|pb\.go|gpg|html|ico|jpg|js|json|xml|min\.css|min\.js|mp3|otf|png|svg|pdf|psd|tiff|ttf|woff|xcf|tar\.gz|gz|tar\.xz|tbz2|zip|sh))$`)

to:
+       rxMirrored = regexp.MustCompile(`^([a-zA-Z0-9\-\_\.]+\.(?:blobs|camli|css|eot|err|gif|go|s|pb\.go|gpg|html|ico|jpg|js|json|xml|min\.css|min\.js|mp3|otf|png|svg|pdf|psd|tiff|ttf|woff|xcf|tar\.gz|gz|tar\.xz|tbz2|zip|sh))$`)

(adding the "." as a valid character in a filename) and that seems to fix the problem. Wondering if there other characters that should be added to the pattern, or if instead it wouldn't be better to just check the file extension instead of trying a full match)

**Comment by bradfitz** [comment]
Thanks!

**Comment by mpl** [comment]
@raff I think that'll do for now, thanks. Besides, there would be "tricky" cases for just checking the extension, (e.g. .tar.gz), wouldn't there?

PTAL: https://camlistore-review.googlesource.com/9066
