### ISSUE TITLE
git 2.11.0 breaks build

### ISSUE THREAD

**Issue by raff** [camlistore/camlistore#888]
This change in git 2.11.0 causes make.go to fail:

* The default abbreviation length, which has historically been 7, now
   scales as the repository grows, using the approximate number of
   objects in the repository and a bit of math around the birthday
   paradox.  The logic suggests to use 12 hexdigits for the Linux
   kernel, and 9 to 10 for Git itself.

The regular expression used to match the git version expects the 7 digits abbreviated hash, but with 2.11.0 I now get 8 characters.

This change fixes it, but you should evaluate if you want to use a different range:

-var gitVersionRx = regexp.MustCompile(`\b\d\d\d\d-\d\d-\d\d-[0-9a-f]{7,7}\b`)
+var gitVersionRx = regexp.MustCompile(`\b\d\d\d\d-\d\d-\d\d-[0-9a-f]{7,8}\b`)

**Comment by mpl** [comment]
thanks

**Comment by marcellanz** [comment]
the git command issued in `make.go:gitVersion` could also be more precise about the length of the short SHA1 hash it expects with `--abbrev` added to the command:
`git rev-list --max-count=1 --pretty=format:'%ad-%h' --date=short --abbrev=7 HEAD`

with a sensible length, that would prevent "surprises" from those heuristics git does to define the right length for a repo.

**Comment by mpl** [comment]
@marcellanz sounds like an even better solution, thanks.
