### ISSUE TITLE
closure/updatelibrary can't update past 2014-07-26

### ISSUE THREAD

**Issue by josephholsten** [camlistore/camlistore#903]
Note: this is totally not important. I was just playing around to see how closure/updatelibrary worked.

In [vendor/embed/closure/updatelibrary.go](https://github.com/camlistore/camlistore/blob/master/vendor/embed/closure/updatelibrary.go), we have really old pins:

```
const (
	gitRepo = "https://code.google.com/p/closure-library/"
	gitHash = "ab89cf45c216"
)
```

The `gitRepo` easily updates to its new home:

```
	gitRepo = "https://github.com/google/closure-library.git"
```

But attempting to update the `gitHash` yields great sadness. The latest release is `20161201`, which has the hash https://github.com/google/closure-library/commit/073fd68ece55859301e5e8eb045a52ffdda7a72d yields the error:

```
$ go run ./updatelibrary.go -verbose
updating to rev 073fd68ece55859301e5e8eb045a52ffdda7a72d
2017/01/24 23:05:57 Could not generate files list: Invalid line in deps: "goog.addDepend
ency('../../third_party/closure/goog/caja/string/html/htmlparser.js', ['goog.string.html
', 'goog.string.html.HtmlParser', 'goog.string.html.HtmlParser.EFlags', 'goog.string.htm
l.HtmlParser.Elements', 'goog.string.html.HtmlParser.Entities', 'goog.string.html.HtmlSa
xHandler'], [], {});"
exit status 1
```

Doing a git bisect, I found that the last "good" revision is https://github.com/google/closure-library/commit/8c84941f31fe020bf952ea77abdd0504fa5d72a3, and the earliest "bad" revision is https://github.com/google/closure-library/commit/5b822175ad24ed350ad201ab0d08237b3d1315ee

Looks like the signature for `goog.addDependency()` has an extra boolean at the end.

I'm guessing this breaks `pkg/misc/closure/gendeps.go`'s rx for deps:
```
var depsRx = regexp.MustCompile(`^goog.addDependency\(['"]([^/]+[a-zA-Z0-9\-\_/\.]*\.js)['"], \[((['"][\w\.]+['"])+(, ['"][\w\.]+['"])*)\], \[((['"][\w\.]+['"])+(, ['"][\w\.]+['"])*)?\]\);`)
```

Is this a thing I should attempt to "fix"?

**Comment by mpl** [comment]
Does https://camlistore-review.googlesource.com/5736 address your concerns?

I think I had postponed that CL at the time because I didn't know where we were going with the web UI, but now that I have a better idea, I should probably revisit it.

**Comment by josephholsten** [comment]
@mpl it works for some of the intermediate revisions, but it won't work with current https://github.com/google/closure-library/blob/master/closure/goog/deps.js

Looks like instead of a boolean, the latest code has an object as its final param.

eg
```
goog.addDependency('../../third_party/closure/goog/caja/string/html/htmlparser.js', ['goog.string.html', 'goog.string.html.HtmlParser', 'goog.string.html.HtmlParser.EFlags', 'goog.string.html.HtmlParser.Elements', 'goog.string.html.HtmlParser.Entities', 'goog.string.html.HtmlSaxHandler'], [], {});
```

**Comment by josephholsten** [comment]
oh, is there a ticket for the long term plans with the UI? I recall you mentioning switching to gopherjs.

**Comment by mpl** [comment]
Thanks. Are you interested in taking over CL5736? If yes, then please be my guest. But I'm going to land a couple of web UI CLs hopefully very soon. Just letting you know now so you don't have to rebase n times over them.

> oh, is there a ticket for the long term plans with the UI?

I don't think so.

> I recall you mentioning switching to gopherjs.

yes we are. :-) issue #798 
First CL using it should land very soon.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/5736
