### ISSUE TITLE
pkg/httputil: break the dependency on google cloud libs

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#904]
With the web UI using gopherjs (https://camlistore-review.googlesource.com/9086), I'm hitting the same problem that we fixed at 668ca6996780d8bca4b76069e97d30f0f45b5cbe for the publisher.

That is, we're using pkg/auth -> pkg/httutil -> pkg/env , which not only imports many more deps (== larger sized generated javascript), but also breaks the generated javascript anyway. I don't know the reason for the latter yet. I'll have to create a repro to file against GopherJS.

It seems like the sole reason httputil imports env is because of:
  env.IsDev()

And indeed if we replace the above, with

  os.Getenv("CAMLI_DEV_CAMLI_ROOT") != ""

(which is not what I suggest we do as the correct fix)

Then the diff on 

  go list -f '{{.Imports}} {{.Deps}}' -json camlistore.org/server/camlistored/ui/goui

is:

	23d22
	< 		"camlistore.org/pkg/env",
	28,31d26
	< 		"camlistore.org/vendor/cloud.google.com/go/compute/metadata",
	< 		"camlistore.org/vendor/cloud.google.com/go/internal",
	< 		"camlistore.org/vendor/github.com/golang/protobuf/proto",
	< 		"camlistore.org/vendor/github.com/googleapis/gax-go",
	38,52d32
	< 		"camlistore.org/vendor/golang.org/x/net/context",
	< 		"camlistore.org/vendor/golang.org/x/net/context/ctxhttp",
	< 		"camlistore.org/vendor/golang.org/x/net/http2",
	< 		"camlistore.org/vendor/golang.org/x/net/http2/hpack",
	< 		"camlistore.org/vendor/golang.org/x/net/internal/timeseries",
	< 		"camlistore.org/vendor/golang.org/x/net/trace",
	< 		"camlistore.org/vendor/google.golang.org/grpc",
	< 		"camlistore.org/vendor/google.golang.org/grpc/codes",
	< 		"camlistore.org/vendor/google.golang.org/grpc/credentials",
	< 		"camlistore.org/vendor/google.golang.org/grpc/grpclog",
	< 		"camlistore.org/vendor/google.golang.org/grpc/internal",
	< 		"camlistore.org/vendor/google.golang.org/grpc/metadata",
	< 		"camlistore.org/vendor/google.golang.org/grpc/naming",
	< 		"camlistore.org/vendor/google.golang.org/grpc/peer",
	< 		"camlistore.org/vendor/google.golang.org/grpc/transport",
	89,90d68
	< 		"html",
	< 		"html/template",
	128,130d105
	< 		"text/tabwriter",
	< 		"text/template",
	< 		"text/template/parse",

So I'd like to find a way for httputil not to depend on the GCE stuff anymore, while still being able to use something like env.IsDev()

**Comment by bradfitz** [comment]
Can you use build tags?

Make some `+build js` versions of our packages that are thinner?

**Comment by mpl** [comment]
yes, that works perfectly, thanks.

I've added the change to https://camlistore-review.googlesource.com/9086

I'll keep this issue open until I've reported the gopherjs breakage upstream.

**Comment by mpl** [comment]
I haven't been able to create a minimal repro with whatever libs were responsible for breaking the gopherjs output if they were imported. Maybe it's fixed with Go 1.8, who knows?
I'll reopen an issue if/when that shows up again.
