### ISSUE TITLE
go run make.go fails - Ubuntu 16.10 golang 1.8rc3

### ISSUE THREAD

**Issue by Jimmy99** [camlistore/camlistore#905]
Greetings
OS is Ubuntu Server 16.10
golang version is 1.8rc3

I am trying to execute go run make.go but I get the following errors:
Do you know of any issues?

# runtime
/usr/local/go/src/runtime/signal_unix.go:27: _SIG_DFL redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:15
/usr/local/go/src/runtime/signal_unix.go:28: _SIG_IGN redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:16
/usr/local/go/src/runtime/signal_unix.go:37: fwdSig redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:25
/usr/local/go/src/runtime/signal_unix.go:42: disableSigChan redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:35
/usr/local/go/src/runtime/signal_unix.go:43: enableSigChan redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:36
/usr/local/go/src/runtime/signal_unix.go:44: maskUpdatedChan redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:37
/usr/local/go/src/runtime/signal_unix.go:56: signalsOK redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:49
/usr/local/go/src/runtime/signal_unix.go:62: initsig redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:55
/usr/local/go/src/runtime/signal_unix.go:97: sigInstallGoHandler redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:90
/usr/local/go/src/runtime/signal_unix.go:122: sigenable redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:115
/usr/local/go/src/runtime/signal_unix.go:122: too many errors

**Comment by mpl** [comment]
Hi.

I can't reproduce with go 1.8rc3.
This looks like a go installation/setup problem though.

Can you please provide more info, like
-how you installed Go (package manager, source, official binary, etc)?
-how you got Camlistore? (how and where you fetched it, what version).
-your GOPATH and GOROOT.

**Comment by Jimmy99** [comment]
Greetings
Golang I downloaded binary from golang.org:
go1.8rc3.linux-amd64.tar.gz
Camlistore I obtained from  git clone https://camlistore.googlesource.com/camlistore

This is results from go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dimitri/projects/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
dimitri@SPFileServer:~$ echo $PATH
/home/dimitri/bin:/home/dimitri/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin

**Comment by mpl** [comment]
Can you please 

  cd $GOPATH/src/camlistore.org
  rm -rf tmp/build-gopath-*
  go run make.go

and paste the whole output here?

**Comment by Jimmy99** [comment]
Greetings
please see output below:

dimitri@SPFileServer:~/projects/go/src/googlesource/camlistore$ go run make.go
# runtime
/usr/local/go/src/runtime/signal_unix.go:27: _SIG_DFL redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:15
/usr/local/go/src/runtime/signal_unix.go:28: _SIG_IGN redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:16
/usr/local/go/src/runtime/signal_unix.go:37: fwdSig redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:25
/usr/local/go/src/runtime/signal_unix.go:42: disableSigChan redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:35
/usr/local/go/src/runtime/signal_unix.go:43: enableSigChan redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:36
/usr/local/go/src/runtime/signal_unix.go:44: maskUpdatedChan redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:37
/usr/local/go/src/runtime/signal_unix.go:56: signalsOK redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:49
/usr/local/go/src/runtime/signal_unix.go:62: initsig redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:55
/usr/local/go/src/runtime/signal_unix.go:97: sigInstallGoHandler redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:90
/usr/local/go/src/runtime/signal_unix.go:122: sigenable redeclared in this block
	previous declaration at /usr/local/go/src/runtime/signal1_unix.go:115
/usr/local/go/src/runtime/signal_unix.go:122: too many errors

**Comment by Jimmy99** [comment]
Dear mpl
I decided to uninstall go1.8rc3 and installed go1.7.5 instead
Camlistore compiled fine and camlistored runs as per normal.
Just wondering what is up with 1.8rc3?
Regards

**Comment by mpl** [comment]
uh, I should have thought sooner of having a closer look at the specific errors you got, sorry.

It looks to me like your go1.8rc3 install is messed up. I don't think you're supposed to have both a signal_unix.go file and a signal1_unix.go file in the runtime package on go1.8rc3. I only have the signal_unix.go file here.

But on go1.7 both these files exist. So could it be that you forgot to

rm -rf /usr/local/go 

before you unzipped go1.8rc3, and you ended up with an install that has a mix of both versions?

**Comment by Jimmy99** [comment]
That explains why the fresh install sorted it out.
Thanks for all your help
