### ISSUE TITLE
publisher frontend serves mixed content when running behind a reverse proxy

### ISSUE THREAD

**Issue by sllawap** [camlistore/camlistore#908]
I run camlistore behind a reverse proxy. nginx terminates all http(s) connections and proxies the requests to camlistore on a secured network via http.

When accessing a publisher endpoint via http, everything works as expected, but when accessing via https, the publisher attempts to access content over http. From the Chromium developer console:

```publisher.js:79 Mixed Content: The page at 'https://<host>/public/photos/' was loaded over HTTPS, but requested an insecure resource 'http://<host>/public/search'. This content should also be served over HTTPS.```

It seems like camlistore is trying to be a bit too smart about constructing the base URL, when client side would have a more accurate view of the world.

**Comment by sllawap** [comment]
I looked into the root cause of this a few weeks back. The most apparent source of the issue is the following HTML being sent to the client by the publisher frontend when served from reverse proxy via https. The reason the publisher behaves this way is sensible enough: as mentioned before, camlistore is receiving the request over http as https termination happens at the edge:

```
	<script>
	var subjectBasePath =  "/public/photos";
	var subject = "sha1-xxxx";
	var publishedRoot = "sha1-yyyy";
	var pathPrefix = "/public/";
	var host = "<host>";
	var scheme = "http";
	var camliViewIsOwner =  false ;
	</script>
```

This results in fetches for the search frontend from publisher.js to occur over http which causes the mixed content flag to be raised.

The way that other systems handle this (if for some reason schema can't be inferred by the client) is to honor the ```X-Forwarded-Proto``` header for overriding the schema. Would you be receptive to a patch implementing that functionality?

**Comment by mpl** [comment]
SGTM. It should indeed be trivial to add that header check in func (pr *publishRequest) subjectHeader to override the pr.req.TLS when needed.
Actually, if we can, we should add that in a func in pkg/app/app.go , so other apps can benefit from it. And subjectHeader will call that func.

One thing I'm not sure about though, as the request goes like:
client -> nginx -> app handler -> publisher
and that the app handler is effectively a (reverse) proxy, I hope it does not interfere with the header. But I don't think it should, we'll see.

Please add me as a reviewer to the CL if you want to make sure I don't miss it.

**Comment by sllawap** [comment]
This no longer seems to be required.
