### ISSUE TITLE
pkg/deploy/gce: add launcher option to run on Free Tier instance 

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#912]
This issue is about providing a very-low cost solution for users to try Camlistore out.

Google Cloud is now providing an "Always Free" Tier, so we should take advantage of that.

When that option is ticked, we should make sure to create a project/instance that matches the specs described at 
https://cloud.google.com/free/

**Comment by mpl** [comment]
Need to finish issue #819 first though.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/10346

**Comment by cliveb** [comment]
Will this CL make the micro-free tier available in the launcher in the next
monthly release?
https://camlistore.org/launch/

I'd like to delete my current Camlistore instance as I keep stopping and
starting  GCE VM to avoid paying $15+ monthly cloud fees.

**Comment by mpl** [comment]
First and foremost, please note that the Free Tier feature should really be considered a sort of trial/demo thing. f1-micro is tiny and has very little memory, so there's no guarantee Camlistore can perform properly on it in the long run. Also there's only 5GB/month of GCS in the Free Tier, so as soon as you go over that, you start paying the regular price.

I have not cut any release as usual early this month, because there were too few changes that landed in may to make it worth a release imo.
That said, I do hope to make a release early in July, which would coincide as usual with an update to the launcher. So yes, if CL 10346 has landed in the meantime, the launcher will then have the Free Tier feature.

In any case, you should know that it is trivial to run an instance of the Camlistore website (including the launcher), so if needed you could do it yourself or I could do it for you.
