### ISSUE TITLE
error when building: "fork/exec /tmp/go-build466177775/command-line-arguments/_obj/exe/make: permission denied"

### ISSUE THREAD

**Issue by increpare** [camlistore/camlistore#915]
Hellooo - 

Following the instructions here to get started *https://camlistore.org/download*, I ran `git clone https://camlistore.googlesource.com/camlistore`

which was fine. Then I ran `go run make.go`, I got the following error

    fork/exec /tmp/go-build134549651/command-line-arguments/_obj/exe/make: permission denied

( with Debian 8.2, go version go1.8 linux/amd64 )

**Comment by mpl** [comment]
hi.

Is there any more context, or is that the only thing being printed?

a shot in the dark: are you trying to do that in /tmp?

**Comment by increpare** [comment]
Oh wait, I can't even run hello world in go. Something up with my go. Ignore me :)

**Comment by increpare** [comment]
( for anyone getting here via google,  http://stackoverflow.com/a/26514408 was the solution - my distro doesn't like executing things in /tmp and setting `export TMPDIR=~/tmp/` fixed everything )

**Comment by mpl** [comment]
which is exactly why I asked that question about /tmp :-)
