### ISSUE TITLE
Amazon Drive blob server support seems like a no-go

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#916]
Amazon Drive's docs explicitly say:

https://developer.amazon.com/public/apis/experience/cloud-drive/content/developer-guide

> ...
> * Don’t build apps that encrypt customer data
>
> * Don't build apps that scrape content or allow customers to copy content from websites
> ...

Not sure whether that second one would include Camlistore's importers.

Discussion: https://www.reddit.com/r/programming/comments/61zuti/amazon_drive_developer_guide_dont_build_apps_that/

I'm filing this proactively, before people request Amazon Drive blobserver support.

/cc @mpl

**Comment by mpl** [comment]
whoa.
