### ISSUE TITLE
Publisher UI uses incorrect scheme to access resources

### ISSUE THREAD

**Issue by tajtiattila** [camlistore/camlistore#920]
The publisher UI the same scheme (HTTP or HTTPS) for communication (browser→camlistore→publisher) as the backend (publisher→camlistore). This is wrong because camlistore/publisher may run in HTTP mode behind a HTTPS reverse proxy, and therefore the schemes being used in the browser and on the server need to be different.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/9946
