### ISSUE TITLE
react: upgrade to use myitcv.io/react

### ISSUE THREAD

**Issue by myitcv** [camlistore/camlistore#929]
A placeholder for the the move from the old `github.com/myitcv/gopherjs/react` to [`myitcv.io/react`](https://myitcv.io/react)

**Comment by myitcv** [comment]
@mpl currently seeing test errors like https://github.com/camlistore/camlistore/issues/680 locally

Am I missing something obvious on how to make the tests with the equivalent of `-parallel 1` (which I guess would cause things to run in serial, maybe fixing the issue?)

**Comment by mpl** [comment]
you mean you're getting the text file busy errors?
I think I've fixed these in https://camlistore-review.googlesource.com/9326
My first patch was pretty much what you guessed, but Brad didn't like it I think. So the subsequent patchsets are a different approach.

**Comment by myitcv** [comment]
> you mean you're getting the text file busy errors?

Yes.

> I think I've fixed these in https://camlistore-review.googlesource.com/9326

Ok cool.

> My first patch was pretty much what you guessed, but Brad didn't like it I think.

I spent literally no time thinking about it so there's almost certainly more complexity that I'm missing :)

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/10367
