### ISSUE TITLE
Untracked files when running make.go on 04afc9ae

### ISSUE THREAD

**Issue by myitcv** [camlistore/camlistore#931]
I'm unclear whether this is a problem per se, but running `go run make.go --sqlite=true` on 04afc9ae8abaf4700a93cb48b40fc0ec3c2aeff5 leaves my local git tree in the following state:

```
HEAD detached at origin/master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        app/publisher/publisher.js
        server/camlistored/ui/goui.js

nothing added to commit but untracked files present (use "git add" to track)
```

@mpl is this expected?

If not I can add both to `.gitignore` and submit the trivial CL.

**Comment by mpl** [comment]
Sure, I saw you had already done that (adding them to .gitignore) in the CL about react. SGTM to make a specific CL for it.

**Comment by myitcv** [comment]
Ok will do. 

Yes apologies, I forgot to point it out in that CL...
