### ISSUE TITLE
build: error running make.go on macOS Sierra with Go tip

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#935]
I can't seem to build Camlistore.

@mpl, any ideas?

```
brad5k:camlistore.org $ git pull
Already up-to-date.

brad5k:camlistore.org $ git rev-parse HEAD
92b866d8195cbbbc12e241e7fe5653e3ee27949b

brad5k:camlistore.org $ go version
go version devel +26f0a7af45 Fri Jul 14 04:03:31 2017 +0000 darwin/amd64

brad5k:camlistore.org $ ~/go1.8/bin/go version
go version go1.8.3 darwin/amd64

brad5k:camlistore.org $ make
go run make.go
You're using go != 1.8, and CAMLI_GOPHERJS_GOROOT was not provided, so defaulting to /Users/bradfitz/go1.8/bin/go for building gopherjs instead.
generated /Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/app/publisher/js/zsearch.go
gopherjs for web UI error: exit status 1, ../../go/src/runtime/error.go:134:3: undeclared name: throw
../../go/src/runtime/error.go:136:12: undeclared name: CallersFrames
../../go/src/runtime/error.go:144:3: undeclared name: throw
../../go/src/runtime/error.go:148:3: undeclared name: throw
../../go/src/runtime/error.go:153:3: undeclared name: throw
../../go/src/runtime/error.go:156:3: undeclared name: throw
exit status 1
make: *** [all] Error 1

brad5k:camlistore.org $ rm -rf tmp/

brad5k:camlistore.org $ make
go run make.go
You're using go != 1.8, and CAMLI_GOPHERJS_GOROOT was not provided, so defaulting to /Users/bradfitz/go1.8/bin/go for building gopherjs instead.
Now rebuilding gopherjs at /Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/bin/gopherjs
generated /Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/app/publisher/js/zsearch.go
gopherjs generated /Users/bradfitz/src/camlistore.org/tmp/build-gopath-nosqlite/src/camlistore.org/app/publisher/publisher.js
Copied gopherjs generated code to  /Users/bradfitz/src/camlistore.org/app/publisher/publisher.js
gopherjs for web UI error: exit status 1, ../../go/src/runtime/error.go:134:3: undeclared name: throw
../../go/src/runtime/error.go:136:12: undeclared name: CallersFrames
../../go/src/runtime/error.go:144:3: undeclared name: throw
../../go/src/runtime/error.go:148:3: undeclared name: throw
../../go/src/runtime/error.go:153:3: undeclared name: throw
../../go/src/runtime/error.go:156:3: undeclared name: throw
exit status 1
make: *** [all] Error 1
```

**Comment by bradfitz** [comment]
It works if I set GOROOT=$HOME/go1.8, though.

**Comment by mpl** [comment]
@bradfitz I'm pretty sure the vendored gopherjs version we have does not support Go > 1.8. So when they do, which I don't think they will until Go 1.9 is out, we'll just have to update our vendored.

**Comment by bradfitz** [comment]
@mpl did you miss this part:

> You're using go != 1.8, and CAMLI_GOPHERJS_GOROOT was not provided, so defaulting to /Users/bradfitz/go1.8/bin/go for building gopherjs instead.

Didn't you add that logic?

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/10586

**Comment by davronakil** [comment]
Also getting: 

`You're using go != 1.9, and CAMLI_GOPHERJS_GOROOT was not provided, so defaulting to /Users/username/go1.9/bin/go for building gopherjs instead.
/Users/username/go1.9/bin/go not found. You need to specify a go1.9 root in CAMLI_GOPHERJS_GOROOT for building gopherjs
exit status 1
`

running go version go1.10 darwin/amd64

**Comment by bradfitz** [comment]
@davronakil, @mpl, it seems that Perkeep is in a weird state now where we require both Go 1.10 and Go 1.9. Go 1.10 is used for most things, and Go 1.9 is used for GopherJS.

@mpl, we should probably roll back the Go 1.10 dependency for now, until GopherJS Go 1.10 is ready.

**Comment by mpl** [comment]
Even if we roll back the change, he would still get that error, as he tried with Go tip anyway. I think we rather need to work on the error message.

**Comment by mpl** [comment]
@davronakil Did you install go 1.10 specifically for Perkeep, or were you already using it before anyway?
Do you think the error message is not clear enough for you to keep going?

**Comment by davronakil** [comment]
1. I installed 1.10 specifically for Perkeep. 
2. I also tried to revert back to 1.9 and got the same error message. 
3. And the error message was not clear enough for me to continue. I got stuck and I have yet to finish setting up Perkeep.

Thanks for your responses and work.

**Comment by mpl** [comment]
@davronakil ok, thanks for the info.

Are you sure about 2. though? the error should have been a different one in that case.

In any case, as soon as https://camlistore-review.googlesource.com/c/camlistore/+/14387 lands, it should be the situation clearer again.

**Comment by mpl** [comment]
@davronakil https://camlistore-review.googlesource.com/c/camlistore/+/14387 is in. you can pull and retry with 1.9 now.

**Comment by davronakil** [comment]
Thanks. I edited the make.go file to have the following: 
```
const (
	goVersionMinor  = 9
	gopherJSGoMinor = 9
)
```

Running go 1.9 now, and still getting the following: 

> camlistore (master) $ go version
> go version go1.9.4 darwin/amd64
> camlistore (master) $ go run make.go
> You're using go != 1.9, and CAMLI_GOPHERJS_GOROOT was not provided, so defaulting to /Users/username/go1.9/bin/go for building gopherjs instead.
> /Users/username/go1.9/bin/go not found. You need to specify a go1.9 root in CAMLI_GOPHERJS_GOROOT for building gopherjs
> exit status 1
> camlistore (master) $

**Comment by mpl** [comment]
@davronakil actually, no, I still don't understand why your Go 1.9 is not initially detected properly. But https://camlistore-review.googlesource.com/c/camlistore/+/14426 should help with recovery and make things work anyway. And it might help us see the initial problem since I added some debugging.

**Comment by davronakil** [comment]
Phew! Finally some progress. I was able to run `go run make.go` BUT I had to `brew uninstall go` first and then install **go 1.9** specifically (it did not work with **go 1.9.4**. Thanks!

**Comment by mpl** [comment]
@davronakil well, that's good to hear for you, but that's not good. One of the main points of this last CL was indeed to improve and debug the situation with a 3 number version, and it works for me with 1.9.4 here.
If you could retry with 1.9.4 and give us the full output, it would help us find out what's the issue on your end, and fix the problem for maybe other users.
