### ISSUE TITLE
launcher: '[compute-component.googleapis.com]' not found or permission denied., forbidden.

### ISSUE THREAD

**Issue by ctessum** [camlistore/camlistore#943]
What I did:
1. go to: https://camlistore.org/launch/
2. Click "Create Project" (A new project is created)
3. Click "Enable billing", and then link the project to a billing account
4. Click "Create instance"

Expected behavior:
* A new instance to be created

Instead:
* On page: https://camlistore.org/launch/instance?instancekey=xxxxx
* Error: An error occurred while creating your instance: project ID error for camlistore-launcher-xxxxx: googleapi: Error 403: Services '[compute-component.googleapis.com]' not found or permission denied., forbidden.

Additional info:
* Camlistore version deployed by this tool: 8f1a7df176de21d0d052c04db45b373c5c282fb1
* I checked, and the compute engine API was successfully enabled in the project.

Is there something I'm doing wrong here? I have successfully used the launcher before.

**Comment by mpl** [comment]
thanks, I'll check it out and let you know.

**Comment by mpl** [comment]
You're not doing anything wrong, I can reproduce. I bet some google API changed, that's all. I'm on it.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/11046

**Comment by mpl** [comment]
fix now deployed in production as well.

@ctessum please let me know if you're still having issues.

**Comment by ctessum** [comment]
It works now. Thanks!
