### ISSUE TITLE
vendor/gopherjs: update to go 1.9 compatible version

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#949]
after #948  is done.

**Comment by mpl** [comment]
@myitcv please feel free to take care of that one if you're interested.

**Comment by sterchelen** [comment]
Same as #948 ... I can handle it.

**Comment by myitcv** [comment]
Thanks @sterchelen; happy to help with any questions

**Comment by sterchelen** [comment]
Done ! 
https://camlistore-review.googlesource.com/c/camlistore/+/11246
