### ISSUE TITLE
make.go: make sure things don't get uselessly rebuilt

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#957]
Brad pointed out that at least zsearch.go seeems to be regenerated every time make.go is run. Look into that.

**Comment by sterchelen** [comment]
Could I take a look ?

**Comment by sterchelen** [comment]
1. From `make.go:genSearchTypes()` on line 443 we are launching `go generate camlistore.org/app/publisher/js`
2. From `camlistore.org/app/publisher/js/main.go` there is this a go directive :`go:generate go run gensearchtypes.go -out zsearch.go`

**Proposition:**
We could check whether or not if the file is already generated, then if yes, we could check if it's the same as `tmp/build-gopath-nosqlite/src/camlistore.org/app/publisher/js/zsearch.go` ?
Then if the file is the same, we don't launch go generate...

**Comment by mpl** [comment]
I'm already on it. the problem is even though we do check the modtimes, zsearch.go is mirrored from what we have in the repo (and not created by go generate), which actually has an older modtime than the source file it is generated from.

**Comment by mpl** [comment]
I think I'm pretty close so I'm going to send a CL soon, but feel free to beat me to it if you want. maybe you'll come up with a better solution.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/11366

**Comment by mpl** [comment]
@sterchelen also, please don't take this as if we didn't want any help. it just so happens that I had already started on that earlier today. Feel free to work on any issue you're interested in.

**Comment by sterchelen** [comment]
No problem. I'm here to help and to learn !

**Comment by bruceadowns** [comment]
I love the idea of having a self-sufficient make.go. Has anyone considered expanding this to a more generalize build mechanism for the broader golang community?

**Comment by mpl** [comment]
@bruceadowns I'm not sure what you mean. Ideally a go project should not need anything more than "go build/install".
Even though Camlistore is indeed a pretty complex piece of software, I feel it's more of a failure of our part that we do need to have make.go. We should work towards removing that need imho.

Additionally, a large part of it is just to provide an isolated building environment, which is not really needed nowadays with containers.

Anyway, our make.go is mostly specific to Camlistore, so I'm not sure how much you'd want to reuse/generalize for other projects.
