### ISSUE TITLE
app/publisher template expansion broken with html/template in Go 1.9

### ISSUE THREAD

**Issue by sllawap** [camlistore/camlistore#960]
After rebuilding from latest in master branch with Go 1.9 and attempting to hit one of my published endpoints:

```
2017-09-28T05:43:28.699206699Z PUBLISHER: 2017/09/28 05:43:28 Error serving subject template: html/template:subject:28:50: predefined escaper "html" disallowed in template
```

The error appears to be referring to https://github.com/camlistore/camlistore/blob/master/app/publisher/gallery.html#L28

Root cause appears to be: https://go-review.googlesource.com/c/go/+/37880 -- which appears to have been wrapped into Go 1.9.

**Comment by mpl** [comment]
thanks, I'm on it.

**Comment by mpl** [comment]
@sllawap PTAL: https://camlistore-review.googlesource.com/c/camlistore/+/11386

**Comment by sllawap** [comment]
Thanks @mpl -- it works!
