### ISSUE TITLE
camlistored/ui: search results not shown completely, infinite scroll broken

### ISSUE THREAD

**Issue by tdilo** [camlistore/camlistore#961]
When opening the web UI with the default search query, the number of results actually displayed is limited to what can be displayed on the current screen, plus an additional row. Infinite scroll is broken and no further items are loaded when scrolling down.

This also happens when performing explicit search queries, for example "before: 2017-01-01".

Tested with devcam server on latest revision (be77d7a4cbf8).

**Comment by mpl** [comment]
thanks, looking into it.

**Comment by mpl** [comment]
@tdilo I can't reproduce with devcam server on be77d7a4cbf82218fdbe0cd75cac41c77ca78332 , I can see all the pictures I've just devcam put there.

Can you give me more detail? Do you see any server-side errors? or in the dev tools javascript console?

**Comment by tdilo** [comment]
No errors, no. I just checked again in Chromium with a cleared cache in incognito mode, on servers built on two separate machines. Nothing. Then I opened Firefox - works perfectly there! Chrome on Android: broken again.

**Comment by mpl** [comment]
What versions of Chrome/ium and firefox?

**Comment by tdilo** [comment]
Sorry, should have included that from the start. Finally found the time to spend some more time on this. Luckily I still had some unpatched systems available. A pattern emerges!

### Broken:
* Chromium/Linux (Arch) Version 61.0.3163.100 (64-bit)
* Chrome/Linux (Ubuntu 17.04 and 16.04) 61.0.3163.100 (64-bit)
* Chrome/Android 8.0 61.0.3163.98
* Chrome/Windows 10 61.0.3163.100 (64-bit)

### Working:
* Firefox/Linux (Arch) 55.0.3 (64-bit)
* Chrome/Chrome OS 60.3.3112.114 (32-bit)
* Chrome/Linux (Ubuntu 17.04) 60.0.3112.90 (64-bit)

I really doubt it is a bug in camlistore now.

**Comment by mpl** [comment]
yeah I have my doubts too given what I had found out in https://github.com/camlistore/camlistore/issues/937

Still, in case you're not the only one affected, we should look for a fix, even if that means just displaying an error message like: "sorry, you're broken because of bug ### in chrome".

**Comment by mpl** [comment]
@tdilo "good" news, I can reproduce on (android) mobile chrome. Investigating now.

**Comment by mpl** [comment]
@tdilo can you try this and report please?

https://camlistore-review.googlesource.com/#/c/camlistore/+/11426

**Comment by tdilo** [comment]
Looks good, works on Chrome on my phone and in Chromium on the desktop. Thanks. :)

**Comment by mpl** [comment]
@tdilo could you please now try the actual fix, which I believe is:
https://camlistore-review.googlesource.com/c/camlistore/+/5736

**Comment by mpl** [comment]
@tdilo ping?

**Comment by tdilo** [comment]
Sorry, chili harvest got in the way.

CL 5736 works here.

At first, I had some fun with the browser cache, resulting in
```
base.js:664 Uncaught Error: Undefined nameToPath for goog.Promise
    at visitNode (base.js:664)
    at Object.goog.writeScripts_ (base.js:678)
    at Object.goog.require (base.js:385)
    at (index):42
```
and (probably as a result)
`(index):106 Uncaught TypeError: cam.ServerConnection is not a constructor`

I had to clear caches to get rid of the errors.

**Comment by mpl** [comment]
Sorry that I bothered you. I've just realized today that I could reproduce simply by upgrading chrome on my dev system. Still, better two testers than one anyway.

**Comment by tdilo** [comment]
> Still, better two testers than one anyway.
I agree. Glad I could help. :)
