### ISSUE TITLE
links on /importer do not work correctly behind reverse proxy

### ISSUE THREAD

**Issue by sllawap** [camlistore/camlistore#962]
They appear as `http://localhost:3179` (which appears to be either `apiHost` or derived from `listen`) -- would `:authority` be a sensible default here in the HTTP/2 world? Could this be something we missed in #908 ?

**Comment by mpl** [comment]
Well first off, we never did anything, as far as I know, for #908 . You seemed interested in sending a CL so I left that up to you. Let me know on the issue there if you want me to take care of it instead.

My "production" setup is behind a reverse proxy too, and I don't remember having any trouble with the importer, but I'll have a look again, thanks. In the meantime, what do you mean about ":authority"? I don't know what that refers to.

**Comment by mpl** [comment]
yeah so my setup is:

in server-config.json

	"listen": ":3178",
	"baseURL": "https://camli.mydomain.org/",

my frontend is basically a Go reverse-proxy that does:

    camliProxyUrl, _ := url.Parse("https://camli.mydomain.org:3178")
    camliProxy = httputil.NewSingleHostReverseProxy(camliProxyUrl)

    http.HandleFunc("https://camli.mydomain.org/", makeHandler(camliHandler))
    func camliHandler(w http.ResponseWriter, r *http.Request) {
	logger.Printf("for camli proxy: %v", r.URL.Path)
	camliProxy.ServeHTTP(w, r)
    }

And everything seems to be alright when I go to "https://camli.mydomain.org/importer"

What's your setup?

**Comment by sllawap** [comment]
My setup is an nginx reverse proxy which handles auth and SSL termination. I allow HTTP for some endpoints (publisher paths) and HTTPS for all paths.

I need the scheme to be sticky and not serve mixed content. I believe I stopped specifying `baseURL`  because it was causing issues in that area, but it seems to be resolved now.

I can happily report that everything seems to be working. Closing this and #908, since I'm no longer encountering either problem with `baseURL`, `apiHost` and `backendURL` correctly defined.

For posterity, this is my server-config.json

```
{
    "listen": ":3179",
    "baseURL": "https://[redacted]",

    "auth": "none",
    "identity": "[redacted]",
    "identitySecretRing": "/etc/camlistore/identity-secring.gpg",

    "blobPath": "/var/lib/camlistore/blobs",
    "levelDB": "/var/lib/camlistore/index",
    "dbNames": null,

    "shareHandler": true,

    "publish": {
        "/public/": {
            "program": "/path/to/publisher",
            "auth": "none",
            "camliRoot": "publicRoot",
            "cacheRoot": "/var/lib/camlistore/blobs/cache",
            "goTemplate": "gallery.html",
            "apiHost": "http://localhost:3179/",
            "backendURL": "http://localhost:3180/",
            "listen": ":3180",
            "appConfig": {
            }
        }
    }
}
```

Nginx config is more complicated to provide here since it is split across includes, but if you're interested I can tease it out for you. The websocket bits are documented in #816

**Comment by mpl** [comment]
Well, I don't understand what the problem actually was then, and how we fixed it, but good I suppose...
Feel free to reopen if needed.
