### ISSUE TITLE
Update camlistore.net DNS

### ISSUE THREAD

**Issue by angelcabo** [camlistore/camlistore#963]
Is there a way to update the IP address the camlistore.net DNS server is pointing to for a given identity? I have an older instance I deployed using the launcher tool awhile ago and now the IP address as reported using DNS lookup is incorrect for my instance ID in Google Cloud.

My VM should be available at 1015397a.camlistore.net. The IP reported by the camlistore.net lookup seems to be `130.211.173.20` which doesn't match my current `External IP` for the VM running camlistore.

**Comment by mpl** [comment]
Afair, camlistored should have asked the DNS server to automatically update your IP, so something went wrong there. I'll have to look at the code.
Maybe we should have a command-line tool as well to force the update in case of such a bug.
In the meantime, I'll think about what kind of work-around can be done to fix your case.

**Comment by angelcabo** [comment]
After reading the code a little closer it seems just clearing out the `camli-hostname` instance metadata attribute and restarting the server did the trick. Sorry, I didn't realize that would force it to reconfigure itself.

Nevertheless, thanks for the quick response.

**Comment by mpl** [comment]
I've just refreshed my memory as well, and as you can see, we indeed update the record on the DNS every hour if needed, so you shouldn't have needed to restart your server.

Unless it's the other way around? maybe your GCE instance name was wrong somehow (you erased your GPG key at some point or something?)?
Are you saying that your VM name is still 1015397a.camlistore.net now?

**Comment by mpl** [comment]
oh no, I see/remember now. We update the DNS record in case the DNS entries disappear, get corrupted, etc. , but not really to cope with client changes. So if your IP somehow changed, nothing is done about that since we always use the initial GCE instance IP.
I'll fix that.

**Comment by mpl** [comment]
@angelcabo Can you please confirm this is what happened to you:
1) you deployed Camlistore on Google Cloud with the launcher
2) your VM initially had IP X, and name foo.camlistore.net
3) at some point the IP of your VM changed to Y, even though you did not restart your VM. If yes, do you know why your IP changed?
4) as a result the record on the DNS server for foo.camlistore.net was wrongly still set to X instead of Y.

**Comment by angelcabo** [comment]
Yep, that's exactly what happened. I may have restarted the VM at some point though. I'm not sure when or why the IP changed but I don't have a static IP assigned. My instance has an ephemeral external IP.

I got the idea to clear out `camlistore-hostname` by looking at `pkg/serverinit/env.go:78`. It seems if the hostname isn't already there a new challenge is initiated with the DNS server. However, I'm not sure where the actual code to update the name entry is located. Although I notice: `pkg/gpgchallenge/server/main.go:51` the `OnSuccess` handler is planning on adding or updating the name entry at some point.

**Comment by angelcabo** [comment]
doh, accidental closing/opening...sorry

**Comment by mpl** [comment]
What puzzles me is the following:
If the VM had restarted, regardless of whether the IP changes on restart or not, with the code as it is things should have worked.
Which means the IP changed _while_ the VM/server was already running, which seems pretty weird to me. I thought even ephemeral IPs were staying booked as long as they are in use.

Anyway, I'll try to add the code to deal with the case of the IP changing at any time.

**Comment by mpl** [comment]
this https://camlistore-review.googlesource.com/c/camlistore/+/11446 should help, but i need to test it first
