### ISSUE TITLE
camlistored/ui: doesn't display in Edge

### ISSUE THREAD

**Issue by broomhall** [camlistore/camlistore#964]
When loading the UI, Edge receives a 401 while getting leaflet.js. This stops the UI from displaying.

It looks like Edge isn't sending the basic auth credentials, resulting in the 401. I'm guessing it's taking a rather hard-line view on the [CORS settings attribute][1] as used in `server/camlistored/ui/index.html`. Using the `crossorigin=""`, which maps to the anonymous state, seems to mean that Edge doesn't send the credentials, even though the request is for the same origin. Removing the attributes `integrity="blah"` and `crossorigin=""` in the two places it's used seems to fix the issue. Alternatively I reckon changing to `crossorigin="use-credentials"` would also fix the issue, although I haven't tested it.

I don't really understand why the integrity and CORS settings attributes are specified for leaflet.js as it is not being requesting from a CDN. Also it's the only resource that does make use of those attribs.

I may be using an old version of Edge -- 38.14393.1066.0

[1]: https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes

**Comment by mpl** [comment]
thanks for the report.

you're completely right. integrity is most likely completely useless as the files come from the Camlistore server.

As to why they were there in the first place, my laziness is to blame. I had pasted them from an example when I started working on the map aspect, and I forgot to check their meaning afterwards.

PTAL: https://camlistore-review.googlesource.com/c/camlistore/+/11486

**Comment by mpl** [comment]
I'm curious though, shouldn't I be able to reproduce what you're seeing with e.g. chrome if I explicitly set crossorigin="anonymous" ? I haven't been able to do so.

**Comment by broomhall** [comment]
Just tried the patch in devcam server and it seems to fix the issue on Edge. Thanks for the prompt response.

I suspect it's an Edge-specific quirk. The request for leaflet.js is to the same origin as index.html so I reckon most browsers disregard the crossorigin attribute. I've not seen the issue with Firefox or IE11.

BTW `crossorigin="anonymous"` should be equivalent to `crossorigin=""` if implemented as per the [whatwg standard][1].

[1]: https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes
