### ISSUE TITLE
Web UI help page has link to broken camlistore.org community page 

### ISSUE THREAD

**Issue by dlipovetsky** [camlistore/camlistore#967]
The [help page links](https://github.com/camlistore/camlistore/blob/27b2442475caf91fb181efb9a39b58c367b9afec/pkg/server/help.go#L59.
) to the [community page](https://camlistore.org/community/) with a trailing slash. The page is broken because of the trailing slash. Between the header and footer, the page just shows:
> lstat /var/camweb/src/camlistore.org/website/content/community/.html: no such file or directory

Running the website server locally, I see that the error is returned by [this os.Lstat call](https://github.com/camlistore/camlistore/blob/39cd6029e35db4738bea11babfaaf0cdf3c7e78a/website/camweb.go#L344).

Since the server redirects when a request maps to a directory but is missing a trailing slash, it could also redirect when a request maps to a file but includes a trailing slash. I'll submit a PR.

**Comment by mpl** [comment]
Thanks for the report. Please see my answer on the PR.
