### ISSUE TITLE
Android build: failure to detect docker

### ISSUE THREAD

**Issue by tdilo** [camlistore/camlistore#973]
On my machine, `build-in-docker.go` fails to detect that it's actually running inside of a Docker container and exits with an error:
```
Usage error: this program should be run within a docker container
exit status 2
```

The problem is that `/proc/self/cgroup` (in the container) contains the line `0::/system.slice/docker.service`, which `inDocker()` rejects as the last field does not start with `/docker`.

Maybe this is just a Docker configuration issue on my side and not actually a bug in the build. Needs investigation, filing the bug as a reminder to do some research.

## Machine info
Arch Linux

```
$ docker version
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:08:56 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.9.1
 Git commit:   f4ffd2511c
 Built:        Wed Oct 18 23:09:11 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ uname -a
Linux 2d417ce7b386 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux

$ systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2017-11-08 23:25:37 CET; 36min ago
     Docs: https://docs.docker.com
 Main PID: 11230 (dockerd)
    Tasks: 27 (limit: 4915)
   CGroup: /system.slice/docker.service
           ├─11230 /usr/bin/dockerd -H fd://
           └─11237 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock [...]
```

**Comment by mpl** [comment]
nah I don't think the problem is with your setup. that check probably only works with old docker setups. looking into it...

**Comment by mpl** [comment]
What does

    docker info | grep -i cgroup

say for you?

**Comment by tdilo** [comment]
`Cgroup Driver: cgroupfs`

**Comment by mpl** [comment]
@tdilo Even on a system that I thought was the most similar to yours, I haven't been able to reproduce the problem, so until we figure out something better, I suggest we just fix it the dumb way:

https://camlistore-review.googlesource.com/#/c/camlistore/+/11586

Does that work for you?

**Comment by tdilo** [comment]
I checked on
* CoreOS  stable (unsure of exact version, as the DigitalOcean dashboard _just_ went down), which does not have the problematic entry
* Docker 17.09.0-ce on Ubuntu 17.10, which does indeed have the same cgroup configuration as my system

That's an indication at least that my system is not horribly broken and that the fix is not just a workaround.
