### ISSUE TITLE
vendor: Upgrade to non-patent-encumbered license of React

### ISSUE THREAD

**Issue by lindner** [camlistore/camlistore#977]
See the [React 16 Blog Post](https://reactjs.org/blog/2017/09/26/react-v16.0.html 
) for details.

Either version 16+ or version 15.6.2 have the new license.

**Comment by bradfitz** [comment]
You interested in doing this?

**Comment by myitcv** [comment]
Probably best to upgrade to 15.6.2 for now because I'm not entirely certain (read: I haven't tried it out fully yet) how React 16 plays with `myitcv.io/react`, the GopherJS bindings around React used by a couple of components.

**Comment by lindner** [comment]
Agree 15.6.2 would be easier.  I'm new to React but it appears that the addons have been discontinued.  It also appears that there's no easy canonical source package to embed.

**Comment by lindner** [comment]
Proposed update in 

https://camlistore-review.googlesource.com/c/camlistore/+/11827

**Comment by myitcv** [comment]
FYI as of https://github.com/myitcv/react/pull/103 I've upgraded `myitcv.io/react` to use React 16.

Per [the wiki](https://github.com/myitcv/react/wiki#react-16), React 15 support will be maintained on a branch, probably following the Go-esque policy of "last two versions"

Not all features in React 16 supported (most notably fragments) but will work on the most important over the Christmas break.
