### ISSUE TITLE
UI: font awesome missing

### ISSUE THREAD

**Issue by tajtiattila** [camlistore/camlistore#982]
The problem is that genfileembed uses the path style of the host when building embedded files.

When building on Windows, embedded resources in subdirectories end up added with backslashes without slashes, eg.

`"css\\font-awesome.min.css"`

instead of

`"css/font-awesome.min.css"`

which is incorrect for the web server even on Windows.

See also https://groups.google.com/forum/#!topic/camlistore/OwD5diVIuys

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/c/camlistore/+/11966
