### ISSUE TITLE
investigate https://mat.tm/joy/

### ISSUE THREAD

**Issue by mpl** [camlistore/camlistore#983]
We're already heavily invested with GopherJS, and I doubt Joy is more mature, but you never know...

CC @myitcv

**Comment by myitcv** [comment]
Thanks for the cc. I saw the link somewhere earlier and I've subscribed to updates. 

We could/should also add a tracker for the WASM issue in the Go repo?

https://github.com/golang/go/issues/18892

On the basis that's another means of writing Go code for the frontend (although much like the joy project, the implementation path is less clear than the status quo of GopherJS)

**Comment by bradfitz** [comment]
I think we want to stick with GopherJS. I don't want to write in a subset dialect of Go.

**Comment by myitcv** [comment]
Agreed. 

_Comments below based on a quick skim of the available docs_

There are some good [guiding principles](https://mat.tm/joy/#principles) for Joy:

> 1. Code is written once, read many times
> 2. Less syntax is better than prettier syntax
> 3. Typed code is easier to update and maintain
> 4. Avoid large runtimes and unused code
> 5. Don’t break browser support without a good reason
> 6. Generate concise Javascript from idiomatic Go
> 7. Embrace standard libraries and standard tools

Points 1, 2, 3, 5 and 7 are very much Go's domain and principles that are, therefore, shared with GopherJS. 

Points 4 and 6 are criticisms that can, to a point, be levelled at GopherJS; they are well known, well defined points of optimisation within the compiler (that are still open).

I have to admit, I'm a little confused about principle 7 however, given [this statement](https://mat.tm/joy/#go-interop):

> Most existing Go code does not yet compile to Javascript. This is because most of the standard library still needs to be translated to Javascript. 

Which seems to suggest this is being done by hand? Doesn't sound like the right approach to me.

So my conclusion as to the "best way forward" still remains:

* GopherJS (which can, if someone had the time/money, be optimised)
* The WASM work + some Javascript interop
