### ISSUE TITLE
gphotos: instructions incomplete

### ISSUE THREAD

**Issue by bradfitz** [camlistore/camlistore#984]
I followed the gphotos importer setup instructions, but got an internal error from perkeep on the oauth redirect back to my instance.

Logs say:

> gphotos: 2017/12/14 21:35:29 couldn't get username: googleapi: Error 403: Access Not Configured. Drive API has not been used in project 169419785751 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=169419785751 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured

I guess our setup instructions are missing the step of enabling an API for the project.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/12166
