### ISSUE TITLE
Launcher shows blank page

### ISSUE THREAD

**Issue by ZucchiniZe** [camlistore/camlistore#985]
https://perkeep.org/launch/ shows a blank page when visited. Upon further investigation it shows a little html but stops at the `go-import` meta tag in the head. 

https://github.com/camlistore/camlistore/blob/c45893a69b93f240ce75af410d18331872321777/website/tmpl/page.html#L19

It seems that the domain variable is causing an error and not allowing the entire page to be loaded.

**Comment by mpl** [comment]
thanks, looking into it.

**Comment by mpl** [comment]
https://camlistore-review.googlesource.com/#/c/camlistore/+/12206
