### ISSUE TITLE
website/website fails to start due to domain, source package mismatch

### ISSUE THREAD

**Issue by lindner** [camlistore/camlistore#997]
Trying to use the instructions in website/README.md:

- cd website
- go build
- ./website

fails with an error like this:

  2017/12/27 14:21:23 Failed to find the root of the perkeep.org source code via osutil.GoPackagePath: file does not exist

The issue results from assuming that prodDomain is equal to the source package name.  Packages are still in the camlistore.org namespace, which means that the website binary cannot find content to serve.

**Comment by mpl** [comment]
Yes, this is expected, as are probably a few other things until the the migration is complete.
There is no valid source code for the perkeep.org namespace yet, so there's no point yet in trying to build/use it as such. Hence, the website should still be built/used under the camlistore.org namespace for now.

**Comment by mpl** [comment]
Should be fixed by https://camlistore-review.googlesource.com/c/camlistore/+/12630

**Comment by willnorris** [comment]
confirmed that the above instructions now work.
